import { describe, expect, it } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { runRenovationFolderWorkflow } from '../server/skills/bundled/cad-drafting/renovation_workflow';

describe('cad renovation folder workflow', () => {
  it('extracts source facts but never generates a default floor plan', async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'lumi_cad_renovation_'));
    try {
      fs.writeFileSync(path.join(dir, 'requirements.txt'), `
Project: two-bedroom renovation
Overall dimensions: 9000mm x 7600mm
Area: 68m2
Rooms: 玄关、客厅、餐厅、厨房、主卧、次卧、卫生间、阳台
Style: 原木 现代简约
Budget: 18万元
Needs: 收纳 干湿分离 书桌
Constraints: 承重墙 燃气 下水 采光
`, 'utf-8');
      fs.writeFileSync(path.join(dir, 'floorplan.png'), 'reference placeholder', 'utf-8');

      const result = await runRenovationFolderWorkflow({
        folderPath: dir,
        projectName: 'Two-bedroom renovation',
        stylePreference: 'natural wood modern',
        writeFiles: true,
        maxFiles: 20,
      });

      expect(result.filesRead.map(file => file.name)).toContain('requirements.txt');
      expect(result.referenceImages.map(file => file.name)).toContain('floorplan.png');
      expect(result.signals.rooms.map(room => room.name)).toEqual(expect.arrayContaining(['客厅', '厨房']));
      expect(result.geometry.calibrated).toBe(true);
      expect(result.geometry.widthMm).toBe(9000);
      expect(result.geometry.heightMm).toBe(7600);
      expect(result.geometry.rooms).toEqual([]);
      expect(result.cadFiles).toEqual([]);
      expect(result.sourceInventoryOnly).toBe(true);
      expect(result.completionEligible).toBe(false);
      expect(result.workflowState).toBe('awaiting_image_geometry_extraction');
      expect(result.primaryReferenceImage).toBe(path.join(dir, 'floorplan.png'));
      expect(result.recommendedToolCalls.map(call => call.tool)).toEqual([
        'floorplan_extract_geometry',
        'cad_prepare_autocad_operations',
        'mcp_cad-drafting_autocad_playback_file',
        'cad_generate_dxf',
      ]);

      const outputDir = result.outputDir || '';
      const inventoryPath = path.join(outputDir, '00_source_inventory.md');
      const requirementsPath = path.join(outputDir, '02_extracted_requirements.md');
      expect(fs.existsSync(inventoryPath)).toBe(true);
      expect(fs.readFileSync(inventoryPath, 'utf-8')).toContain('CAD files generated by this scan: none');
      expect(fs.readFileSync(requirementsPath, 'utf-8')).toContain('This file records source facts only');
      expect(fs.readdirSync(outputDir).some(name => /\.(?:dxf|dwg|svg|ifc|rvt)$/i.test(name))).toBe(false);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('writes a source inventory by default without creating CAD artifacts', async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'lumi_cad_renovation_default_write_'));
    try {
      fs.writeFileSync(path.join(dir, 'dimensions.txt'), 'Overall dimensions 8000mm x 6500mm, 客厅、厨房、卧室。', 'utf-8');
      const result = await runRenovationFolderWorkflow({ folderPath: dir, projectName: 'Source inventory' });

      expect(result.outputDir).toBe(path.join(dir, 'LumiCAD_Source_Inventory'));
      expect(result.workflowState).toBe('source_inventory_ready');
      expect(result.draftFiles.every(file => file.path && fs.existsSync(file.path))).toBe(true);
      expect(result.cadFiles).toEqual([]);
      expect(result.warnings.join(' ')).toContain('never generates CAD');
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('returns source-inventory previews without writing files when writeFiles is false', async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'lumi_cad_renovation_preview_'));
    try {
      fs.writeFileSync(path.join(dir, 'source.txt'), '两室 户型 面积 65㎡ 客厅 厨房 主卧 次卧 卫生间 风格：奶油风', 'utf-8');

      const result = await runRenovationFolderWorkflow({
        folderPath: dir,
        projectName: 'Preview inventory',
        writeFiles: false,
        maxFiles: 5,
      });

      expect(result.outputDir).toBeUndefined();
      expect(result.draftFiles.length).toBeGreaterThan(0);
      expect(result.draftFiles.every(file => !file.path && file.preview.length > 0)).toBe(true);
      expect(result.cadFiles).toEqual([]);
      expect(fs.existsSync(path.join(dir, 'LumiCAD_Source_Inventory'))).toBe(false);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});
