import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { listGeneratedSkillHistory } from '../server/skills/generated_history';

const roots: string[] = [];
afterEach(() => { for (const root of roots.splice(0)) {
  if (path.dirname(root) !== path.resolve(os.tmpdir()) || !path.basename(root).startsWith('lumi-generated-history-')) throw Error('Unsafe test cleanup');
  fs.rmSync(root, { recursive: true, force: true });
} });
describe('persistent local generated skill history', () => {
  it('includes installed generated skills, deduplicates their exact draft, and retains other draft versions', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'lumi-generated-history-')); roots.push(root);
    const draftsRoot = path.join(root, 'drafts'), skillsRoot = path.join(root, 'skills');
    const write = (base: string, name: string, lumi: object) => {
      fs.mkdirSync(path.join(base, name), { recursive: true });
      fs.writeFileSync(path.join(base, name, 'package.json'), JSON.stringify({ description: 'Order totals: Compute current rows', lumi }));
    };
    write(skillsRoot, 'totals', { generatedByLumi: true, managedSkill: { origin: 'generated', reviewHash: 'approved' } });
    write(skillsRoot, 'store-calculator', { autoGenerated: false });
    write(draftsRoot, 'totals-approved', { autoGenerated: true, status: 'draft', skillName: 'totals', draftReview: { contentHash: 'approved' } });
    write(draftsRoot, 'totals-next', { autoGenerated: true, status: 'draft', skillName: 'totals', draftReview: { contentHash: 'next' } });
    const input = { draftsRoot, skillsRoot, runtimeStates: [{ name: 'totals', enabled: true, usable: true, broken: false }] };
    const rows = listGeneratedSkillHistory(input);
    expect(rows).toHaveLength(2);
    expect(rows).toContainEqual(expect.objectContaining({ skillName: 'totals', displayName: 'Order totals', status: 'installed', reviewHash: 'approved' }));
    expect(rows).toContainEqual(expect.objectContaining({ status: 'draft', draftId: 'totals-next' }));
    expect(JSON.stringify(rows)).not.toContain(root);
    expect(listGeneratedSkillHistory({ ...input, runtimeStates: [] }).find(item => !item.draftId)?.status).toBe('broken');
    expect(listGeneratedSkillHistory({ ...input, runtimeStates: [{ name: 'totals', enabled: false, usable: false, broken: false }] }).find(item => !item.draftId)?.status).toBe('disabled');
    // A fresh reader reproduces history from disk, without session state.
    expect(listGeneratedSkillHistory(input)).toEqual(rows);
  });
});
