import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import {
  rollbackRuntimeCapabilityCleanup,
  runRuntimeCapabilityCleanup,
} from '../server/mcp/runtime_cleanup';

const tempPaths: string[] = [];

afterEach(() => {
  for (const target of tempPaths.splice(0)) {
    fs.rmSync(target, { recursive: true, force: true });
  }
});

function createSkill(
  skillsDir: string,
  name: string,
  options: { autoGenerated?: boolean; generatedMarker?: boolean } = {},
): string {
  const skillDir = path.join(skillsDir, name);
  fs.mkdirSync(skillDir, { recursive: true });
  fs.writeFileSync(path.join(skillDir, 'package.json'), JSON.stringify({
    name: `lumi-skill-${name}`,
    lumi: { autoGenerated: options.autoGenerated === true },
  }));
  fs.writeFileSync(
    path.join(skillDir, 'index.ts'),
    `${options.generatedMarker ? '// Auto-generated Lumi Skill\n' : ''}export {};\n`,
  );
  return skillDir;
}

describe('MCP runtime capability cleanup', () => {
  it('quarantines historical generated skills and preserves managed skills and custom servers', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'lumi-runtime-cleanup-'));
    tempPaths.push(root);
    const configPath = path.join(root, 'data', 'mcp_config.json');
    const skillsDir = path.join(root, 'lumi_skills');
    const quarantineRoot = path.join(root, 'data', 'quarantine', 'generated-skills');
    fs.mkdirSync(path.dirname(configPath), { recursive: true });

    createSkill(skillsDir, 'generated-in-config', { autoGenerated: true });
    createSkill(skillsDir, 'generated-from-source', { generatedMarker: true });
    createSkill(skillsDir, 'cad-drafting');
    fs.writeFileSync(configPath, JSON.stringify({
      mcpServers: {
        filesystem: {
          command: 'npx',
          args: ['-y', '@modelcontextprotocol/server-filesystem', '.'],
          enabled: true,
        },
        'generated-in-config': {
          command: 'npx',
          args: ['tsx', '~/lumi_skills/generated-in-config/index.ts'],
          enabled: true,
          autoGenerated: true,
          cachedTools: [{ name: 'stale-tool' }],
        },
        'generated-from-source': {
          command: 'npx',
          args: ['tsx', '~/lumi_skills/generated-from-source/index.ts'],
          enabled: true,
        },
        'missing-generated': {
          command: 'npx',
          args: ['tsx', '~/lumi_skills/missing-generated/index.ts'],
          enabled: true,
          autoGenerated: true,
        },
        'cad-drafting': {
          command: 'npx',
          args: ['tsx', '~/lumi_skills/cad-drafting/index.ts'],
          enabled: true,
          autoGenerated: false,
        },
        'custom-files': {
          command: 'node',
          args: ['custom-filesystem-server.js'],
          enabled: true,
        },
      },
    }));

    const report = runRuntimeCapabilityCleanup({
      configPath,
      skillsDir,
      quarantineRoot,
      now: new Date('2026-07-23T06:00:00.000Z'),
    });

    expect(report.applied).toBe(true);
    expect(report.removedServerNames).toEqual([
      'generated-from-source',
      'generated-in-config',
      'missing-generated',
    ]);
    expect(report.quarantinedSkills.map(skill => skill.name)).toEqual([
      'generated-from-source',
      'generated-in-config',
    ]);
    expect(report.errors).toEqual([]);
    expect(fs.existsSync(path.join(skillsDir, 'generated-in-config'))).toBe(false);
    expect(fs.existsSync(path.join(skillsDir, 'generated-from-source'))).toBe(false);
    expect(fs.existsSync(path.join(skillsDir, 'cad-drafting'))).toBe(true);
    expect(report.backupPath && fs.existsSync(report.backupPath)).toBe(true);
    expect(report.skillManifestPath && fs.existsSync(report.skillManifestPath)).toBe(true);
    expect(report.reportPath && fs.existsSync(report.reportPath)).toBe(true);

    const persisted = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    expect(persisted.mcpServers.filesystem.enabled).toBe(false);
    expect(persisted.mcpServers['generated-in-config']).toBeUndefined();
    expect(persisted.mcpServers['generated-from-source']).toBeUndefined();
    expect(persisted.mcpServers['missing-generated']).toBeUndefined();
    expect(persisted.mcpServers['cad-drafting'].enabled).toBe(true);
    expect(persisted.mcpServers['custom-files'].enabled).toBe(true);
    expect(persisted.migrations).toEqual({
      runtimeCapabilityCleanupV1: 1,
      desktopBuiltinFilesystem: 2,
    });
  });

  it('is idempotent after the versioned migration marker is persisted', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'lumi-runtime-cleanup-once-'));
    tempPaths.push(root);
    const configPath = path.join(root, 'mcp_config.json');
    const skillsDir = path.join(root, 'lumi_skills');
    const quarantineRoot = path.join(root, 'quarantine');
    fs.mkdirSync(skillsDir, { recursive: true });
    fs.writeFileSync(configPath, JSON.stringify({
      mcpServers: {},
      migrations: {
        runtimeCapabilityCleanupV1: 1,
        desktopBuiltinFilesystem: 2,
      },
    }));
    createSkill(skillsDir, 'approved-user-skill');

    const report = runRuntimeCapabilityCleanup({
      configPath,
      skillsDir,
      quarantineRoot,
      now: new Date('2026-07-23T06:00:00.000Z'),
    });

    expect(report.applied).toBe(false);
    expect(fs.existsSync(path.join(skillsDir, 'approved-user-skill'))).toBe(true);
    expect(fs.existsSync(quarantineRoot)).toBe(false);
  });

  it('rolls a completed cleanup back without overwriting existing skill directories', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'lumi-runtime-cleanup-rollback-'));
    tempPaths.push(root);
    const configPath = path.join(root, 'data', 'mcp_config.json');
    const skillsDir = path.join(root, 'lumi_skills');
    const quarantineRoot = path.join(root, 'data', 'quarantine', 'generated-skills');
    fs.mkdirSync(path.dirname(configPath), { recursive: true });
    createSkill(skillsDir, 'historical-generated', { autoGenerated: true });
    const originalConfig = {
      mcpServers: {
        'historical-generated': {
          command: 'npx',
          args: ['tsx', '~/lumi_skills/historical-generated/index.ts'],
          enabled: true,
          autoGenerated: true,
        },
      },
    };
    fs.writeFileSync(configPath, JSON.stringify(originalConfig));

    const cleanup = runRuntimeCapabilityCleanup({
      configPath,
      skillsDir,
      quarantineRoot,
      now: new Date('2026-07-23T08:00:00.000Z'),
    });
    const rollback = rollbackRuntimeCapabilityCleanup(cleanup.reportPath!);

    expect(rollback.rolledBack).toBe(true);
    expect(rollback.restoredSkills).toEqual(['historical-generated']);
    expect(fs.existsSync(path.join(skillsDir, 'historical-generated', 'index.ts'))).toBe(true);
    expect(JSON.parse(fs.readFileSync(configPath, 'utf8'))).toEqual(originalConfig);
    expect(rollback.rollbackBackupPath && fs.existsSync(rollback.rollbackBackupPath)).toBe(true);
  });
});
