import './helpers';
import { beforeEach, describe, expect, it, vi } from 'vitest';

const runtimeFixture = vi.hoisted(() => ({
  localSkills: [] as Array<Record<string, any>>,
  config: {} as Record<string, any>,
  health: {} as Record<string, any>,
  connected: [] as string[],
  keys: {} as Record<string, string>,
  marketplace: [] as Array<Record<string, any>>,
  signedExtensions: [] as Array<Record<string, any>>,
}));

vi.mock('../server/config/keys', () => ({
  loadKeys: () => runtimeFixture.keys,
}));

vi.mock('../server/mcp/client', () => ({
  mcpManager: {
    listLocalSkills: () => runtimeFixture.localSkills,
    getConfig: () => runtimeFixture.config,
    getServerHealth: () => runtimeFixture.health,
    getConnectedServers: () => runtimeFixture.connected,
  },
}));

vi.mock('../server/adapters/registry', () => ({
  getAdapterRegistry: () => ({ adapters: [] }),
}));

vi.mock('../server/marketplace/registry', () => ({
  getMarketplaceSkills: () => runtimeFixture.marketplace,
}));

vi.mock('../server/extensions/registry', () => ({
  listExtensionRuntimeSnapshots: () => runtimeFixture.signedExtensions,
}));

vi.mock('../server/self_extension/capability_memory', () => ({
  isCapabilityLearningRecordVerified: () => false,
  listCapabilityLearningRecords: () => [],
}));

import { buildSelfExtensionPlan } from '../server/self_extension/pipeline';
import { getExtensionRuntimeStates } from '../server/skills/runtime_state';

function localSkill(name: string, overrides: Record<string, any> = {}) {
  return {
    name,
    description: `${name} test skill`,
    toolCount: 1,
    autoGenerated: false,
    installedAt: '2026-09-01T00:00:00.000Z',
    source: 'local',
    broken: false,
    ...overrides,
  };
}

function manifestEntry(overrides: Record<string, any> = {}) {
  return {
    toolName: 'mcp_callable_skill_run',
    capabilityId: 'callable_skill.run',
    source: 'skill',
    executable: true,
    provenance: {
      kind: 'skill',
      provider: 'callable_skill',
      trust: 'user-reviewed',
    },
    ...overrides,
  } as any;
}

describe('skill runtime availability truth', () => {
  beforeEach(() => {
    runtimeFixture.localSkills = [];
    runtimeFixture.config = {};
    runtimeFixture.health = {};
    runtimeFixture.connected = [];
    runtimeFixture.keys = {};
    runtimeFixture.marketplace = [];
    runtimeFixture.signedExtensions = [];
  });

  it('does not treat a directory, disabled config, missing key, or absent registration as usable', () => {
    runtimeFixture.localSkills = [
      localSkill('directory_only'),
      localSkill('disabled_skill'),
      localSkill('missing_key_skill'),
      localSkill('unregistered_skill'),
    ];
    runtimeFixture.config = {
      disabled_skill: { enabled: false, source: 'local' },
      missing_key_skill: {
        enabled: true,
        source: 'local',
        requiresApiKey: true,
        apiKeyEnv: 'MISSING_SKILL_KEY',
      },
      unregistered_skill: { enabled: true, source: 'local' },
    };

    const byName = new Map(
      getExtensionRuntimeStates([
        manifestEntry({
          toolName: 'mcp_disabled_skill_run',
          provenance: { kind: 'skill', provider: 'disabled_skill', trust: 'user-reviewed' },
        }),
        manifestEntry({
          toolName: 'mcp_missing_key_skill_run',
          provenance: { kind: 'skill', provider: 'missing_key_skill', trust: 'user-reviewed' },
        }),
      ]).map(state => [state.name, state]),
    );

    expect(byName.get('directory_only')).toMatchObject({
      packagePresent: true,
      configured: false,
      registered: false,
      usable: false,
      status: 'not_configured',
    });
    expect(byName.get('disabled_skill')).toMatchObject({
      configured: true,
      enabled: false,
      registered: true,
      usable: false,
      status: 'disabled',
    });
    expect(byName.get('missing_key_skill')).toMatchObject({
      enabled: true,
      keyReady: false,
      registered: true,
      usable: false,
      status: 'configuration_required',
    });
    expect(byName.get('unregistered_skill')).toMatchObject({
      enabled: true,
      keyReady: true,
      registered: false,
      usable: false,
      status: 'installed_unregistered',
    });
  });

  it('requires an executable skill/MCP manifest entry from the exact provider before reporting callable', () => {
    runtimeFixture.localSkills = [localSkill('callable_skill')];
    runtimeFixture.config = {
      callable_skill: { enabled: true, source: 'local' },
    };
    runtimeFixture.connected = ['callable_skill'];
    runtimeFixture.health = { callable_skill: { status: 'healthy' } };

    const rejected = getExtensionRuntimeStates([
      manifestEntry({
        toolName: 'mcp_provider_prefix_run',
        provenance: { kind: 'skill', provider: 'callable_skill_extra', trust: 'user-reviewed' },
      }),
      manifestEntry({ executable: false }),
      manifestEntry({ source: 'builtin' }),
    ]).find(state => state.name === 'callable_skill');

    expect(rejected).toMatchObject({
      connected: true,
      registered: false,
      usable: false,
      status: 'installed_unregistered',
      toolNames: [],
    });

    const callable = getExtensionRuntimeStates([
      manifestEntry(),
    ]).find(state => state.name === 'callable_skill');

    expect(callable).toMatchObject({
      packagePresent: true,
      configured: true,
      enabled: true,
      keyReady: true,
      connected: true,
      healthStatus: 'healthy',
      registered: true,
      usable: true,
      status: 'callable',
      toolNames: ['mcp_callable_skill_run'],
      manifestCapabilityIds: ['callable_skill.run'],
    });
  });

  it('plans an exact Skill Hall install instead of the legacy generic install tool', () => {
    runtimeFixture.marketplace = [{
      id: 'skill-orchard-telemetry',
      name: 'Orchard Telemetry',
      description: 'Collect orchard telemetry into a repeatable report.',
      author: 'Lumi Official',
      downloads: 0,
      rating: 0,
      category: 'Operations',
      icon: 'Activity',
      installSource: 'bundled',
      installPath: 'D:/fixtures/orchard-telemetry',
      installed: false,
    }];

    const plan = buildSelfExtensionPlan({
      userId: 'skill_runtime_truth_user',
      goal: 'Collect orchard telemetry into a report',
      domain: 'general',
      tools: [],
      capabilityManifest: [],
    });

    expect(plan.readiness).toBe('install_or_repair_skill');
    expect(plan.resolution).toMatchObject({
      decision: 'repair_or_install_skill',
      primarySource: 'marketplace_skill',
      preferredTools: ['skill_marketplace_install'],
      shouldCreateNewCapability: false,
    });
    expect(plan.pipeline).toContainEqual(expect.objectContaining({
      status: 'confirm_first',
      tool: 'skill_marketplace_install',
      args: { skillId: 'skill-orchard-telemetry' },
    }));
    expect(plan.pipeline.map(step => step.tool)).not.toContain('install_skill');
  });

  it('keeps a community discovery result out of the executable install route', () => {
    runtimeFixture.marketplace = [{
      id: 'skill-community-orchard',
      name: 'Community Orchard Sync',
      description: 'Synchronize orchard observations.',
      author: 'Community',
      downloads: 0,
      rating: 0,
      category: 'Operations',
      icon: 'Activity',
      installSource: 'community',
      installPath: 'D:/untrusted/community-orchard',
      installed: false,
    }];

    const plan = buildSelfExtensionPlan({
      userId: 'skill_runtime_truth_user',
      goal: 'Synchronize orchard observations',
      domain: 'general',
      tools: [],
      capabilityManifest: [],
    });

    expect(plan.existingCoverage.marketplaceSkills[0]).toMatchObject({
      installSource: 'community',
      installable: false,
    });
    expect(plan.resolution.decision).toBe('research_adapter');
    expect(plan.pipeline).not.toContainEqual(expect.objectContaining({
      tool: 'skill_marketplace_install',
      args: { skillId: 'skill-community-orchard' },
    }));
  });

  it('orders a general gap through Skill Hall and external MCP discovery before generation', () => {
    const plan = buildSelfExtensionPlan({
      userId: 'skill_runtime_truth_user',
      goal: 'Normalize a proprietary orchard sensor export',
      domain: 'general',
      tools: [],
      capabilityManifest: [],
    });
    const tools = plan.pipeline.map(step => step.tool).filter(Boolean);
    const signedExtensions = tools.indexOf('extension_registry_list');
    const skillSearch = tools.indexOf('skill_marketplace_search');
    const externalCandidates = tools.indexOf('external_control_candidates');
    const research = tools.indexOf('capability_research');
    const generate = tools.indexOf('generate_skill');

    expect(plan.resolution).toMatchObject({
      decision: 'research_adapter',
      preferredTools: ['capability_research'],
    });
    expect(signedExtensions).toBeGreaterThanOrEqual(0);
    expect(skillSearch).toBeGreaterThan(signedExtensions);
    expect(externalCandidates).toBeGreaterThan(skillSearch);
    expect(research).toBeGreaterThan(externalCandidates);
    expect(generate).toBeGreaterThan(research);
    expect(plan.pipeline[generate]?.notes).toContain('same task');
  });

  it('reuses a live signed extension before Skill Hall, external MCP, or generation', () => {
    runtimeFixture.signedExtensions = [{
      extensionId: 'orchard.signed',
      revisionId: 'revision-orchard-1',
      name: 'Orchard Sensor Bridge',
      version: '1.0.0',
      kind: 'plugin',
      revisionStatus: 'active',
      manifestDigest: 'a'.repeat(64),
      signerFingerprint: 'b'.repeat(64),
      registered: true,
      usable: true,
      runtimeStatus: 'registered',
      registeredToolNames: ['orchard_signed_read_sensor'],
      declaredToolCount: 1,
      keyReady: true,
      providerId: '',
      providerModelIds: [],
    }];

    const plan = buildSelfExtensionPlan({
      userId: 'skill_runtime_truth_user',
      goal: 'Read the orchard sensor bridge',
      domain: 'general',
      tools: [],
      capabilityManifest: [],
    });

    expect(plan.readiness).toBe('use_existing');
    expect(plan.resolution).toMatchObject({
      decision: 'use_existing_coverage',
      primarySource: 'signed_extension',
      preferredTools: ['orchard_signed_read_sensor'],
      shouldCreateNewCapability: false,
    });
    expect(plan.existingCoverage.signedExtensions[0]).toMatchObject({
      extensionId: 'orchard.signed',
      usable: true,
      runtimeStatus: 'registered',
    });
    expect(plan.pipeline).toContainEqual(expect.objectContaining({
      tool: 'orchard_signed_read_sensor',
      status: 'available_now',
    }));
    expect(plan.pipeline.map(step => step.tool)).not.toContain('external_control_candidates');
    expect(plan.pipeline.map(step => step.tool)).not.toContain('generate_skill');
  });

  it.each([
    ['帮我整理财税发票并核对报销预算', 'finance'],
    ['把这份合同交给律师审查庭审风险', 'legal'],
    ['接入企业微信后回复这条消息', 'messaging'],
    ['分析当前客户端窗口并切换聊天模式', 'client_control'],
    ['读取这个文件夹里的 PDF 文档资料', 'files'],
  ])('keeps Chinese capability gaps on their intended domain: %s', (goal, expectedDomain) => {
    const plan = buildSelfExtensionPlan({
      userId: 'skill_runtime_truth_user',
      goal,
      tools: [],
      capabilityManifest: [],
    });

    expect(plan.domain).toBe(expectedDomain);
    expect(plan.pipeline[0]).toMatchObject({ tool: 'adapter_registry_list' });
    expect(plan.pipeline[1]).toMatchObject({ tool: 'extension_registry_list' });
    expect(plan.pipeline[2]).toMatchObject({ tool: 'skill_marketplace_search' });
  });
});
