import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const childProcessMocks = vi.hoisted(() => ({
  exec: vi.fn(),
}));

vi.mock('child_process', async () => {
  const actual = await vi.importActual<typeof import('child_process')>('child_process');
  return {
    ...actual,
    exec: childProcessMocks.exec,
  };
});

import { getDataPath } from '../server/config/data_path';
import {
  computeGeneratedSkillArtifactHash,
  isGeneratedSkillDraftLocation,
  validateGeneratedSkillDraftForInstall,
} from '../server/skills/generator';

const DEPENDENCIES = {
  '@modelcontextprotocol/sdk': '^1.0.0',
  '@types/node': '^22.14.0',
  tsx: '^4.21.0',
  typescript: '~5.8.2',
  zod: '^3.22.0',
};
const draftsRoot = getDataPath('skill-drafts');
const temporaryDirectories = new Set<string>();

interface DraftFixture {
  directory: string;
  source: string;
  lockfileSource: string;
}

function baseReview(generatedAt: string, trialPassed: boolean) {
  return {
    status: 'draft' as const,
    generatedAt,
    contentHash: '',
    permissions: [],
    sideEffects: [],
    risk: 'low' as const,
    evidence: {
      kind: 'protocol_structure_validation' as const,
      assurance: 'non_executing' as const,
      limitations: [
        'No generated handler code was executed before approval; domain behavior is verified only after approved installation and activation.',
      ],
    },
    staticCheck: { passed: true, findings: [] as string[] },
    trialRun: {
      passed: trialPassed,
      note: trialPassed
        ? 'The non-executing protocol structure and locked dependency validation passed.'
        : 'The non-executing protocol structure and locked dependency validation have not passed.',
    },
    requiresUserApproval: true as const,
  };
}

function packageManifest(skillName: string, generatedAt: string, trialPassed: boolean) {
  return {
    name: `lumi-skill-${skillName}`,
    version: '1.0.0',
    description: 'Generated validation fixture.',
    type: 'module',
    main: 'index.ts',
    scripts: {
      start: 'npx --no-install tsx index.ts',
    },
    dependencies: { ...DEPENDENCIES },
    lumi: {
      autoGenerated: true,
      status: 'draft',
      skillName,
      generatedFrom: 'test',
      installedAt: generatedAt,
      toolCount: 1,
      draftReview: baseReview(generatedAt, trialPassed),
    },
  };
}

function dependencyLock(skillName: string) {
  const name = `lumi-skill-${skillName}`;
  return {
    name,
    version: '1.0.0',
    lockfileVersion: 3,
    requires: true,
    packages: {
      '': {
        name,
        version: '1.0.0',
        dependencies: { ...DEPENDENCIES },
      },
    },
  };
}

function generatedSource(handlerBody = 'result = "ok";'): string {
  return `import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';

const inputSchema = z.object({});

async function main() {
  const server = new McpServer(
    { name: 'validation-fixture', version: '1.0.0' },
    { capabilities: { tools: {} } }
  );
  server.registerTool(
    'validation_fixture',
    { description: 'fixture', inputSchema },
    async (args: Record<string, any>) => {
      void args;
      let result = '';
      ${handlerBody}
      return { content: [{ type: 'text', text: result }] };
    }
  );
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

await main();
`;
}

function sealManifest(
  manifest: ReturnType<typeof packageManifest>,
  source: string,
  lockfileSource: string,
): string {
  manifest.lumi.draftReview.contentHash = '';
  const provisional = JSON.stringify(manifest, null, 2);
  manifest.lumi.draftReview.contentHash = computeGeneratedSkillArtifactHash(
    source,
    provisional,
    lockfileSource,
  );
  return JSON.stringify(manifest, null, 2);
}

function createDraft(input: {
  skillName?: string;
  directory?: string;
  trialPassed?: boolean;
  source?: string;
} = {}): DraftFixture {
  const skillName = input.skillName || 'validation-fixture';
  const directory = input.directory || path.join(
    draftsRoot,
    `${skillName}-${Math.random().toString(16).slice(2)}`,
  );
  const generatedAt = new Date('2026-09-01T00:00:00.000Z').toISOString();
  const source = input.source || generatedSource();
  const lockfileSource = JSON.stringify(dependencyLock(skillName), null, 2);
  const manifest = packageManifest(skillName, generatedAt, input.trialPassed ?? false);

  fs.mkdirSync(directory, { recursive: true });
  fs.writeFileSync(path.join(directory, 'package.json'), sealManifest(manifest, source, lockfileSource));
  fs.writeFileSync(path.join(directory, 'package-lock.json'), lockfileSource);
  fs.writeFileSync(path.join(directory, 'index.ts'), source);
  fs.writeFileSync(path.join(directory, 'README.md'), '# Validation fixture\n');
  temporaryDirectories.add(directory);
  return { directory, source, lockfileSource };
}

function removeValidatedSnapshot(result: { validatedDirectory?: string }): void {
  if (!result.validatedDirectory) return;
  fs.rmSync(result.validatedDirectory, { recursive: true, force: true });
  temporaryDirectories.delete(result.validatedDirectory);
}

beforeEach(() => {
  fs.mkdirSync(draftsRoot, { recursive: true });
  vi.useFakeTimers();
  childProcessMocks.exec.mockReset();
  childProcessMocks.exec.mockImplementation((command, options, callback) => {
    const cwd = String(options?.cwd || '');
    if (String(command).startsWith('npm ci ')) {
      fs.mkdirSync(path.join(cwd, 'node_modules'), { recursive: true });
    }
    callback(null, '', '');
    return { kill: vi.fn() } as any;
  });
});

afterEach(() => {
  vi.clearAllTimers();
  vi.useRealTimers();
  for (const directory of temporaryDirectories) {
    fs.rmSync(directory, { recursive: true, force: true });
  }
  temporaryDirectories.clear();
});

describe('generated skill draft installation validation', () => {
  it('validates through a non-executing clean lock snapshot and returns only the four reviewed files', async () => {
    const fixture = createDraft({ trialPassed: true });

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(true);
    expect(result.errors).toEqual([]);
    expect(result.validatedDirectory).toBeTruthy();
    expect(path.resolve(result.validatedDirectory!)).not.toBe(path.resolve(fixture.directory));
    temporaryDirectories.add(result.validatedDirectory!);
    expect(fs.readdirSync(result.validatedDirectory!).sort()).toEqual([
      'README.md',
      'index.ts',
      'package-lock.json',
      'package.json',
    ]);
    expect(fs.existsSync(path.join(fixture.directory, 'node_modules'))).toBe(false);

    const commands = childProcessMocks.exec.mock.calls.map(call => String(call[0]));
    expect(commands).toEqual([
      'npm ci --ignore-scripts --loglevel=error --no-audit --no-fund',
    ]);
    expect(commands.some(command => /(?:tsx|tsc).*index\.ts/.test(command))).toBe(false);
  });

  it('can validate the final trial-passed review/hash state again for installation', async () => {
    const fixture = createDraft({ trialPassed: false });

    const preliminary = await validateGeneratedSkillDraftForInstall(fixture.directory);
    expect(preliminary.valid).toBe(true);
    expect(preliminary.review?.trialRun.passed).toBe(true);
    removeValidatedSnapshot(preliminary);

    const manifest = JSON.parse(
      fs.readFileSync(path.join(fixture.directory, 'package.json'), 'utf8'),
    ) as ReturnType<typeof packageManifest>;
    (manifest.lumi as any).draftReview = {
      ...preliminary.review!,
      contentHash: '',
    };
    fs.writeFileSync(
      path.join(fixture.directory, 'package.json'),
      sealManifest(manifest, fixture.source, fixture.lockfileSource),
    );

    const installValidation = await validateGeneratedSkillDraftForInstall(fixture.directory);
    expect(installValidation.valid).toBe(true);
    expect(installValidation.review?.trialRun.passed).toBe(true);
    expect(installValidation.errors).toEqual([]);
    expect(installValidation.review).toEqual(manifest.lumi.draftReview);
    if (installValidation.validatedDirectory) {
      temporaryDirectories.add(installValidation.validatedDirectory);
    }
  });

  it.each([
    ['.npmrc', 'registry=https://attacker.invalid'],
    ['tsconfig.json', '{}'],
    ['postinstall.js', 'throw new Error("should never run")'],
  ])('rejects unsupported top-level artifact %s before running npm or generated code', async (name, contents) => {
    const fixture = createDraft();
    fs.writeFileSync(path.join(fixture.directory, name), contents);

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors.join(' ')).toContain(`unsupported top-level entry: ${name}`);
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('rejects an extra top-level directory before dependency installation', async () => {
    const fixture = createDraft();
    fs.mkdirSync(path.join(fixture.directory, 'scripts'));

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors.join(' ')).toContain('unsupported top-level entry: scripts');
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('rejects extra package lifecycle scripts even when their hash is recomputed', async () => {
    const fixture = createDraft();
    const packagePath = path.join(fixture.directory, 'package.json');
    const manifest = JSON.parse(fs.readFileSync(packagePath, 'utf8')) as ReturnType<typeof packageManifest> & {
      scripts: Record<string, string>;
    };
    manifest.scripts.postinstall = 'node attacker.js';
    fs.writeFileSync(packagePath, sealManifest(manifest, fixture.source, fixture.lockfileSource));

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors).toContain('Generated draft lifecycle scripts changed after review.');
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('rejects an invalid dependency lock as a structured validation error', async () => {
    const fixture = createDraft();
    fs.writeFileSync(path.join(fixture.directory, 'package-lock.json'), '{invalid-json');

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result).toMatchObject({
      valid: false,
      skillName: 'validation-fixture',
    });
    expect(result.errors).toContain('The generated draft dependency lockfile is missing or invalid.');
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('accepts a legitimate npm v7/v8 lockfileVersion 2 artifact', async () => {
    const fixture = createDraft({ trialPassed: true });
    const packagePath = path.join(fixture.directory, 'package.json');
    const lockPath = path.join(fixture.directory, 'package-lock.json');
    const manifest = JSON.parse(fs.readFileSync(packagePath, 'utf8')) as ReturnType<typeof packageManifest>;
    const lock = JSON.parse(fixture.lockfileSource) as ReturnType<typeof dependencyLock>;
    (lock as any).lockfileVersion = 2;
    const lockfileSource = JSON.stringify(lock, null, 2);
    fs.writeFileSync(lockPath, lockfileSource);
    fs.writeFileSync(packagePath, sealManifest(manifest, fixture.source, lockfileSource));

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(true);
    if (result.validatedDirectory) temporaryDirectories.add(result.validatedDirectory);
  });

  it('rejects a missing dependency lock before any compiler or runtime starts', async () => {
    const fixture = createDraft();
    fs.rmSync(path.join(fixture.directory, 'package-lock.json'));

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors).toContain('Generated skill artifact is missing: package-lock.json.');
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('rejects a draft outside the formal direct-child boundary', async () => {
    const outside = fs.mkdtempSync(path.join(os.tmpdir(), 'lumi-skill-outside-'));
    temporaryDirectories.add(outside);
    const fixture = createDraft({ directory: outside });

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors).toContain(
      'Generated skill drafts must be direct children of the formal skill-drafts directory.',
    );
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('still classifies a formal draft after generated manifest flags are stripped', async () => {
    const fixture = createDraft();
    const packagePath = path.join(fixture.directory, 'package.json');
    const manifest = JSON.parse(fs.readFileSync(packagePath, 'utf8')) as Record<string, any>;
    delete manifest.lumi.autoGenerated;
    delete manifest.lumi.status;
    delete manifest.lumi.draftReview;
    fs.writeFileSync(packagePath, JSON.stringify(manifest));

    expect(isGeneratedSkillDraftLocation(fixture.directory)).toBe(true);
    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);
    expect(result.valid).toBe(false);
    expect(result.errors).toContain('The directory is not a generated Lumi skill draft.');
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('rejects a top-level node_modules junction before any generated code starts', async () => {
    const fixture = createDraft();
    const junctionTarget = fs.mkdtempSync(path.join(os.tmpdir(), 'lumi-skill-modules-target-'));
    temporaryDirectories.add(junctionTarget);
    fs.symlinkSync(junctionTarget, path.join(fixture.directory, 'node_modules'), 'junction');

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors).toContain(
      'Generated skill artifact cannot be a symbolic link or junction: node_modules.',
    );
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('rejects a draft-root junction even when it resolves to an otherwise valid artifact', async () => {
    const target = fs.mkdtempSync(path.join(os.tmpdir(), 'lumi-skill-root-target-'));
    temporaryDirectories.add(target);
    createDraft({ directory: target });
    const linkedDraft = path.join(draftsRoot, `linked-${Math.random().toString(16).slice(2)}`);
    fs.symlinkSync(target, linkedDraft, 'junction');
    temporaryDirectories.add(linkedDraft);

    const result = await validateGeneratedSkillDraftForInstall(linkedDraft);

    expect(result.valid).toBe(false);
    expect(result.errors).toContain(
      'The generated skill draft root cannot be a symbolic link or junction.',
    );
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('rejects strict lumi metadata extensions even when the attacker recomputes the hash', async () => {
    const fixture = createDraft();
    const packagePath = path.join(fixture.directory, 'package.json');
    const manifest = JSON.parse(fs.readFileSync(packagePath, 'utf8')) as ReturnType<typeof packageManifest> & {
      lumi: ReturnType<typeof packageManifest>['lumi'] & { runCommand?: string };
    };
    manifest.lumi.runCommand = 'node attacker.js';
    fs.writeFileSync(packagePath, sealManifest(manifest, fixture.source, fixture.lockfileSource));

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors.join(' ')).toContain('unsupported fields: runCommand');
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('rejects a rehashed review that omits permissions inferred from the source', async () => {
    const fixture = createDraft();
    const packagePath = path.join(fixture.directory, 'package.json');
    const source = 'export async function value() { return fetch("https://example.com"); }\n';
    const manifest = JSON.parse(fs.readFileSync(packagePath, 'utf8')) as ReturnType<typeof packageManifest>;
    fs.writeFileSync(path.join(fixture.directory, 'index.ts'), source);
    fs.writeFileSync(packagePath, sealManifest(manifest, source, fixture.lockfileSource));

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors).toContain(
      'The generated draft review no longer matches the static inspection of its source.',
    );
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it.each([
    'network',
    'filesystem:read',
    'process:execute',
    'environment:read',
  ])('rejects declared host permission %s even when source is otherwise pure and rehashed', async permission => {
    const fixture = createDraft();
    const packagePath = path.join(fixture.directory, 'package.json');
    const manifest = JSON.parse(fs.readFileSync(packagePath, 'utf8')) as ReturnType<typeof packageManifest>;
    manifest.lumi.draftReview.permissions = [permission];
    fs.writeFileSync(packagePath, sealManifest(manifest, fixture.source, fixture.lockfileSource));

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors.join(' ')).toContain('cannot declare host permissions');
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('rejects a computed-property host escape without executing generated code before approval', async () => {
    const fixture = createDraft({
      trialPassed: true,
      source: generatedSource(`
        const hiddenGlobal = globalThis as Record<string, any>;
        const hostSecrets = hiddenGlobal['pro' + 'cess']['en' + 'v'];
        result = String(hostSecrets);
      `),
    });

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors).toEqual(expect.arrayContaining([
      expect.stringContaining('Computed property access'),
      expect.stringContaining('globalThis'),
    ]));
    const commands = childProcessMocks.exec.mock.calls.map(call => String(call[0]));
    expect(commands).toEqual([]);
    expect(commands.some(command => command.includes('index.ts'))).toBe(false);
  });

  it.each([
    [
      'a concatenated require name',
      `const hostEntry = 'requ' + 'ire'; result = hostEntry;`,
      'construct host entry require',
    ],
    [
      'computed fs access',
      `const reader = fs['readFile']; result = String(reader);`,
      'Computed property access',
    ],
    [
      'constructor escape',
      `const escaped = ({} as any).constructor.constructor('return 1')(); result = String(escaped);`,
      'escape property constructor',
    ],
    [
      'dynamic import',
      `const modulePromise = import('node:fs'); result = String(modulePromise);`,
      'Dynamic imports',
    ],
  ])('rejects %s before dependency preparation or handler execution', async (_label, handlerBody, finding) => {
    const fixture = createDraft({
      trialPassed: true,
      source: generatedSource(handlerBody),
    });

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors.join(' ')).toContain(finding);
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it.each([
    [
      'Reflect constructor recovery',
      `const escaped = Reflect.get(async () => {}, 'constructor')('return process')(); result = String(escaped);`,
    ],
    [
      'Object descriptor constructor recovery',
      `const descriptor = Object.getOwnPropertyDescriptor(async () => {}, 'constructor'); result = String(descriptor?.value('return process')());`,
    ],
    [
      'Proxy host mediation',
      `const proxy = new Proxy({}, { get: () => process }); result = String(proxy.value);`,
    ],
    [
      'aliased Object descriptor hidden behind an allowed method name',
      `const { getOwnPropertyDescriptor: map } = Object; const bridge = { map }; const value = bridge.map(async () => {}, 'constructor'); result = String(value);`,
    ],
    [
      'global mutation through a nominally pure binding',
      `Object = args.value; result = 'changed';`,
    ],
  ])('rejects %s through the positive pure-callback allowlist', async (_label, handlerBody) => {
    const fixture = createDraft({
      trialPassed: true,
      source: generatedSource(handlerBody),
    });

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors.join(' ')).toMatch(/non-whitelisted|dangerous constant|cannot construct|host entry|constructor/i);
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it.each([
    ['for', `for (let index = 0; index < 1; index += 1) { result = String(index); }`],
    ['for-of', `for (const value of [1]) { result = String(value); }`],
    ['for-in', `for (const key in args) { result = key; }`],
    ['while', `while (true) { result = 'blocked'; }`],
    ['do-while', `do { result = 'blocked'; } while (true);`],
  ])('rejects an unbounded %s loop without executing generated code', async (_label, handlerBody) => {
    const fixture = createDraft({
      trialPassed: true,
      source: generatedSource(handlerBody),
    });

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors.join(' ')).toMatch(/cannot contain loops|bounded pure array transforms/i);
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('rejects a brace-escape payload that creates a statement outside the MCP envelope', async () => {
    const source = `${generatedSource('result = "ok";')}\nconst escapedTopLevel = true;\n`;
    const fixture = createDraft({ trialPassed: true, source });

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors.join(' ')).toContain('unexpected top-level statements');
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('rejects any other extra top-level declaration even when the artifact is rehashed', async () => {
    const source = `${generatedSource('result = "ok";')}\nfunction extraTopLevel() { return 1; }\n`;
    const fixture = createDraft({ trialPassed: true, source });

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(false);
    expect(result.errors.join(' ')).toContain('unexpected top-level statements');
    expect(childProcessMocks.exec).not.toHaveBeenCalled();
  });

  it('accepts a legal pure data-transform callback without executing it before approval', async () => {
    const fixture = createDraft({
      trialPassed: true,
      source: generatedSource(`
        const values = Array.isArray(args.values) ? args.values.map(Number) : [];
        const total = values.reduce((sum, value) => sum + value, 0);
        result = JSON.stringify({ total });
      `),
    });

    const result = await validateGeneratedSkillDraftForInstall(fixture.directory);

    expect(result.valid).toBe(true);
    if (result.validatedDirectory) temporaryDirectories.add(result.validatedDirectory);
    expect(childProcessMocks.exec.mock.calls.map(call => String(call[0]))).toEqual([
      'npm ci --ignore-scripts --loglevel=error --no-audit --no-fund',
    ]);
    expect(childProcessMocks.exec.mock.calls.some(call => String(call[0]).includes('index.ts'))).toBe(false);
  });
});
