import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import {
  computeGeneratedSkillArtifactHash,
  readGeneratedSkillDraft,
} from '../server/skills/generator';

const temporaryDirectories: string[] = [];

describe('Executable skill generation policy', () => {
  afterEach(() => {
    for (const directory of temporaryDirectories.splice(0)) {
      fs.rmSync(directory, { recursive: true, force: true });
    }
  });

  it('has no automatic executable-skill generation entry point or deployment override', () => {
    const generatorSource = fs.readFileSync(
      path.join(process.cwd(), 'server', 'skills', 'generator.ts'),
      'utf8',
    );
    const schedulerSource = fs.readFileSync(
      path.join(process.cwd(), 'server', 'scheduler.ts'),
      'utf8',
    );

    expect(generatorSource).not.toContain('autoGenerateSkill');
    expect(generatorSource).not.toContain('LUMI_AUTO_GENERATE_EXECUTABLE_SKILLS');
    expect(schedulerSource).not.toContain('auto_skill_gen');
  });

  it('recognizes generated output only as a reviewed, approval-gated draft', () => {
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'lumi-skill-draft-policy-'));
    temporaryDirectories.push(directory);
    fs.writeFileSync(path.join(directory, 'package.json'), JSON.stringify({
      name: 'lumi-skill-example',
      lumi: {
        autoGenerated: true,
        status: 'draft',
        skillName: 'example',
        draftReview: {
          status: 'draft',
          generatedAt: new Date(0).toISOString(),
          contentHash: 'hash',
          permissions: [],
          sideEffects: [],
          risk: 'low',
          evidence: {
            kind: 'protocol_structure_validation',
            assurance: 'non_executing',
            limitations: [],
          },
          staticCheck: { passed: true, findings: [] },
          trialRun: { passed: true, note: 'isolated startup passed' },
          requiresUserApproval: true,
        },
      },
    }));

    expect(readGeneratedSkillDraft(directory)).toMatchObject({
      skillName: 'example',
      review: {
        status: 'draft',
        requiresUserApproval: true,
      },
    });
  });

  it('binds the review hash to executable manifest fields and the dependency lock', () => {
    const source = 'export const value = 1;';
    const review = {
      status: 'draft',
      generatedAt: new Date(0).toISOString(),
      contentHash: 'self-referential-value-is-excluded',
      permissions: ['network'],
      sideEffects: ['Connects to an external network service.'],
      risk: 'medium',
      evidence: {
        kind: 'protocol_structure_validation',
        assurance: 'non_executing',
        limitations: ['startup evidence only'],
      },
      staticCheck: { passed: true, findings: [] },
      trialRun: { passed: true, note: 'isolated startup passed' },
      requiresUserApproval: true,
    };
    const baseManifest = {
      name: 'lumi-skill-example',
      version: '1.0.0',
      type: 'module',
      main: 'index.ts',
      scripts: { start: 'npx --no-install tsx index.ts' },
      dependencies: {
        '@modelcontextprotocol/sdk': '^1.0.0',
        '@types/node': '^22.14.0',
        tsx: '^4.21.0',
        typescript: '~5.8.2',
        zod: '^3.22.0',
      },
      lumi: {
        autoGenerated: true,
        status: 'draft',
        skillName: 'example',
        draftReview: review,
      },
    };
    const baseLock = JSON.stringify({ lockfileVersion: 3, packages: {} });
    const reviewed = computeGeneratedSkillArtifactHash(
      source,
      JSON.stringify(baseManifest),
      baseLock,
    );

    expect(computeGeneratedSkillArtifactHash(
      source,
      JSON.stringify({
        ...baseManifest,
        lumi: {
          ...baseManifest.lumi,
          draftReview: { ...review, contentHash: 'updated-review' },
        },
      }),
      baseLock,
    )).toBe(reviewed);
    for (const changedReview of [
      { ...review, permissions: ['filesystem:write', 'network'] },
      { ...review, risk: 'high' },
      { ...review, trialRun: { passed: false, note: 'not run' } },
      { ...review, requiresUserApproval: false },
    ]) {
      expect(computeGeneratedSkillArtifactHash(
        source,
        JSON.stringify({
          ...baseManifest,
          lumi: { ...baseManifest.lumi, draftReview: changedReview },
        }),
        baseLock,
      )).not.toBe(reviewed);
    }
    expect(computeGeneratedSkillArtifactHash(
      source,
      JSON.stringify({
        ...baseManifest,
        scripts: { start: 'node alternate.js' },
      }),
      baseLock,
    )).not.toBe(reviewed);
    expect(computeGeneratedSkillArtifactHash(
      source,
      JSON.stringify({
        ...baseManifest,
        lumi: { ...baseManifest.lumi, runCommand: 'node' },
      }),
      baseLock,
    )).not.toBe(reviewed);
    expect(computeGeneratedSkillArtifactHash(
      source,
      JSON.stringify({
        ...baseManifest,
        dependencies: { zod: '99.0.0' },
      }),
      baseLock,
    )).not.toBe(reviewed);
    expect(computeGeneratedSkillArtifactHash(
      source,
      JSON.stringify(baseManifest),
      JSON.stringify({ lockfileVersion: 3, packages: { changed: {} } }),
    )).not.toBe(reviewed);
  });
});
