import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { readGeneratedSkillDraft } from '../server/skills/generator';

const temporaryDirectories: string[] = [];

describe('Executable skill generation policy', () => {
  afterEach(() => {
    for (const directory of temporaryDirectories.splice(0)) {
      fs.rmSync(directory, { recursive: true, force: true });
    }
  });

  it('has no automatic executable-skill generation entry point or deployment override', () => {
    const generatorSource = fs.readFileSync(
      path.join(process.cwd(), 'server', 'skills', 'generator.ts'),
      'utf8',
    );
    const schedulerSource = fs.readFileSync(
      path.join(process.cwd(), 'server', 'scheduler.ts'),
      'utf8',
    );

    expect(generatorSource).not.toContain('autoGenerateSkill');
    expect(generatorSource).not.toContain('LUMI_AUTO_GENERATE_EXECUTABLE_SKILLS');
    expect(schedulerSource).not.toContain('auto_skill_gen');
  });

  it('recognizes generated output only as a reviewed, approval-gated draft', () => {
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'lumi-skill-draft-policy-'));
    temporaryDirectories.push(directory);
    fs.writeFileSync(path.join(directory, 'package.json'), JSON.stringify({
      name: 'lumi-skill-example',
      lumi: {
        autoGenerated: true,
        status: 'draft',
        skillName: 'example',
        draftReview: {
          status: 'draft',
          generatedAt: new Date(0).toISOString(),
          contentHash: 'hash',
          permissions: [],
          sideEffects: [],
          risk: 'low',
          evidence: {
            kind: 'mcp_tool_receipt',
            assurance: 'declared',
            limitations: [],
          },
          staticCheck: { passed: true, findings: [] },
          trialRun: { passed: true, note: 'isolated startup passed' },
          requiresUserApproval: true,
        },
      },
    }));

    expect(readGeneratedSkillDraft(directory)).toMatchObject({
      skillName: 'example',
      review: {
        status: 'draft',
        requiresUserApproval: true,
      },
    });
  });
});
