import fs from 'fs';
import path from 'path';
import { describe, expect, it } from 'vitest';
import {
  LUMI_TECHNICAL_ARCHITECTURE,
  getLumiTechnicalArchitecture,
} from '../shared/technical_architecture';
import { getClientSelfAwarenessReport } from '../server/client/self_model';

describe('technical architecture manifest', () => {
  it('is the stable cross-platform product topology', () => {
    const manifest = getLumiTechnicalArchitecture();
    const ids = manifest.components.map(component => component.id);
    const technologies = manifest.components.flatMap(component => component.technologies);

    expect(manifest).toBe(LUMI_TECHNICAL_ARCHITECTURE);
    expect(new Set(ids).size).toBe(ids.length);
    expect(manifest.topology).toBe('local-first-desktop-agent');
    expect(technologies).toEqual(expect.arrayContaining([
      'React 19',
      'Tauri 2',
      'Rust',
      'Node.js',
      'Express',
      'Socket.IO',
      'SQLite',
      'CapabilityManifest',
      'Windows UI Automation',
      'macOS Accessibility',
    ]));
    const native = manifest.components.find(component => component.id === 'native.automation');
    expect(native?.platforms).toEqual(expect.arrayContaining(['windows', 'macos']));
    expect(manifest.invariants).toEqual(expect.arrayContaining([
      expect.stringContaining('same capability IDs'),
      expect.stringContaining('TaskLedger'),
    ]));
  });

  it('is exposed through client self-awareness even without live client state', () => {
    const report = getClientSelfAwarenessReport(`architecture-test-${Date.now()}`);
    expect(report.architecture).toBe(LUMI_TECHNICAL_ARCHITECTURE);
    expect(report.architecture.components.length).toBeGreaterThanOrEqual(8);
  });

  it('keeps contributor docs and README counts generated from source', () => {
    const root = process.cwd();
    const context = fs.readFileSync(path.join(root, '.project-context.md'), 'utf8');
    const readme = fs.readFileSync(path.join(root, 'README.md'), 'utf8');
    const stats = fs.readFileSync(path.join(root, 'docs', 'generated', 'capability-stats.md'), 'utf8');

    expect(context).toContain('shared/technical_architecture.ts');
    expect(context).not.toContain('React 11');
    expect(readme).toContain('docs/generated/capability-stats.md');
    expect(readme).not.toMatch(/37\s*个\s*MCP|37\s*技能\s*\+\s*26|30\+\s*内置技能/);
    expect(stats).toContain('Generated by `npm run docs:capability-stats`');
  });
});
