export { queryMemories, queryMemoriesVector, backfillEmbeddings, addMemory, removeMemory, updateMemoryLifecycle, resolveMemoryConflict, decayMemories, dynamicDecayMemories, computeMemoryValue, promoteMemories, formatMemoriesForContext, classifyMemoryEvidence, addReminder, upsertPendingReminder, getDueReminders, fireReminder, getUnconsolidatedEpisodic, markConsolidated, decayMemoryAssociations, initMemoryAssociations, getAssociatedMemories } from './store';
export { CONVERSATIONAL_MEMORY_EVIDENCE } from './types';
export type { Reminder } from './store';
export { extractMemories } from './extractor';
export type { ExtractedMemory, MemoryTier, MemoryPerspective } from './types';
export type { ExtractedReminder } from './extractor';
export { analyzeBehavioralPatterns, runBehavioralAnalysis } from './behavioral';
export type { BehavioralPattern } from './behavioral';
export { initMemorySync, registerUserSocket, unregisterUserSocket, broadcastMemoryChange, broadcastDeviceChange, broadcastPreferenceChange } from './sync';
export { buildNarrativeChain } from './narrative';
export type { NarrativeChainResult } from './narrative';
export { evaluateMemoryFirewall, getMemoryFirewallPolicy } from './firewall';
export type { MemoryFirewallDecision, MemoryFirewallPolicy } from './firewall';
export { runDreamCycle, getSleepCycleState } from './dream';
export type { DreamCycleReport, DreamCycleOptions, SleepCycleState } from './dream';
