import { readDB, writeDB } from '../../db_layer';
import type { Memory } from './types';
import { isUnverifiedCapabilityBoundary, sanitizeSummaryForPrompt } from '../conversation/summary_grounding';

export function isTestLearningSource(source?: string): boolean {
  return /^(?:(?:local_)?acceptance(?:_harness)?|e2e|probe|smoke|test)(?:[-_:]|$)/i.test(String(source || '').trim());
}

/** Only explicit test identifiers are inferred for legacy records without provenance. */
export function isTestMemory(memory: Pick<Memory, 'sourceInteractionId' | 'content'>): boolean {
  return isTestLearningSource(memory.sourceInteractionId)
    || /\bLC-(?:TASK|SKILL|WORKFLOW|LIVE|UI)-|this is isolated read-only verification/i.test(memory.content);
}

/** Activity generated by the application is not an observation of its owner. */
export function isOwnerInteractionEvidence(row: {
  source?: string; mode?: string; role?: string; agentId?: string;
  content?: string; message?: string;
}): boolean {
  return !isTestLearningSource(row.source)
    && !['proactive', 'system', 'growth_journal', 'skill_gen'].includes(row.mode || '')
    && !['system', 'tool'].includes(row.role || '')
    && !row.agentId?.startsWith('memory_avatar_')
    && !isTestMemory({ sourceInteractionId: row.source || '', content: row.content || row.message || '' });
}

/** Generated reflections may be displayed, but never fed back as new evidence. */
export function isDerivedLearningMemory(memory: Pick<Memory, 'sourceInteractionId' | 'content'>): boolean {
  return /^(?:growth_journal|narrative_consolidation|predictive_lumi|proactive_lumi|proactive_scan)/i.test(memory.sourceInteractionId || '')
    || /^\[(?:Growth Journal|Predictive|Proactive Scan)\b/i.test(memory.content || '');
}

export function isMalformedBehavioralMemory(memory: Pick<Memory, 'sourceInteractionId' | 'content'>): boolean {
  if (!/^behavioral_/.test(memory.sourceInteractionId || '') || !memory.content.startsWith('Most used tools: ')) return false;
  return memory.content.slice('Most used tools: '.length).split(', ').some(item => !/^[a-z][a-z0-9_-]{1,127}\(\d+x\)$/i.test(item));
}

export function isOwnerEvolutionEvidence(memory: Memory): boolean {
  return memory.nodeType !== 'branch' && memory.perspective === 'owner_trait'
    && !isTestMemory(memory) && !isMalformedBehavioralMemory(memory) && !isDerivedLearningMemory(memory)
    && !memory.sourceInteractionId?.startsWith('quarantine:') && ['chat', 'voice', 'manual'].includes(memory.source || '')
    && !memory.agentId?.startsWith('memory_avatar_');
}

/** Archive the exact old values before isolating confirmed corrupt evidence. */
export function repairRuntimeLearningEvidence(): number {
  const db = readDB();
  const marker = 'learning_evidence_repair_v2';
  if (db.settings?.some(row => row.key === marker)) return 0;
  const memories: any[] = [];
  for (const memory of db.memories || []) {
    if (!isMalformedBehavioralMemory(memory) && !isTestMemory(memory)) continue;
    if (memory.sourceInteractionId?.startsWith('quarantine:')) continue;
    memories.push({ id: memory.id, sourceInteractionId: memory.sourceInteractionId, perspective: memory.perspective, retention: memory.retention });
    memory.sourceInteractionId = `quarantine:learning:${memory.sourceInteractionId}`;
    memory.perspective = 'shared_memory';
    memory.retention = 'session';
  }
  const summaries: any[] = [];
  for (const conversation of db.conversations || []) {
    const chain = Array.isArray(conversation.summaryChain) ? conversation.summaryChain : [];
    if (![conversation.summary || '', ...chain].some(isUnverifiedCapabilityBoundary)) continue;
    summaries.push({ id: conversation.id, summary: conversation.summary, summaryChain: chain,
      lastSummaryMessageCount: conversation.lastSummaryMessageCount });
    conversation.summary = sanitizeSummaryForPrompt(conversation.summary);
    conversation.summaryChain = chain.map(sanitizeSummaryForPrompt).filter(Boolean);
    conversation.lastSummaryMessageCount = 0;
  }
  db.settings ||= [];
  db.settings.push({ key: marker, value: JSON.stringify({ at: new Date().toISOString(), memories, summaries }) });
  writeDB(db);
  return memories.length + summaries.length;
}

/** Preserve original records; remove confirmed test material from ordinary learning. */
export function repairTestMemoryProvenance(): number {
  const db = readDB();
  const marker = 'memory_test_provenance_repair_v1';
  if (db.settings?.some(row => row.key === marker)) return 0;
  const interactions = new Map<string, any>((db.interactions || []).map(row => [row.id, row]));
  const changes: any[] = [];
  for (const memory of db.memories || []) {
    const origin = interactions.get(memory.sourceInteractionId);
    if (!isTestMemory(memory) && !isTestLearningSource(origin?.source)) continue;
    changes.push({ id: memory.id, sourceInteractionId: memory.sourceInteractionId, perspective: memory.perspective, retention: memory.retention });
    memory.sourceInteractionId = `test:legacy:${memory.sourceInteractionId}`;
    memory.perspective = 'shared_memory';
    memory.retention = 'session';
  }
  // Repair only profiles with an unambiguous test phrase, retaining the exact
  // previous state for recovery. Do not guess that ordinary technical interests are tests.
  const profiles: any[] = [];
  for (const row of db.settings || []) {
    if (!row.key.startsWith('personality_user_state:')) continue;
    try {
      const state = JSON.parse(row.value);
      if (!/this is isolated read-only verification|LC-(?:TASK|SKILL|WORKFLOW)-/i.test(JSON.stringify(state.growthState || {}))) continue;
      profiles.push({ key: row.key, value: row.value });
      delete state.growthState;
      state.lastEvolvedAt = null;
      row.value = JSON.stringify(state);
    } catch { /* Invalid unrelated state is left untouched. */ }
  }
  db.settings ||= [];
  db.settings.push({ key: marker, value: JSON.stringify({ at: new Date().toISOString(), memories: changes, profiles }) });
  writeDB(db);
  return changes.length;
}
