import { Router, type NextFunction, type Request, type Response } from "express";
import { requireAdmin, requireAuth, requireLocalRequest } from "../middleware/auth";
import { DESKTOP_SESSION_HEADER, verifyDesktopSessionProof } from "../config/desktop_bootstrap";
import {
  mcpManager,
  getMCPConfig,
  updateMCPConfig,
  recoverServerTools,
  getRegisteredMCPToolNames,
  requireSafeMCPServerName,
  unregisterServerTools,
  type MCPConfigUpdateResult,
} from "../mcp";
import { logger } from "../../logger";
import {
  normalizeRemoteDeviceConfig,
  projectMcpServerHealth,
  projectRemoteDeviceConfig,
  sanitizeMcpEndpoint,
  sanitizeMcpLogValue,
} from "../mcp/public_security";

function redactMcpArgumentList(value: unknown): string[] {
  const args = Array.isArray(value) ? value.map(item => String(item || '')) : [];
  const secretFlag = /^(?:--?(?:api[-_]?key|token|secret|password|authorization)|bearer)$/i;
  return args.map((arg, index) => {
    if (index > 0 && secretFlag.test(args[index - 1])) return '[configured]';
    if (/^(?:bearer\s+|sk-)[a-z0-9._~+/=-]{8,}$/i.test(arg)) return '[configured]';
    if (/^(?:--?(?:api[-_]?key|token|secret|password|authorization))=.+$/i.test(arg)) {
      return `${arg.split('=', 1)[0]}=[configured]`;
    }
    return arg;
  });
}

function publicMcpConfig(name: string, cfg: any, connected: boolean) {
  const registeredToolNames = getRegisteredMCPToolNames(name);
  const registered = registeredToolNames.length > 0;
  const usable = cfg?.enabled === true && registered;
  return {
    name,
    enabled: cfg?.enabled === true,
    ...(cfg?.source === 'local' || cfg?.source === 'external' ? { source: cfg.source } : {}),
    ...(['stdio', 'http', 'ws'].includes(cfg?.transport) ? { transport: cfg.transport } : {}),
    ...(typeof cfg?.command === 'string' ? { command: cfg.command } : {}),
    args: redactMcpArgumentList(cfg?.args),
    ...(cfg?.url ? { url: sanitizeMcpEndpoint(cfg.url) } : {}),
    ...(typeof cfg?.autoGenerated === 'boolean' ? { autoGenerated: cfg.autoGenerated } : {}),
    ...(typeof cfg?.description === 'string' ? { description: cfg.description } : {}),
    ...(typeof cfg?.requiresApiKey === 'boolean' ? { requiresApiKey: cfg.requiresApiKey } : {}),
    ...(typeof cfg?.apiKeyEnv === 'string' ? { apiKeyEnv: cfg.apiKeyEnv } : {}),
    ...(cfg?.apiKeyUrl ? { apiKeyUrl: sanitizeMcpEndpoint(cfg.apiKeyUrl) } : {}),
    ...(['pending', 'active', 'disabled'].includes(cfg?.installationState)
      ? { installationState: cfg.installationState }
      : {}),
    envConfigured: Boolean(cfg?.env && Object.keys(cfg.env).length),
    headersConfigured: Boolean(cfg?.headers && Object.keys(cfg.headers).length),
    connected,
    registered,
    usable,
    toolCount: registeredToolNames.length,
    registeredToolNames,
    runtimeStatus: usable
      ? 'callable'
      : cfg?.enabled !== true
        ? 'disabled'
        : connected
          ? 'connected_unregistered'
          : 'disconnected',
  };
}

function reportMcpRouteFailure(operation: string, error: unknown): void {
  logger.error(`[MCP Routes] ${operation} failed: ${sanitizeMcpLogValue((error as any)?.message || error)}`);
}

function publicConfigUpdateResult(result: MCPConfigUpdateResult) {
  return {
    ...result,
    services: result.services.map(service => ({
      ...service,
      ...(service.error ? { error: sanitizeMcpLogValue(service.error) } : {}),
      ...(service.rollbackError ? { rollbackError: sanitizeMcpLogValue(service.rollbackError) } : {}),
    })),
  };
}

function requireNativeDesktopSession(req: Request, res: Response, next: NextFunction): void {
  if (!req.user || !verifyDesktopSessionProof(req.headers[DESKTOP_SESSION_HEADER], req.user.uid)) {
    res.status(403).json({
      error: 'A valid native desktop session proof is required for MCP runtime changes.',
    });
    return;
  }
  next();
}

export function mountMcpRoutes(router: Router) {
  router.get("/mcp", requireAuth, requireAdmin, requireLocalRequest, (_req, res) => {
    const config = getMCPConfig();
    const connected = mcpManager.getConnectedServers();
    const servers = Object.entries(config).map(([name, cfg]) => (
      publicMcpConfig(name, cfg, connected.includes(name))
    ));
    res.json({ servers });
  });

  router.post("/mcp", requireAuth, requireAdmin, requireLocalRequest, requireNativeDesktopSession, async (req, res) => {
    try {
      const { servers, mode = 'merge' } = req.body || {};
      if (!servers || typeof servers !== 'object' || Array.isArray(servers)) {
        return res.status(400).json({ error: 'Invalid servers config' });
      }
      if (mode !== 'merge' && mode !== 'replace') {
        return res.status(400).json({ error: 'mode must be merge or replace' });
      }
      const result = await updateMCPConfig(servers, { mode });
      res.status(result.ok ? 200 : 409).json(publicConfigUpdateResult(result));
    } catch (err: any) {
      reportMcpRouteFailure('configuration update', err);
      res.status(400).json({ error: 'MCP configuration update failed' });
    }
  });

  router.put("/mcp/:name", requireAuth, requireAdmin, requireLocalRequest, requireNativeDesktopSession, async (req, res) => {
    try {
      const name = requireSafeMCPServerName(req.params.name);
      const result = await updateMCPConfig({ [name]: req.body?.config }, { mode: 'merge' });
      res.status(result.ok ? 200 : 409).json(publicConfigUpdateResult(result));
    } catch (err: any) {
      reportMcpRouteFailure('server configuration replacement', err);
      res.status(400).json({ error: 'MCP server configuration is invalid' });
    }
  });

  router.delete("/mcp/:name", requireAuth, requireAdmin, requireLocalRequest, requireNativeDesktopSession, async (req, res) => {
    try {
      const name = requireSafeMCPServerName(req.params.name);
      const result = await updateMCPConfig({}, { mode: 'merge', removeNames: [name] });
      res.status(result.ok ? 200 : 409).json(publicConfigUpdateResult(result));
    } catch (err: any) {
      reportMcpRouteFailure('server configuration deletion', err);
      res.status(400).json({ error: 'MCP server deletion failed' });
    }
  });

  router.post("/mcp/:name/state", requireAuth, requireAdmin, requireLocalRequest, requireNativeDesktopSession, async (req, res) => {
    try {
      const name = requireSafeMCPServerName(req.params.name);
      if (typeof req.body?.enabled !== 'boolean') {
        return res.status(400).json({ error: 'enabled must be boolean' });
      }
      const current = getMCPConfig()[name];
      if (!current) return res.status(404).json({ error: 'MCP server not found' });
      const result = await updateMCPConfig({
        [name]: { ...current, enabled: req.body.enabled },
      }, {
        mode: 'merge',
        forceRestartNames: req.body.enabled ? [name] : [],
      });
      res.status(result.ok ? 200 : 409).json(publicConfigUpdateResult(result));
    } catch (err: any) {
      reportMcpRouteFailure('server state update', err);
      res.status(400).json({ error: 'MCP server state update failed' });
    }
  });

  router.get("/mcp/health", requireAuth, requireAdmin, requireLocalRequest, (_req, res) => {
    res.json({ servers: projectMcpServerHealth(mcpManager.getServerHealth()) });
  });

  router.post("/mcp/restart/:name", requireAuth, requireAdmin, requireLocalRequest, requireNativeDesktopSession, async (req, res) => {
    let name = '';
    try {
      name = requireSafeMCPServerName(req.params.name);
      unregisterServerTools(name);
      const tools = await mcpManager.restartServer(name);
      if (!Array.isArray(tools) || tools.length === 0) {
        throw new Error(`MCP server "${name}" exposed no tools.`);
      }
      const registered = await recoverServerTools(name, tools);
      res.json({ tools, registered });
    } catch (err: any) {
      if (name) unregisterServerTools(name);
      reportMcpRouteFailure('server restart', err);
      res.status(500).json({ error: 'MCP server restart failed' });
    }
  });

  router.get("/remote-devices", requireAuth, requireAdmin, requireLocalRequest, (_req, res) => {
    try {
      res.json({ devices: projectRemoteDeviceConfig(mcpManager.getRemoteDevices()) });
    } catch (err: any) {
      reportMcpRouteFailure('remote device read', err);
      res.status(500).json({ error: 'Remote device configuration could not be loaded' });
    }
  });

  router.put("/remote-devices", requireAuth, requireAdmin, requireLocalRequest, requireNativeDesktopSession, (req, res) => {
    try {
      const { devices } = req.body;
      const normalized = normalizeRemoteDeviceConfig(devices);
      if (!normalized) {
        return res.status(400).json({ error: 'Invalid devices config' });
      }
      mcpManager.saveRemoteDevices(normalized);
      res.json({ success: true, devices: projectRemoteDeviceConfig(normalized) });
    } catch (err: any) {
      reportMcpRouteFailure('remote device update', err);
      res.status(500).json({ error: 'Remote device configuration could not be saved' });
    }
  });

  router.get("/mcp/github/search", requireAuth, async (req, res) => {
    try {
      const q = (req.query.q as string) || 'MCP server';
      const response = await fetch(
        `https://api.github.com/search/repositories?q=${encodeURIComponent(q)}+topic:mcp&sort=stars&order=desc&per_page=20`,
        {
          headers: {
            'Accept': 'application/vnd.github.v3+json',
            'User-Agent': 'LumiCore-MCP-Browser',
            ...(process.env.GITHUB_TOKEN ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` } : {}),
          },
        }
      );
      if (!response.ok) {
        return res.status(response.status).json({ error: `GitHub API error: ${response.statusText}` });
      }
      const data = await response.json();
      const results = (data.items || []).map((item: any) => ({
        id: item.id,
        name: item.full_name,
        description: item.description,
        stars: item.stargazers_count,
        url: item.html_url,
        topics: item.topics || [],
        language: item.language,
        updatedAt: item.updated_at,
      }));
      res.json({ results, total: data.total_count || 0 });
    } catch (err: any) {
      reportMcpRouteFailure('GitHub search', err);
      res.status(500).json({ error: 'GitHub MCP search failed' });
    }
  });

  router.get("/mcp/npm/search", requireAuth, async (req, res) => {
    try {
      const q = (req.query.q as string) || 'mcp';
      const response = await fetch(
        `https://registry.npmjs.org/-/v1/search?text=${encodeURIComponent(q)}+keywords:mcp&size=20`,
        {
          headers: {
            'Accept': 'application/json',
            'User-Agent': 'LumiCore-MCP-Browser',
          },
        }
      );
      if (!response.ok) {
        return res.status(response.status).json({ error: `npm API error: ${response.statusText}` });
      }
      const data = await response.json();
      const results = (data.objects || []).map((obj: any) => {
        const pkg = obj.package || {};
        return {
          id: pkg.name,
          name: pkg.name,
          description: pkg.description || '',
          stars: 0,
          url: pkg.links?.npm || `https://www.npmjs.com/package/${pkg.name}`,
          topics: pkg.keywords || [],
          language: 'npm',
          updatedAt: pkg.date || '',
        };
      });
      res.json({ results, total: data.total || 0 });
    } catch (err: any) {
      reportMcpRouteFailure('npm search', err);
      res.status(500).json({ error: 'npm MCP search failed' });
    }
  });
}
