import { Router, Request, Response, NextFunction } from "express";
import path from "path";
import { readDB, writeDB } from "../../db_layer";
import { mcpManager, getMCPConfig, updateMCPConfig, normalizeSkillInstallName } from "../mcp";
import {
  generateSkill,
  readGeneratedSkillDraft,
  validateGeneratedSkillDraftForInstall,
} from "../skills/generator";
import { getRecentWorkflows } from "../skills/worklog";
import { loadKeys } from "../config/keys";
import { requireAdmin, requireAuth, requireLocalRequest, resolveDomain } from "../middleware/auth";
import { createAgentForSkill } from "../agents/skill_agent";
import { isLoopbackAddress } from "../config/local_identity";

const asyncHandler = (fn: (req: Request, res: Response, next?: NextFunction) => Promise<any>) =>
  (req: Request, res: Response, next: NextFunction) =>
    Promise.resolve(fn(req, res, next)).catch(next);

function getStartupFailureNote(description: string | undefined): string | undefined {
  const match = String(description || '').match(/\(disabled after startup failure:\s*([^)]+)\)\s*$/i);
  return match?.[1]?.trim();
}

function stripStartupFailureNote(description: string | undefined, fallback: string): string {
  return String(description || fallback).replace(/\s*\(disabled after startup failure:[^)]+\)\s*$/i, '').trim();
}

export function mountSkillRoutes(
  router: Router,
  jwtSecret: string,
  llmGetters: {
    getDeepSeek: () => any;
    getGemini: () => any;
    getOpenAI?: () => any;
    getAnthropic?: () => any;
    getQwen?: () => any;
    getOllama?: () => any;
    getLmStudio?: () => any;
    getArk?: () => any;
    getXiaomi?: () => any;
    getKimi?: () => any;
    getGlm?: () => any;
    getRelay?: () => any;
  },
  io: { emit: (event: string, data: any) => void },
) {
  const skillAgentScope = (req: Request) => {
    const user = req.user!;
    const dc = resolveDomain(user);
    return {
      ownerUid: user.uid,
      userId: user.uid,
      domain: dc.domain,
      orgId: dc.orgId,
    };
  };

  const removeAutoAgentForSkill = (name: string) => {
    const agentId = `skill_${name.toLowerCase().replace(/[^a-z0-9]/g, '-')}`;
    try {
      const db = readDB();
      if (db.agents) {
        const removed = db.agents.filter((a: any) => a.autoCreated && (a.id === agentId || String(a.id || '').startsWith(`${agentId}_`)));
        if (removed.length > 0) {
          db.agents = db.agents.filter((a: any) => !removed.includes(a));
          writeDB(db);
          for (const agent of removed) io.emit('agent:removed', { id: agent.id });
        }
      }
    } catch {}
  };

  const activateOrRollback = async (name: string) => {
    try {
      return await mcpManager.restartServer(name);
    } catch (error) {
      mcpManager.uninstallSkill(name);
      throw error;
    }
  };

  // List all installed skills (local + external MCP servers)
  router.get("/skills", requireAuth, (req, res) => {
    try {
      const includeOperationalDetails = req.user?.role === 'admin' && isLoopbackAddress(req.socket?.remoteAddress);
      const localSkills = mcpManager.listLocalSkills();
      const mcpConfig = getMCPConfig();
      const health = mcpManager.getServerHealth();
      const allSkills = Object.entries(mcpConfig).map(([name, config]) => {
        const local = localSkills.find(s => s.name === name);
        const serverHealth = health[name];
        const startupError = serverHealth?.lastError || getStartupFailureNote(config.description);
        const summary = {
          name,
          description: stripStartupFailureNote(config.description, name),
          enabled: config.enabled,
          source: config.source || 'external',
          autoGenerated: config.autoGenerated || false,
          toolCount: config.toolCount || (local?.toolCount || 0),
          connected: mcpManager.getConnectedServers().includes(name),
          broken: local?.broken || false,
          healthStatus: serverHealth?.status || 'unknown',
          requiresApiKey: config.requiresApiKey || false,
        };
        if (!includeOperationalDetails) return summary;
        return {
          ...summary,
          generatedFrom: config.generatedFrom,
          installedAt: local?.installedAt || '',
          startupError,
          consecutiveCrashes: serverHealth?.consecutiveCrashes || 0,
          lastCrashTime: serverHealth?.lastCrashTime,
          lastSuccessfulConnect: serverHealth?.lastSuccessfulConnect,
          apiKeyEnv: config.apiKeyEnv,
          apiKeyUrl: config.apiKeyUrl,
        };
      });
      res.json({ skills: allSkills });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Generate a skill from description or workflows
  router.post("/skills/generate", requireAuth, requireAdmin, requireLocalRequest, asyncHandler(async (req, res) => {
    try {
      const { description, provider, model } = req.body;
      const dc = resolveDomain(req.user!);

      let workflows;
      if (req.body.workflowIds) {
        const allWorkflows = getRecentWorkflows(req.user!.uid, dc.domain, dc.orgId);
        workflows = allWorkflows.filter(w => (req.body.workflowIds as string[]).includes(w.id));
      } else if (req.body.useRecent) {
        workflows = getRecentWorkflows(req.user!.uid, dc.domain, dc.orgId).slice(-5);
      }

      const result = await generateSkill(
        {
          description,
          workflows,
          ...(provider ? { provider } : {}),
          ...(model ? { model } : {}),
          userId: req.user!.uid,
        },
        llmGetters.getDeepSeek, llmGetters.getGemini, llmGetters.getOpenAI, llmGetters.getAnthropic, llmGetters.getQwen,
        llmGetters.getOllama, llmGetters.getLmStudio, llmGetters.getArk, llmGetters.getXiaomi,
        llmGetters.getKimi, llmGetters.getGlm, llmGetters.getRelay,
      );

      if (result.success) {
        res.json({
          ...result,
          activated: false,
          note: 'Draft created in the isolated Lumi data directory. Review and explicitly install it before use.',
        });
      } else {
        res.status(400).json(result);
      }
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  }));

  // Install a skill from git/npm/local
  router.post("/skills/install", requireAuth, requireAdmin, requireLocalRequest, async (req, res) => {
    try {
      const { source, url, package: pkgName, path: localPath, name } = req.body;

      if (source === 'git' && url) {
        const destDir = await mcpManager.installFromGitHub(String(url));
        const skillName = path.basename(destDir);
        await activateOrRollback(skillName);
        createAgentForSkill(skillName, { description: `Git install: ${url}`, category: 'general', installSource: 'git', scope: skillAgentScope(req) }, io);
        res.json({ success: true, name: skillName, directory: destDir });
      } else if (source === 'local' && localPath) {
        const generatedDraft = readGeneratedSkillDraft(localPath);
        if (generatedDraft && req.body.approved !== true) {
          return res.status(409).json({
            error: 'Generated skill draft installation requires approved=true after reviewing permissions, risk, side effects, and trial results.',
            draft: generatedDraft,
          });
        }
        const validation = generatedDraft
          ? await validateGeneratedSkillDraftForInstall(localPath)
          : null;
        if (validation && !validation.valid) {
          return res.status(400).json({
            error: 'Generated skill draft validation failed.',
            details: validation.errors,
          });
        }
        const skillName = normalizeSkillInstallName(name || validation?.skillName || path.basename(localPath));
        const destDir = await mcpManager.installSkillValidated(
          skillName,
          localPath,
          validation?.review
            ? {
                approvedGeneratedDraft: {
                  approvedAt: new Date().toISOString(),
                  review: validation.review as unknown as Record<string, unknown>,
                },
              }
            : undefined,
        );
        await activateOrRollback(skillName);
        createAgentForSkill(skillName, {
          description: generatedDraft ? `Approved generated draft: ${localPath}` : `Local install: ${localPath}`,
          category: 'general',
          installSource: generatedDraft ? 'generated' : 'local',
          scope: skillAgentScope(req),
        }, io);
        res.json({ success: true, name: skillName, directory: destDir });
      } else if (source === 'npm' && pkgName) {
        const npmDir = await mcpManager.installFromNpm(pkgName);
        const npmName = path.basename(npmDir);
        await activateOrRollback(npmName);
        io.emit('skill:installed', { name: npmName, source: 'npm' });
        createAgentForSkill(npmName, { description: `npm package: ${pkgName}`, category: 'general', installSource: 'npm', scope: skillAgentScope(req) }, io);
        res.json({ success: true, name: npmName, directory: npmDir });
      } else if (source === 'github' && url) {
        const ghDir = await mcpManager.installFromGitHub(url);
        const ghName = path.basename(ghDir);
        await activateOrRollback(ghName);
        io.emit('skill:installed', { name: ghName, source: 'github' });
        createAgentForSkill(ghName, { description: `GitHub repo: ${url}`, category: 'general', installSource: 'github', scope: skillAgentScope(req) }, io);
        res.json({ success: true, name: ghName, directory: ghDir });
      } else {
        res.status(400).json({ error: 'Invalid source. Use: github/git (with a GitHub HTTPS URL), local (with path), or npm (with package)' });
      }
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Repair a local skill by reinstalling known sources or restarting it
  router.post("/skills/:name/repair", requireAuth, requireAdmin, requireLocalRequest, async (req, res) => {
    try {
      const result = await mcpManager.repairSkill(req.params.name);
      if (!result.success) return res.status(400).json(result);
      io.emit('skill:updated', { name: req.params.name });
      res.json(result);
    } catch (err: any) {
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // Explicitly clean incomplete local skills
  router.delete("/skills/broken", requireAuth, requireAdmin, requireLocalRequest, async (_req, res) => {
    try {
      const removed = mcpManager.cleanupBrokenSkills();
      for (const name of removed) {
        io.emit('skill:uninstalled', { name });
        removeAutoAgentForSkill(name);
      }
      res.json({ success: true, removed });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Uninstall a skill
  router.delete("/skills/:name", requireAuth, requireAdmin, requireLocalRequest, async (req, res) => {
    try {
      mcpManager.uninstallSkill(req.params.name);
      io.emit('skill:uninstalled', { name: req.params.name });
      removeAutoAgentForSkill(req.params.name);
      res.json({ success: true });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Enable a skill
  router.post("/skills/:name/enable", requireAuth, requireAdmin, requireLocalRequest, async (req, res) => {
    try {
      const config = getMCPConfig();
      if (!config[req.params.name]) return res.status(404).json({ error: 'Skill not found' });
      const skillConfig = config[req.params.name];
      if (skillConfig.requiresApiKey && skillConfig.apiKeyEnv) {
        const stored = loadKeys()[skillConfig.apiKeyEnv]?.trim();
        const fromEnv = process.env[skillConfig.apiKeyEnv]?.trim();
        if (!stored && !fromEnv) {
          return res.status(400).json({
            error: `Configure ${skillConfig.apiKeyEnv} before enabling this skill.`,
            requiresApiKey: true,
            apiKeyEnv: skillConfig.apiKeyEnv,
            apiKeyUrl: skillConfig.apiKeyUrl,
          });
        }
      }
      skillConfig.enabled = true;
      updateMCPConfig(config);
      try { await mcpManager.restartServer(req.params.name); } catch {} // start the process
      res.json({ success: true });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Disable a skill
  router.post("/skills/:name/disable", requireAuth, requireAdmin, requireLocalRequest, async (req, res) => {
    try {
      const config = getMCPConfig();
      if (!config[req.params.name]) return res.status(404).json({ error: 'Skill not found' });
      config[req.params.name].enabled = false;
      updateMCPConfig(config);
      try { await mcpManager.disconnectServer(req.params.name); } catch {} // stop the process
      res.json({ success: true });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Workflow inspection (for debugging / manual generation)
  router.get("/skills/workflows", requireAuth, (req, res) => {
    const dc = resolveDomain(req.user!);
    const workflows = getRecentWorkflows(req.user!.uid, dc.domain, dc.orgId);
    res.json({ workflows: workflows.slice(-20), total: workflows.length });
  });
}
