import fs from 'node:fs';
import path from 'node:path';

export interface GeneratedSkillHistoryItem {
  id: string;
  skillName: string;
  displayName: string;
  description: string;
  generatedAt: string;
  status: 'draft' | 'installed' | 'disabled' | 'broken';
  reviewHash?: string;
  draftId?: string;
}

/** Read bounded metadata only. Listing never installs, validates code by
 * executing it, issues approval, or loads a module from a Skill package. */
export function listGeneratedSkillHistory(input: {
  draftsRoot: string;
  skillsRoot: string;
  runtimeStates: Array<{ name: string; enabled: boolean; usable: boolean; broken: boolean }>;
}): GeneratedSkillHistoryItem[] {
  const rows: GeneratedSkillHistoryItem[] = [];
  for (const [root, installed] of [[input.skillsRoot, true], [input.draftsRoot, false]] as const) {
    if (!fs.existsSync(root) || fs.lstatSync(root).isSymbolicLink()) continue;
    const directories = fs.readdirSync(root, { withFileTypes: true }).filter(entry => entry.isDirectory() && !entry.isSymbolicLink()).slice(0, 500);
    for (const directory of directories) {
      try {
        const file = path.join(root, directory.name, 'package.json');
        const stat = fs.lstatSync(file);
        if (!stat.isFile() || stat.isSymbolicLink() || stat.size > 512_000) continue;
        const pkg = JSON.parse(fs.readFileSync(file, 'utf8'));
        const lumi = pkg.lumi;
        if (!lumi || (installed ? lumi.generatedByLumi !== true && lumi.managedSkill?.origin !== 'generated' : lumi.autoGenerated !== true || lumi.status !== 'draft')) continue;
        const skillName = installed ? directory.name : String(lumi.skillName || '');
        if (!skillName) continue;
        const reviewHash = String(installed ? lumi.managedSkill?.reviewHash || lumi.draftReview?.contentHash || '' : lumi.draftReview?.contentHash || '');
        const state = input.runtimeStates.find(item => item.name === skillName);
        const description = String(pkg.description || '').slice(0, 1000);
        const title = description.split(/[:：]/u)[0];
        const displayName = String(lumi.displayName || (title.length < description.length && title.length <= 80 ? title : skillName));
        const sameInstalled = !installed && reviewHash && rows.find(item => item.skillName === skillName && item.reviewHash === reviewHash && !item.draftId);
        if (sameInstalled) continue;
        rows.push({ id: `${installed ? 'installed' : 'draft'}:${directory.name}`, skillName, displayName, description,
          generatedAt: String(lumi.draftReview?.generatedAt || lumi.installedAt || ''),
          status: installed ? state?.broken || !state ? 'broken' : !state.enabled ? 'disabled' : state.usable ? 'installed' : 'broken' : 'draft',
          ...(reviewHash ? { reviewHash } : {}), ...(!installed ? { draftId: directory.name } : {}) });
      } catch { /* A malformed entry cannot hide the remaining history. */ }
    }
  }
  return rows.sort((a, b) => b.generatedAt.localeCompare(a.generatedAt));
}
