/**
 * Lumi Skill Generator — LLM-driven MCP server package generation.
 *
 * Takes workflow records (tool call sequences) or natural language descriptions
 * and generates a complete, installable MCP server package in ~/lumi_skills/.
 */
import fs from 'fs';
import path from 'path';
import os from 'os';
import { createHash } from 'crypto';
import { exec } from 'child_process';
import * as ts from 'typescript';
import { makeLLMCall, NormalizedMessage } from '../llm/providers';
import { getScopedPreferredLLM } from '../llm/user_preferences';
import type { UserLLMProvider } from '../llm/user_preferences';
import { WorkflowRecord, WorkflowStep } from './worklog';
import { mcpManager, SKILLS_DIR } from '../mcp/client';
import { getDataPath } from '../config/data_path';

const SKILLS_DIR_PATH = SKILLS_DIR;
const SKILL_DRAFTS_DIR = getDataPath('skill-drafts');
const GENERATED_SKILL_DEPENDENCIES = {
  '@modelcontextprotocol/sdk': '^1.0.0',
  '@types/node': '^22.14.0',
  tsx: '^4.21.0',
  typescript: '~5.8.2',
  zod: '^3.22.0',
} as const;
const GENERATED_SKILL_TOP_LEVEL_FIELDS = new Set([
  'name',
  'version',
  'description',
  'type',
  'main',
  'scripts',
  'dependencies',
  'lumi',
]);
const GENERATED_SKILL_LUMI_FIELDS = new Set([
  'autoGenerated',
  'status',
  'skillName',
  'generatedFrom',
  'installedAt',
  'toolCount',
  'draftReview',
]);
const GENERATED_SKILL_REVIEW_FIELDS = new Set([
  'status',
  'generatedAt',
  'contentHash',
  'permissions',
  'sideEffects',
  'risk',
  'evidence',
  'staticCheck',
  'trialRun',
  'requiresUserApproval',
]);
const GENERATED_SKILL_EVIDENCE_FIELDS = new Set([
  'kind',
  'assurance',
  'limitations',
]);
const GENERATED_SKILL_STATIC_CHECK_FIELDS = new Set([
  'passed',
  'findings',
]);
const GENERATED_SKILL_TRIAL_RUN_FIELDS = new Set([
  'passed',
  'note',
]);
const GENERATED_SKILL_TOP_LEVEL_ENTRIES = new Set([
  'package.json',
  'package-lock.json',
  'index.ts',
  'README.md',
  'node_modules',
]);
const GENERATED_SKILL_REQUIRED_FILES = [
  'package.json',
  'package-lock.json',
  'index.ts',
  'README.md',
] as const;

export interface SkillGenerateRequest {
  /** Natural language description of what the skill should do */
  description?: string;
  /** Existing workflows to learn from */
  workflows?: WorkflowRecord[];
  /** LLM provider to use */
  provider?: UserLLMProvider;
  model?: string;
  userId?: string;
}

export interface SkillGenerateResult {
  success: boolean;
  skillName?: string;
  toolName?: string;
  directory?: string;
  status?: 'draft';
  review?: GeneratedSkillDraftReview;
  error?: string;
  generatedCode?: string;
}

export interface GeneratedSkillDraftReview {
  status: 'draft';
  generatedAt: string;
  contentHash: string;
  permissions: string[];
  sideEffects: string[];
  risk: 'low' | 'medium' | 'high';
  evidence: {
    kind: 'protocol_structure_validation';
    assurance: 'non_executing';
    limitations: string[];
  };
  staticCheck: {
    passed: boolean;
    findings: string[];
  };
  trialRun: {
    passed: boolean;
    note: string;
  };
  requiresUserApproval: true;
}

const GENERATE_PROMPT = `You are a Skill SDK generator for LumiCore. Your job is to create a reviewable MCP (Model Context Protocol) server tool that performs only pure computation or in-memory data transformation.

## Context
Lumi has learned a repeatable workflow by observing tool execution patterns. Encode only the pure, deterministic data-transformation portion as a standalone MCP tool.

## Input
{inputDescription}

## Output Requirements
Output ONLY a JSON object with these fields:

{
  "skillName": "lowercase-kebab-case-name",
  "toolName": "snake_case_tool_name",
  "toolDescription": "1-2 sentence description of what this tool does",
  "inputSchema": {
    "type": "object",
    "properties": {
      "paramName": { "type": "string", "description": "what this param is" }
    },
    "required": ["paramName"]
  },
  "handlerCode": "The COMPLETE TypeScript body placed inside the single async MCP tool callback. It may only calculate from args and transform in-memory JSON-compatible data. It MUST set the existing variable named 'result' to a string. Example:\\n  const values = Array.isArray(args.values) ? args.values.map(Number) : [];\\n  const total = values.reduce((sum, value) => sum + value, 0);\\n  result = JSON.stringify({{ total }});",
  "permissions": [],
  "sideEffects": [],
  "risk": "low",
  "readme": "Markdown documentation: what the skill does, usage example, parameters, output format"
}

## Guidelines
- The skillName should be short and descriptive (max 3 words, kebab-case)
- Generated handlers are restricted to pure computation and in-memory data transformation. If the request needs files, network, processes, environment access, desktop control, or another host capability, do not generate a skill for it.
- handlerCode MUST be real executable TypeScript, not a description. It is reviewed as source and is never executed before approval.
- Keep inputSchema focused: only parameters that change between invocations
- Do not use import, require, eval, Function, dynamic import, process, globalThis, global, Deno, Bun, fetch, WebSocket, filesystem, network, shell/process APIs, environment APIs, computed property access, constructor/prototype escape, or hidden nested tool execution
- permissions and sideEffects MUST both be empty arrays; generated skills are reviewed drafts and are never installed automatically
- Always set 'result' to a string before the function returns
- For async operations, use 'await' — the handler is an async function
- Do NOT include 'import' statements or 'export' — those are added automatically

JSON output:`;

const SKILL_TEMPLATE = `/**
 * Auto-generated Lumi Skill: {skillName}
 * Generated at: {timestamp}
 * Generator: Lumi Skill SDK
 */
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';


// ── Generated Handler ──

// ── Schema (generated) ──
const inputSchema = {inputSchema};

// ── MCP Server Entry ──
async function main() {
  const server = new McpServer(
    { name: '{skillName}', version: '1.0.0' },
    { capabilities: { tools: {} } }
  );

  server.registerTool(
    '{toolName}',
    {
      description: '{toolDescription}',
      inputSchema,
    },
    {handlerCode}
  );

  const transport = new StdioServerTransport();
  await server.connect(transport);
}

await main();
`;

const PACKAGE_TEMPLATE = `{
  "name": "lumi-skill-{skillName}",
  "version": "1.0.0",
  "description": "{toolDescription}",
  "type": "module",
  "main": "index.ts",
  "scripts": {
    "start": "npx --no-install tsx index.ts"
  },
  "dependencies": {
    "@modelcontextprotocol/sdk": "^1.0.0",
    "@types/node": "^22.14.0",
    "tsx": "^4.21.0",
    "typescript": "~5.8.2",
    "zod": "^3.22.0"
  },
  "lumi": {
    "autoGenerated": true,
    "status": "draft",
    "skillName": "{skillName}",
    "generatedFrom": "{generatedFrom}",
    "installedAt": "{installedAt}",
    "toolCount": 1,
    "draftReview": {draftReview}
  }
}
`;

/**
 * Generate a skill from workflow records or a natural language description.
 */
export async function generateSkill(
  request: SkillGenerateRequest,
  getDeepSeek: () => any,
  getGemini: () => any,
  getOpenAI?: () => any,
  getAnthropic?: () => any,
  getQwen?: () => any,
  getOllama?: () => any,
  getLmStudio?: () => any,
  getArk?: () => any,
  getXiaomi?: () => any,
  getKimi?: () => any,
  getGlm?: () => any,
  getRelay?: () => any,
): Promise<SkillGenerateResult> {
  // Build input description for LLM
  let inputDescription = '';

  if (request.workflows && request.workflows.length > 0) {
    const intents = [...new Set(request.workflows.map(w => w.userIntent))];
    const allTools = request.workflows.flatMap(w => w.toolSequence);

    inputDescription = `## Observed Workflow Pattern
This workflow has been executed ${request.workflows.length} times.

### User Intent
${intents.join('\n')}

### Tool Call Sequences
${request.workflows.map((w, i) => `
Execution #${i + 1}:
${w.toolSequence.map((s, j) => `  ${j + 1}. ${s.name}(${JSON.stringify(s.args)}) → ${s.resultSummary.slice(0, 100)}`).join('\n')}
`).join('\n')}

### Most Common Tools Used
${topTools(allTools).map(t => `- ${t.name} (${t.count}x)`).join('\n')}
`;
  } else if (request.description) {
    inputDescription = `## User Request\n${request.description}`;
  } else {
    return { success: false, error: 'No workflows or description provided' };
  }

  const prompt = GENERATE_PROMPT.replace('{inputDescription}', inputDescription);

  const messages: NormalizedMessage[] = [
    { role: 'user', content: prompt },
  ];

  const preferred = getScopedPreferredLLM(request.userId || 'skill_gen');
  const provider = request.provider || preferred.provider;
  const model = request.model || preferred.model;
  const explicitModelOverride = Boolean(request.provider || request.model);
  const routeConfig = {
    provider,
    model,
    userId: request.userId || 'skill_gen',
    selectionMode: explicitModelOverride ? 'pinned' as const : preferred.selectionMode,
    fallbackCandidates: explicitModelOverride ? [] : preferred.fallbackCandidates,
    allowCloudFallback: explicitModelOverride ? false : preferred.allowCloudFallback,
    source: 'skill_generator',
  };
  let generatedSkillStagingDir = '';
  let generatedPublishedDraftDir = '';

  try {
    const response = await makeLLMCall(
      messages,
      [],
      { ...routeConfig, maxTokens: 2048 },
      getDeepSeek,
      getGemini,
      getOpenAI,
      getAnthropic,
      getQwen,
      getOllama,
      getLmStudio,
      getArk,
      getXiaomi,
      getKimi,
      getGlm,
      getRelay,
    );

    const text = response.text || '';
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      return { success: false, error: 'LLM did not return valid JSON', generatedCode: text };
    }

    const parsed = JSON.parse(jsonMatch[0]);

    if (!parsed.skillName || !parsed.toolName) {
      return { success: false, error: 'Missing skillName or toolName in generated output', generatedCode: text };
    }

    if (!parsed.handlerCode || typeof parsed.handlerCode !== 'string' || parsed.handlerCode.trim().length === 0) {
      // If LLM returned old field name (handlerLogic), retry with explicit conversion prompt
      if (parsed.handlerLogic && typeof parsed.handlerLogic === 'string') {
        console.warn('[SkillGen] LLM returned handlerLogic instead of handlerCode — retrying with conversion prompt');
        const conversionMessages: NormalizedMessage[] = [
          { role: 'user', content: `Turn this handler logic description into a pure TypeScript data-transform body for the single async MCP callback. The body may only calculate from 'args' (Record<string, any>) and must set the existing variable named "result" to a string. Do not use files, network, processes, environment access, dynamic code, imports, or computed property access.\n\nLogic:\n${parsed.handlerLogic}\n\nReturn ONLY a JSON object: {"handlerCode": "// the pure computation code here"}` },
        ];
        try {
          const convResponse = await makeLLMCall(
            conversionMessages, [],
            { ...routeConfig, maxTokens: 2048 },
            getDeepSeek, getGemini, getOpenAI, getAnthropic, getQwen,
            getOllama, getLmStudio, getArk, getXiaomi, getKimi, getGlm, getRelay,
          );
          const convText = convResponse.text || '';
          const convJson = convText.match(/\{[\s\S]*\}/);
          if (convJson) {
            const convParsed = JSON.parse(convJson[0]);
            if (convParsed.handlerCode && typeof convParsed.handlerCode === 'string') {
              parsed.handlerCode = convParsed.handlerCode;
              console.log('[SkillGen] Successfully converted handlerLogic → handlerCode');
            }
          }
        } catch (e: any) {
          console.warn('[SkillGen] handlerLogic conversion retry failed:', e.message);
        }
      }

      // If still no handlerCode after retry, fail
      if (!parsed.handlerCode || typeof parsed.handlerCode !== 'string' || parsed.handlerCode.trim().length === 0) {
        return { success: false, error: 'LLM did not return handlerCode', generatedCode: text };
      }
    }

    // Build the skill draft. Generated code never enters the active skill
    // directory and is never registered with MCP from this function.
    const skillName = parsed.skillName.toLowerCase().replace(/[^a-z0-9-]/g, '-');
    const installedSkillDir = path.join(SKILLS_DIR_PATH, skillName);
    if (fs.existsSync(installedSkillDir) || mcpManager.getConfig()[skillName]) {
      return { success: false, error: `Skill "${skillName}" is already installed. Remove it before generating a replacement draft.`, directory: installedSkillDir };
    }
    generatedSkillStagingDir = path.join(os.tmpdir(), `lumi-skill-generate-${skillName}-${process.pid}-${Date.now()}`);
    const skillDir = generatedSkillStagingDir;

    const generatedFrom = request.workflows
      ? request.workflows.map(w => w.id).join(',')
      : 'manual';

    const now = new Date().toISOString();

    // Build the executable handler function from LLM-generated code
    const handlerCode = buildHandlerFunction(parsed.handlerCode, parsed.inputSchema);

    // Build the input schema as a Zod-compatible object literal for the template
    const schemaLiteral = buildSchemaLiteral(parsed.inputSchema);

    // Fill templates
    let indexTs = SKILL_TEMPLATE
      .replace(/{skillName}/g, skillName)
      .replace(/{toolName}/g, parsed.toolName)
      .replace(/{toolDescription}/g, escapeTsSingleQuoted(parsed.toolDescription || parsed.toolName))
      .replace(/{timestamp}/g, now)
      .replace('{handlerCode}', handlerCode)
      .replace('{inputSchema}', schemaLiteral);

    let review = buildGeneratedSkillDraftReview({
      source: indexTs,
      generatedAt: now,
      declaredPermissions: parsed.permissions,
      declaredSideEffects: parsed.sideEffects,
      declaredRisk: parsed.risk,
      validationPassed: false,
    });
    if (!review.staticCheck.passed) {
      return {
        success: false,
        skillName,
        toolName: parsed.toolName,
        generatedCode: indexTs,
        error: `Static skill review failed: ${review.staticCheck.findings.join(' | ')}`,
      };
    }
    let packageJson = buildDraftPackageJson({
      skillName,
      toolDescription: parsed.toolDescription || '',
      generatedFrom,
      generatedAt: now,
      review,
    });

    const readme = (parsed.readme || `# ${skillName}\n\n${parsed.toolDescription}`);

    // Write files
    if (!fs.existsSync(skillDir)) fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(path.join(skillDir, 'package.json'), packageJson);
    fs.writeFileSync(path.join(skillDir, 'index.ts'), indexTs);
    fs.writeFileSync(path.join(skillDir, 'README.md'), readme);

    console.log(`[SkillGen] Generated skill "${skillName}" at ${skillDir}`);

    // Resolve and lock dependencies without running package lifecycle scripts.
    // No compiler or generated runtime is started in this staging directory.
    await createSkillDependencyLock(skillDir);
    const lockfilePath = path.join(skillDir, 'package-lock.json');
    const lockfileSource = fs.readFileSync(lockfilePath, 'utf8');
    ({ packageJson, review } = assembleReviewedDraftPackage({
      skillName,
      toolDescription: parsed.toolDescription || '',
      generatedFrom,
      generatedAt: now,
      source: indexTs,
      lockfileSource,
      review,
    }));
    fs.writeFileSync(path.join(skillDir, 'package.json'), packageJson);

    const draftDir = allocateDraftDirectory(skillName, now);
    fs.mkdirSync(path.dirname(draftDir), { recursive: true });
    fs.renameSync(skillDir, draftDir);
    generatedSkillStagingDir = '';
    generatedPublishedDraftDir = draftDir;

    // Runtime smoke test — verify the process can start
    let validation = await validateGeneratedSkillDraftForInstall(draftDir);
    const firstTypeError = validation.errors.find(error => (
      error.startsWith('TypeScript validation failed:')
    ));

    if (!validation.valid && firstTypeError) {
      console.warn(`[SkillGen] Type-check failed for "${skillName}", retrying with error feedback...`);

      // Retry: feed errors back to LLM
      const retryPrompt = `Fix the TypeScript errors in this handler code.

## Original description
${inputDescription}

## Errored handler code
${parsed.handlerCode}

## TypeScript errors
${firstTypeError}

Return ONLY a JSON object with "handlerCode" (the fixed code body).`;

      try {
        const retryMessages: NormalizedMessage[] = [
          { role: 'user', content: retryPrompt },
        ];
        const retryResponse = await makeLLMCall(
          retryMessages, [],
          { ...routeConfig, maxTokens: 2048 },
          getDeepSeek, getGemini, getOpenAI, getAnthropic, getQwen,
          getOllama, getLmStudio, getArk, getXiaomi, getKimi, getGlm, getRelay,
        );

        const retryText = retryResponse.text || '';
        const retryJson = retryText.match(/\{[\s\S]*\}/);
        if (retryJson) {
          const retryParsed = JSON.parse(retryJson[0]);
          const fixedCode = retryParsed.handlerCode;
          if (fixedCode && typeof fixedCode === 'string') {
            const fixedHandler = buildHandlerFunction(fixedCode, parsed.inputSchema);
            const fixedIndexTs = SKILL_TEMPLATE
              .replace(/{skillName}/g, skillName)
              .replace(/{toolName}/g, parsed.toolName)
              .replace(/{toolDescription}/g, escapeTsSingleQuoted(parsed.toolDescription || parsed.toolName))
              .replace(/{timestamp}/g, now)
              .replace('{handlerCode}', fixedHandler)
              .replace('{inputSchema}', schemaLiteral);

            indexTs = fixedIndexTs;
            fs.writeFileSync(path.join(draftDir, 'index.ts'), fixedIndexTs);
            review = buildGeneratedSkillDraftReview({
              source: indexTs,
              generatedAt: now,
              declaredPermissions: parsed.permissions,
              declaredSideEffects: parsed.sideEffects,
              declaredRisk: parsed.risk,
              validationPassed: false,
            });
            ({ packageJson, review } = assembleReviewedDraftPackage({
              skillName,
              toolDescription: parsed.toolDescription || '',
              generatedFrom,
              generatedAt: now,
              source: indexTs,
              lockfileSource,
              review,
            }));
            fs.writeFileSync(path.join(draftDir, 'package.json'), packageJson);
            validation = await validateGeneratedSkillDraftForInstall(draftDir);
          }
        }
      } catch (retryErr: any) {
        validation = {
          valid: false,
          errors: [...validation.errors, `Retry failed: ${retryErr.message}`],
        };
      }
    }

    if (!validation.valid || !validation.review || !validation.validatedDirectory) {
      return {
        success: false,
        skillName,
        toolName: parsed.toolName,
        generatedCode: indexTs,
        error: validation.errors.join(' | '),
      };
    }

    try { fs.rmSync(validation.validatedDirectory, { recursive: true, force: true }); } catch {}
    ({ packageJson, review } = assembleReviewedDraftPackage({
      skillName,
      toolDescription: parsed.toolDescription || '',
      generatedFrom,
      generatedAt: now,
      source: indexTs,
      lockfileSource,
      review: validation.review,
    }));
    fs.writeFileSync(path.join(draftDir, 'package.json'), packageJson);
    const finalManifestValidation = validateGeneratedDraftManifest(draftDir, skillName);
    if (
      finalManifestValidation.errors.length > 0
      || computeGeneratedSkillArtifactHash(indexTs, packageJson, lockfileSource) !== review.contentHash
    ) {
      throw new Error(`Final generated draft integrity check failed: ${finalManifestValidation.errors.join(' | ')}`);
    }
    generatedPublishedDraftDir = '';

    return {
      success: true,
      skillName,
      toolName: parsed.toolName,
      directory: draftDir,
      status: 'draft',
      review,
      generatedCode: indexTs,
    };
  } catch (err: any) {
    console.error('[SkillGen] Generation failed:', err);
    return { success: false, error: err.message };
  } finally {
    if (generatedSkillStagingDir) {
      try { fs.rmSync(generatedSkillStagingDir, { recursive: true, force: true }); } catch {}
    }
    if (generatedPublishedDraftDir) {
      try { fs.rmSync(generatedPublishedDraftDir, { recursive: true, force: true }); } catch {}
    }
  }
}

function normalizeStringList(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return Array.from(new Set(
    value.map(item => String(item || '').trim()).filter(Boolean),
  )).sort((left, right) => left.localeCompare(right));
}

function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(',')}]`;
  if (value && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    return `{${Object.keys(record)
      .sort((left, right) => left.localeCompare(right))
      .map(key => `${JSON.stringify(key)}:${canonicalJson(record[key])}`)
      .join(',')}}`;
  }
  const primitive = JSON.stringify(value);
  return primitive === undefined ? 'null' : primitive;
}

function canonicalDraftManifest(manifestSource: string): string {
  if (!manifestSource.trim()) return '';
  const manifest = JSON.parse(manifestSource) as Record<string, any>;
  const lumi = manifest.lumi && typeof manifest.lumi === 'object'
    ? { ...manifest.lumi }
    : undefined;
  if (lumi?.draftReview && typeof lumi.draftReview === 'object') {
    // Bind the approval surface (permissions, side effects, risk, checks and
    // trial result) while replacing only the one self-referential value.
    // Removing the whole review would let those user-visible security facts
    // change without invalidating the artifact.
    lumi.draftReview = {
      ...lumi.draftReview,
      contentHash: '',
    };
    manifest.lumi = lumi;
  }
  return canonicalJson(manifest);
}

export function computeGeneratedSkillArtifactHash(
  source: string,
  manifestSource = '',
  lockfileSource = '',
): string {
  return createHash('sha256')
    .update('lumi-generated-skill-artifact-v2\0', 'utf8')
    .update(source, 'utf8')
    .update('\0manifest\0', 'utf8')
    .update(canonicalDraftManifest(manifestSource), 'utf8')
    .update('\0lockfile\0', 'utf8')
    .update(lockfileSource.trim() ? canonicalJson(JSON.parse(lockfileSource)) : '', 'utf8')
    .digest('hex');
}

function inspectGeneratedSkillSource(source: string): {
  permissions: string[];
  sideEffects: string[];
  risk: GeneratedSkillDraftReview['risk'];
  findings: string[];
} {
  return {
    permissions: [],
    sideEffects: [],
    risk: 'low',
    findings: validateGeneratedSkillProtocolStructure(source),
  };
}

const GENERATED_SKILL_IMPORTS = [
  ['@modelcontextprotocol/sdk/server/mcp.js', 'McpServer'],
  ['@modelcontextprotocol/sdk/server/stdio.js', 'StdioServerTransport'],
  ['zod', 'z'],
] as const;

const GENERATED_SKILL_FORBIDDEN_IDENTIFIERS = new Set([
  'require',
  'eval',
  'Function',
  'process',
  'globalThis',
  'global',
  'Deno',
  'Bun',
  'fetch',
  'WebSocket',
  'XMLHttpRequest',
  'EventSource',
  'Worker',
  'SharedWorker',
  'WebTransport',
  'navigator',
  'window',
  'document',
  'location',
  'localStorage',
  'sessionStorage',
  'indexedDB',
  'module',
  'exports',
  '__filename',
  '__dirname',
  'child_process',
  'fs',
  'net',
  'http',
  'https',
  'tls',
  'dgram',
  'dns',
  'cluster',
  'vm',
  'mcpManager',
  'toolRegistry',
  'executeToolCall',
  'desktopRelay',
]);

const GENERATED_SKILL_FORBIDDEN_PROPERTIES = new Set([
  'constructor',
  'prototype',
  '__proto__',
  'env',
]);

function generatedSkillFinding(findings: Set<string>, message: string): void {
  findings.add(message);
}

function importBindingMatches(
  statement: ts.Statement | undefined,
  expectedModule: string,
  expectedBinding: string,
): boolean {
  if (!statement || !ts.isImportDeclaration(statement) || !ts.isStringLiteral(statement.moduleSpecifier)) return false;
  if (statement.moduleSpecifier.text !== expectedModule) return false;
  const clause = statement.importClause;
  if (!clause || clause.isTypeOnly || clause.name || !clause.namedBindings || !ts.isNamedImports(clause.namedBindings)) {
    return false;
  }
  const elements = clause.namedBindings.elements;
  return elements.length === 1
    && !elements[0].isTypeOnly
    && !elements[0].propertyName
    && elements[0].name.text === expectedBinding;
}

function unwrapGeneratedExpression(expression: ts.Expression): ts.Expression {
  let current = expression;
  while (
    ts.isParenthesizedExpression(current)
    || ts.isAsExpression(current)
    || ts.isTypeAssertionExpression(current)
    || ts.isNonNullExpression(current)
    || ts.isSatisfiesExpression(current)
  ) {
    current = current.expression;
  }
  return current;
}

function propertyNameText(name: ts.PropertyName): string | null {
  if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name)) return name.text;
  return null;
}

function isStaticDataLiteral(expression: ts.Expression): boolean {
  const value = unwrapGeneratedExpression(expression);
  if (
    ts.isStringLiteral(value)
    || ts.isNumericLiteral(value)
    || value.kind === ts.SyntaxKind.TrueKeyword
    || value.kind === ts.SyntaxKind.FalseKeyword
    || value.kind === ts.SyntaxKind.NullKeyword
  ) return true;
  if (ts.isArrayLiteralExpression(value)) {
    return value.elements.every(element => ts.isExpression(element) && isStaticDataLiteral(element));
  }
  if (!ts.isObjectLiteralExpression(value)) return false;
  return value.properties.every(property => (
    ts.isPropertyAssignment(property)
    && propertyNameText(property.name) !== null
    && isStaticDataLiteral(property.initializer)
  ));
}

function isAllowedGeneratedSchemaExpression(expression: ts.Expression): boolean {
  const value = unwrapGeneratedExpression(expression);
  if (!ts.isCallExpression(value) || !ts.isPropertyAccessExpression(value.expression)) return false;
  const receiver = unwrapGeneratedExpression(value.expression.expression);
  const method = value.expression.name.text;

  if (ts.isIdentifier(receiver) && receiver.text === 'z') {
    if (['string', 'number', 'boolean', 'any'].includes(method)) return value.arguments.length === 0;
    if (method === 'array' || method === 'record') {
      return value.arguments.length === 1 && isAllowedGeneratedSchemaExpression(value.arguments[0]);
    }
    if (method !== 'object' || value.arguments.length !== 1) return false;
    const shape = unwrapGeneratedExpression(value.arguments[0]);
    return ts.isObjectLiteralExpression(shape) && shape.properties.every(property => (
      ts.isPropertyAssignment(property)
      && propertyNameText(property.name) !== null
      && isAllowedGeneratedSchemaExpression(property.initializer)
    ));
  }

  return method === 'describe'
    && value.arguments.length === 1
    && ts.isStringLiteral(value.arguments[0])
    && isAllowedGeneratedSchemaExpression(receiver);
}

function getSingleConstInitializer(statement: ts.Statement | undefined, name: string): ts.Expression | null {
  if (!statement || !ts.isVariableStatement(statement) || !(statement.declarationList.flags & ts.NodeFlags.Const)) return null;
  if (statement.declarationList.declarations.length !== 1) return null;
  const declaration = statement.declarationList.declarations[0];
  if (!ts.isIdentifier(declaration.name) || declaration.name.text !== name || !declaration.initializer) return null;
  return declaration.initializer;
}

function isIdentifierCall(expression: ts.Expression, name: string): expression is ts.CallExpression {
  const value = unwrapGeneratedExpression(expression);
  return ts.isCallExpression(value)
    && ts.isIdentifier(value.expression)
    && value.expression.text === name
    && value.arguments.length === 0;
}

function isAwaitedIdentifierCall(statement: ts.Statement | undefined, name: string): boolean {
  if (!statement || !ts.isExpressionStatement(statement)) return false;
  const expression = unwrapGeneratedExpression(statement.expression);
  return ts.isAwaitExpression(expression) && isIdentifierCall(expression.expression, name);
}

function isExactToolResultReturn(statement: ts.Statement): boolean {
  if (!ts.isReturnStatement(statement) || !statement.expression) return false;
  const resultObject = unwrapGeneratedExpression(statement.expression);
  if (!ts.isObjectLiteralExpression(resultObject) || resultObject.properties.length !== 1) return false;
  const content = resultObject.properties[0];
  if (!ts.isPropertyAssignment(content) || propertyNameText(content.name) !== 'content') return false;
  const contentArray = unwrapGeneratedExpression(content.initializer);
  if (!ts.isArrayLiteralExpression(contentArray) || contentArray.elements.length !== 1) return false;
  const item = unwrapGeneratedExpression(contentArray.elements[0] as ts.Expression);
  if (!ts.isObjectLiteralExpression(item) || item.properties.length !== 2) return false;
  const values = new Map<string, ts.Expression>();
  for (const property of item.properties) {
    if (!ts.isPropertyAssignment(property)) return false;
    const name = propertyNameText(property.name);
    if (!name) return false;
    values.set(name, property.initializer);
  }
  const typeValue = values.get('type');
  const textValue = values.get('text');
  return Boolean(
    typeValue
    && ts.isStringLiteral(unwrapGeneratedExpression(typeValue))
    && (unwrapGeneratedExpression(typeValue) as ts.StringLiteral).text === 'text'
    && textValue
    && ts.isIdentifier(unwrapGeneratedExpression(textValue))
    && (unwrapGeneratedExpression(textValue) as ts.Identifier).text === 'result'
  );
}

function constantGeneratedString(node: ts.Expression): string | null {
  const value = unwrapGeneratedExpression(node);
  if (ts.isStringLiteral(value) || ts.isNoSubstitutionTemplateLiteral(value)) return value.text;
  if (ts.isBinaryExpression(value) && value.operatorToken.kind === ts.SyntaxKind.PlusToken) {
    const left = constantGeneratedString(value.left);
    const right = constantGeneratedString(value.right);
    return left === null || right === null ? null : `${left}${right}`;
  }
  return null;
}

const GENERATED_SKILL_PURE_GLOBAL_VALUES = new Set([
  'undefined',
  'NaN',
  'Infinity',
  'Array',
  'Object',
  'JSON',
  'Math',
  'Number',
  'String',
  'Boolean',
  'BigInt',
  'parseInt',
  'parseFloat',
  'isFinite',
  'isNaN',
  'encodeURI',
  'encodeURIComponent',
  'decodeURI',
  'decodeURIComponent',
]);

const GENERATED_SKILL_PURE_GLOBAL_CALLS = new Set([
  'Number',
  'String',
  'Boolean',
  'BigInt',
  'parseInt',
  'parseFloat',
  'isFinite',
  'isNaN',
  'encodeURI',
  'encodeURIComponent',
  'decodeURI',
  'decodeURIComponent',
]);

const GENERATED_SKILL_NON_FIRST_CLASS_GLOBALS = new Set([
  'Array',
  'Object',
  'JSON',
  'Math',
]);

const GENERATED_SKILL_PURE_STATIC_VALUES: Record<string, Set<string>> = {
  Math: new Set([
    'E', 'LN10', 'LN2', 'LOG10E', 'LOG2E', 'PI', 'SQRT1_2', 'SQRT2',
  ]),
  Number: new Set([
    'EPSILON', 'MAX_SAFE_INTEGER', 'MAX_VALUE', 'MIN_SAFE_INTEGER', 'MIN_VALUE',
    'NaN', 'NEGATIVE_INFINITY', 'POSITIVE_INFINITY',
  ]),
};

const GENERATED_SKILL_PURE_STATIC_CALLS: Record<string, Set<string>> = {
  Array: new Set(['isArray', 'from', 'of']),
  Object: new Set(['keys', 'values', 'entries', 'fromEntries', 'hasOwn']),
  JSON: new Set(['parse', 'stringify']),
  Number: new Set(['isFinite', 'isInteger', 'isNaN', 'parseFloat', 'parseInt']),
  String: new Set(['fromCharCode', 'fromCodePoint']),
  BigInt: new Set(['asIntN', 'asUintN']),
  Math: new Set([
    'abs', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh',
    'cbrt', 'ceil', 'clz32', 'cos', 'cosh', 'exp', 'expm1', 'floor',
    'fround', 'hypot', 'imul', 'log', 'log10', 'log1p', 'log2', 'max',
    'min', 'pow', 'round', 'sign', 'sin', 'sinh', 'sqrt', 'tan', 'tanh',
    'trunc',
  ]),
};

const GENERATED_SKILL_PURE_INSTANCE_CALLS = new Set([
  'at',
  'charAt',
  'charCodeAt',
  'codePointAt',
  'concat',
  'endsWith',
  'entries',
  'every',
  'filter',
  'find',
  'findIndex',
  'flat',
  'flatMap',
  'forEach',
  'includes',
  'indexOf',
  'join',
  'keys',
  'lastIndexOf',
  'map',
  'match',
  'matchAll',
  'normalize',
  'padEnd',
  'padStart',
  'reduce',
  'reduceRight',
  'repeat',
  'replace',
  'replaceAll',
  'slice',
  'some',
  'split',
  'startsWith',
  'substring',
  'toExponential',
  'toFixed',
  'toLowerCase',
  'toPrecision',
  'toUpperCase',
  'trim',
  'trimEnd',
  'trimStart',
  'values',
]);

const GENERATED_SKILL_DANGEROUS_STRING_FRAGMENTS = [
  '__proto__',
  'constructor',
  'prototype',
  'globalthis',
  'child_process',
  'fs/promises',
  'node:',
  'return process',
  'return global',
  'require',
  'import(',
] as const;

function generatedSkillStringIsDangerous(value: string): boolean {
  const normalized = value.toLocaleLowerCase('en-US').replace(/\s+/g, ' ').trim();
  return GENERATED_SKILL_DANGEROUS_STRING_FRAGMENTS.some(fragment => normalized.includes(fragment));
}

function isGeneratedLocalWriteTarget(expression: ts.Expression, scope: Set<string>): boolean {
  const value = unwrapGeneratedExpression(expression);
  if (ts.isIdentifier(value)) return scope.has(value.text);
  if (ts.isPropertyAccessExpression(value)) {
    if (GENERATED_SKILL_FORBIDDEN_PROPERTIES.has(value.name.text)) return false;
    return isGeneratedLocalWriteTarget(value.expression, scope);
  }
  return false;
}

function isGeneratedAssignmentOperator(kind: ts.SyntaxKind): boolean {
  return kind >= ts.SyntaxKind.FirstAssignment && kind <= ts.SyntaxKind.LastAssignment;
}

function addGeneratedBindingNames(
  name: ts.BindingName,
  scope: Set<string>,
  findings: Set<string>,
): void {
  if (ts.isIdentifier(name)) {
    if (GENERATED_SKILL_PURE_GLOBAL_VALUES.has(name.text) || GENERATED_SKILL_FORBIDDEN_IDENTIFIERS.has(name.text)) {
      generatedSkillFinding(findings, `Generated skill callback cannot shadow reserved binding ${name.text}.`);
      return;
    }
    scope.add(name.text);
    return;
  }
  for (const element of name.elements) {
    if (ts.isOmittedExpression(element)) continue;
    if (element.propertyName && ts.isComputedPropertyName(element.propertyName)) {
      generatedSkillFinding(findings, 'Computed binding properties are not allowed in generated skill callbacks.');
    }
    addGeneratedBindingNames(element.name, scope, findings);
  }
}

function validateGeneratedCallbackExpression(
  expression: ts.Expression,
  scope: Set<string>,
  findings: Set<string>,
): void {
  const value = unwrapGeneratedExpression(expression);
  if (
    ts.isStringLiteral(value)
    || ts.isNoSubstitutionTemplateLiteral(value)
  ) {
    if (generatedSkillStringIsDangerous(value.text)) {
      generatedSkillFinding(findings, 'Generated skill callback contains a dangerous constant string.');
    }
    return;
  }
  if (
    ts.isNumericLiteral(value)
    || ts.isRegularExpressionLiteral(value)
    || value.kind === ts.SyntaxKind.TrueKeyword
    || value.kind === ts.SyntaxKind.FalseKeyword
    || value.kind === ts.SyntaxKind.NullKeyword
  ) return;
  if (ts.isIdentifier(value)) {
    if (
      !scope.has(value.text)
      && (
        !GENERATED_SKILL_PURE_GLOBAL_VALUES.has(value.text)
        || GENERATED_SKILL_NON_FIRST_CLASS_GLOBALS.has(value.text)
      )
    ) {
      generatedSkillFinding(findings, `Generated skill callback references non-whitelisted identifier ${value.text}.`);
    }
    return;
  }
  if (ts.isArrayLiteralExpression(value)) {
    for (const element of value.elements) {
      if (ts.isSpreadElement(element)) validateGeneratedCallbackExpression(element.expression, scope, findings);
      else validateGeneratedCallbackExpression(element as ts.Expression, scope, findings);
    }
    return;
  }
  if (ts.isObjectLiteralExpression(value)) {
    for (const property of value.properties) {
      if (ts.isSpreadAssignment(property)) {
        validateGeneratedCallbackExpression(property.expression, scope, findings);
        continue;
      }
      if (ts.isShorthandPropertyAssignment(property)) {
        validateGeneratedCallbackExpression(property.name, scope, findings);
        continue;
      }
      if (!ts.isPropertyAssignment(property) || propertyNameText(property.name) === null) {
        generatedSkillFinding(findings, 'Generated skill callback object literals may contain only plain data properties.');
        continue;
      }
      const propertyName = propertyNameText(property.name)!;
      if (GENERATED_SKILL_FORBIDDEN_PROPERTIES.has(propertyName) || generatedSkillStringIsDangerous(propertyName)) {
        generatedSkillFinding(findings, `Generated skill callback cannot define dangerous property ${propertyName}.`);
      }
      validateGeneratedCallbackExpression(property.initializer, scope, findings);
    }
    return;
  }
  if (ts.isPropertyAccessExpression(value)) {
    if (GENERATED_SKILL_FORBIDDEN_PROPERTIES.has(value.name.text)) {
      generatedSkillFinding(findings, `Generated skill callback cannot access escape property ${value.name.text}.`);
    }
    const receiver = unwrapGeneratedExpression(value.expression);
    if (
      ts.isIdentifier(receiver)
      && !scope.has(receiver.text)
      && GENERATED_SKILL_PURE_GLOBAL_VALUES.has(receiver.text)
    ) {
      if (GENERATED_SKILL_PURE_STATIC_VALUES[receiver.text]?.has(value.name.text) !== true) {
        generatedSkillFinding(findings, 'Generated skill callback cannot extract methods or unknown properties from global objects.');
      }
      return;
    }
    validateGeneratedCallbackExpression(receiver, scope, findings);
    return;
  }
  if (ts.isElementAccessExpression(value)) {
    generatedSkillFinding(findings, 'Computed property access is not allowed in generated skill callbacks.');
    validateGeneratedCallbackExpression(value.expression, scope, findings);
    if (value.argumentExpression) validateGeneratedCallbackExpression(value.argumentExpression, scope, findings);
    return;
  }
  if (ts.isCallExpression(value)) {
    let allowed = false;
    const callee = unwrapGeneratedExpression(value.expression);
    if (ts.isIdentifier(callee)) {
      allowed = !scope.has(callee.text) && GENERATED_SKILL_PURE_GLOBAL_CALLS.has(callee.text);
    } else if (ts.isPropertyAccessExpression(callee)) {
      const receiver = unwrapGeneratedExpression(callee.expression);
      const method = callee.name.text;
      if (ts.isIdentifier(receiver) && !scope.has(receiver.text)) {
        allowed = GENERATED_SKILL_PURE_STATIC_CALLS[receiver.text]?.has(method) === true;
      }
      if (!allowed && GENERATED_SKILL_PURE_INSTANCE_CALLS.has(method)) {
        allowed = true;
        validateGeneratedCallbackExpression(receiver, scope, findings);
      }
    }
    if (!allowed) {
      generatedSkillFinding(findings, 'Generated skill callback contains a non-whitelisted function or method call.');
      validateGeneratedCallbackExpression(callee, scope, findings);
    }
    for (const argument of value.arguments) {
      validateGeneratedCallbackExpression(
        ts.isSpreadElement(argument) ? argument.expression : argument,
        scope,
        findings,
      );
    }
    return;
  }
  if (ts.isNewExpression(value)) {
    generatedSkillFinding(findings, 'Generated skill callback cannot construct objects with new.');
    if (value.arguments) {
      value.arguments.forEach(argument => validateGeneratedCallbackExpression(argument, scope, findings));
    }
    return;
  }
  if (ts.isTaggedTemplateExpression(value)) {
    generatedSkillFinding(findings, 'Tagged templates are not allowed in generated skill callbacks.');
    return;
  }
  if (ts.isArrowFunction(value)) {
    if (value.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.AsyncKeyword)) {
      generatedSkillFinding(findings, 'Nested async callbacks are not allowed in generated skill callbacks.');
    }
    const childScope = new Set(scope);
    for (const parameter of value.parameters) {
      addGeneratedBindingNames(parameter.name, childScope, findings);
      if (parameter.initializer) validateGeneratedCallbackExpression(parameter.initializer, scope, findings);
    }
    if (ts.isBlock(value.body)) validateGeneratedCallbackStatements(value.body.statements, childScope, findings);
    else validateGeneratedCallbackExpression(value.body, childScope, findings);
    return;
  }
  if (ts.isBinaryExpression(value)) {
    if (
      value.operatorToken.kind === ts.SyntaxKind.InKeyword
      || value.operatorToken.kind === ts.SyntaxKind.InstanceOfKeyword
    ) {
      generatedSkillFinding(findings, 'Reflection-style binary operators are not allowed in generated skill callbacks.');
    }
    if (isGeneratedAssignmentOperator(value.operatorToken.kind) && !isGeneratedLocalWriteTarget(value.left, scope)) {
      generatedSkillFinding(findings, 'Generated skill callback assignments may target only local data.');
    }
    validateGeneratedCallbackExpression(value.left, scope, findings);
    validateGeneratedCallbackExpression(value.right, scope, findings);
    return;
  }
  if (ts.isDeleteExpression(value)) {
    generatedSkillFinding(findings, 'delete is not allowed in generated skill callbacks.');
    validateGeneratedCallbackExpression(value.expression, scope, findings);
    return;
  }
  if (ts.isPrefixUnaryExpression(value) || ts.isPostfixUnaryExpression(value)) {
    if (
      [ts.SyntaxKind.PlusPlusToken, ts.SyntaxKind.MinusMinusToken].includes(value.operator)
      && !isGeneratedLocalWriteTarget(value.operand, scope)
    ) {
      generatedSkillFinding(findings, 'Generated skill callback updates may target only local data.');
    }
    validateGeneratedCallbackExpression(value.operand, scope, findings);
    return;
  }
  if (ts.isConditionalExpression(value)) {
    validateGeneratedCallbackExpression(value.condition, scope, findings);
    validateGeneratedCallbackExpression(value.whenTrue, scope, findings);
    validateGeneratedCallbackExpression(value.whenFalse, scope, findings);
    return;
  }
  if (ts.isTemplateExpression(value)) {
    if (generatedSkillStringIsDangerous(value.head.text)) {
      generatedSkillFinding(findings, 'Generated skill callback contains a dangerous constant string.');
    }
    value.templateSpans.forEach(span => {
      validateGeneratedCallbackExpression(span.expression, scope, findings);
      if (generatedSkillStringIsDangerous(span.literal.text)) {
        generatedSkillFinding(findings, 'Generated skill callback contains a dangerous constant string.');
      }
    });
    return;
  }
  if (ts.isTypeOfExpression(value) || ts.isVoidExpression(value)) {
    validateGeneratedCallbackExpression(value.expression, scope, findings);
    return;
  }
  if (ts.isAwaitExpression(value) || ts.isYieldExpression(value)) {
    generatedSkillFinding(findings, 'Async suspension is not allowed in pure generated skill callbacks.');
    if (value.expression) validateGeneratedCallbackExpression(value.expression, scope, findings);
    return;
  }
  if (ts.isCommaListExpression(value)) {
    value.elements.forEach(element => validateGeneratedCallbackExpression(element, scope, findings));
    return;
  }

  generatedSkillFinding(
    findings,
    `Generated skill callback contains unsupported expression ${ts.SyntaxKind[value.kind] || value.kind}.`,
  );
}

function validateGeneratedVariableDeclarationList(
  declarationList: ts.VariableDeclarationList,
  scope: Set<string>,
  findings: Set<string>,
): void {
  for (const declaration of declarationList.declarations) {
    if (declaration.initializer) {
      validateGeneratedCallbackExpression(declaration.initializer, scope, findings);
    }
    addGeneratedBindingNames(declaration.name, scope, findings);
  }
}

function validateGeneratedCallbackStatement(
  statement: ts.Statement,
  scope: Set<string>,
  findings: Set<string>,
): void {
  if (ts.isVariableStatement(statement)) {
    validateGeneratedVariableDeclarationList(statement.declarationList, scope, findings);
    return;
  }
  if (ts.isExpressionStatement(statement)) {
    validateGeneratedCallbackExpression(statement.expression, scope, findings);
    return;
  }
  if (ts.isReturnStatement(statement) || ts.isThrowStatement(statement)) {
    if (statement.expression) validateGeneratedCallbackExpression(statement.expression, scope, findings);
    return;
  }
  if (ts.isIfStatement(statement)) {
    validateGeneratedCallbackExpression(statement.expression, scope, findings);
    validateGeneratedCallbackStatement(statement.thenStatement, new Set(scope), findings);
    if (statement.elseStatement) {
      validateGeneratedCallbackStatement(statement.elseStatement, new Set(scope), findings);
    }
    return;
  }
  if (ts.isBlock(statement)) {
    validateGeneratedCallbackStatements(statement.statements, new Set(scope), findings);
    return;
  }
  if (
    ts.isForOfStatement(statement)
    || ts.isForInStatement(statement)
    || ts.isForStatement(statement)
    || ts.isWhileStatement(statement)
    || ts.isDoStatement(statement)
  ) {
    generatedSkillFinding(
      findings,
      'Generated skill callbacks cannot contain loops; use bounded pure array transforms instead.',
    );
    return;
  }
  if (
    ts.isBreakStatement(statement)
    || ts.isContinueStatement(statement)
    || ts.isEmptyStatement(statement)
  ) return;

  generatedSkillFinding(
    findings,
    `Generated skill callback contains unsupported statement ${ts.SyntaxKind[statement.kind] || statement.kind}.`,
  );
}

function validateGeneratedCallbackStatements(
  statements: readonly ts.Statement[],
  initialScope: Set<string>,
  findings: Set<string>,
): void {
  const scope = new Set(initialScope);
  for (const statement of statements) {
    validateGeneratedCallbackStatement(statement, scope, findings);
  }
}

function validateGeneratedSkillProtocolStructure(source: string): string[] {
  const findings = new Set<string>();
  if (!source.trim() || Buffer.byteLength(source, 'utf8') > 512 * 1024) {
    return ['Generated skill source must be non-empty and no larger than 512 KiB.'];
  }
  if (source.includes('\0')) {
    generatedSkillFinding(findings, 'Generated skill source cannot contain null bytes.');
  }

  const sourceFile = ts.createSourceFile(
    'index.ts',
    source,
    ts.ScriptTarget.ESNext,
    true,
    ts.ScriptKind.TS,
  );
  const parseDiagnostics = (sourceFile as ts.SourceFile & { parseDiagnostics?: readonly ts.Diagnostic[] }).parseDiagnostics || [];
  if (parseDiagnostics.length > 0) {
    generatedSkillFinding(findings, 'Generated skill source is not valid TypeScript syntax.');
    return [...findings];
  }

  if (sourceFile.statements.length !== 6) {
    generatedSkillFinding(findings, 'Generated skill source contains unexpected top-level statements.');
  }
  for (let index = 0; index < GENERATED_SKILL_IMPORTS.length; index += 1) {
    const expected = GENERATED_SKILL_IMPORTS[index];
    if (!importBindingMatches(sourceFile.statements[index], expected[0], expected[1])) {
      generatedSkillFinding(findings, 'Generated skill imports must be exactly the three fixed MCP/Zod modules.');
    }
  }
  if (sourceFile.statements.some((statement, index) => index >= 3 && ts.isImportDeclaration(statement))) {
    generatedSkillFinding(findings, 'Generated skill imports must be exactly the three fixed MCP/Zod modules.');
  }

  const schemaInitializer = getSingleConstInitializer(sourceFile.statements[3], 'inputSchema');
  if (!schemaInitializer || !isAllowedGeneratedSchemaExpression(schemaInitializer)) {
    generatedSkillFinding(findings, 'Generated skill inputSchema must be a generator-owned Zod data schema.');
  }

  const mainStatement = sourceFile.statements[4];
  const mainFunction = mainStatement && ts.isFunctionDeclaration(mainStatement) ? mainStatement : null;
  const mainIsAsync = Boolean(
    mainFunction
    && mainFunction.name?.text === 'main'
    && mainFunction.parameters.length === 0
    && mainFunction.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.AsyncKeyword)
    && mainFunction.body
  );
  if (!mainIsAsync) {
    generatedSkillFinding(findings, 'Generated skill protocol envelope must contain the expected async main function.');
  }
  if (!isAwaitedIdentifierCall(sourceFile.statements[5], 'main')) {
    generatedSkillFinding(findings, 'Generated skill protocol envelope must end with exactly await main().');
  }

  let callback: ts.ArrowFunction | null = null;
  let callbackBody: ts.Block | null = null;
  if (mainIsAsync && mainFunction?.body) {
    const statements = mainFunction.body.statements;
    if (statements.length !== 4) {
      generatedSkillFinding(findings, 'Generated skill main function contains unexpected statements.');
    }

    const serverInitializer = getSingleConstInitializer(statements[0], 'server');
    const serverValue = serverInitializer ? unwrapGeneratedExpression(serverInitializer) : null;
    if (
      !serverValue
      || !ts.isNewExpression(serverValue)
      || !ts.isIdentifier(serverValue.expression)
      || serverValue.expression.text !== 'McpServer'
      || serverValue.arguments?.length !== 2
      || !serverValue.arguments.every(isStaticDataLiteral)
    ) {
      generatedSkillFinding(findings, 'Generated skill main function must construct only the expected MCP server envelope.');
    }

    const registerStatement = statements[1];
    if (registerStatement && ts.isExpressionStatement(registerStatement)) {
      const expression = unwrapGeneratedExpression(registerStatement.expression);
      if (
        ts.isCallExpression(expression)
        && ts.isPropertyAccessExpression(expression.expression)
        && ts.isIdentifier(expression.expression.expression)
        && expression.expression.expression.text === 'server'
        && expression.expression.name.text === 'registerTool'
        && expression.arguments.length === 3
        && ts.isStringLiteral(expression.arguments[0])
      ) {
        const registration = unwrapGeneratedExpression(expression.arguments[1]);
        const handler = unwrapGeneratedExpression(expression.arguments[2]);
        if (ts.isObjectLiteralExpression(registration)) {
          const fields = new Map<string, ts.ObjectLiteralElementLike>();
          for (const property of registration.properties) {
            if (ts.isPropertyAssignment(property) || ts.isShorthandPropertyAssignment(property)) {
              const name = propertyNameText(property.name);
              if (name) fields.set(name, property);
            }
          }
          const description = fields.get('description');
          const schema = fields.get('inputSchema');
          if (
            fields.size !== 2
            || !description
            || !ts.isPropertyAssignment(description)
            || !ts.isStringLiteral(unwrapGeneratedExpression(description.initializer))
            || !schema
            || !(
              ts.isShorthandPropertyAssignment(schema)
              || (ts.isPropertyAssignment(schema)
                && ts.isIdentifier(unwrapGeneratedExpression(schema.initializer))
                && (unwrapGeneratedExpression(schema.initializer) as ts.Identifier).text === 'inputSchema')
            )
          ) {
            generatedSkillFinding(findings, 'Generated skill tool registration metadata changed outside the reviewed envelope.');
          }
        } else {
          generatedSkillFinding(findings, 'Generated skill tool registration metadata changed outside the reviewed envelope.');
        }
        if (
          ts.isArrowFunction(handler)
          && Boolean(handler.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.AsyncKeyword))
          && handler.parameters.length === 1
          && ts.isIdentifier(handler.parameters[0].name)
          && handler.parameters[0].name.text === 'args'
          && ts.isBlock(handler.body)
        ) {
          callback = handler;
          callbackBody = handler.body;
        }
      }
    }
    if (!callback) {
      generatedSkillFinding(findings, 'Generated implementation must exist only inside the unique async server.registerTool callback.');
    }

    const transportInitializer = getSingleConstInitializer(statements[2], 'transport');
    const transportValue = transportInitializer ? unwrapGeneratedExpression(transportInitializer) : null;
    if (
      !transportValue
      || !ts.isNewExpression(transportValue)
      || !ts.isIdentifier(transportValue.expression)
      || transportValue.expression.text !== 'StdioServerTransport'
      || (transportValue.arguments?.length || 0) !== 0
    ) {
      generatedSkillFinding(findings, 'Generated skill main function must construct only the expected stdio transport.');
    }
    const connectStatement = statements[3];
    let exactConnect = false;
    if (connectStatement && ts.isExpressionStatement(connectStatement)) {
      const outer = unwrapGeneratedExpression(connectStatement.expression);
      if (ts.isAwaitExpression(outer)) {
        const call = unwrapGeneratedExpression(outer.expression);
        exactConnect = ts.isCallExpression(call)
          && ts.isPropertyAccessExpression(call.expression)
          && ts.isIdentifier(call.expression.expression)
          && call.expression.expression.text === 'server'
          && call.expression.name.text === 'connect'
          && call.arguments.length === 1
          && ts.isIdentifier(call.arguments[0])
          && call.arguments[0].text === 'transport';
      }
    }
    if (!exactConnect) {
      generatedSkillFinding(findings, 'Generated skill main function must contain only the expected transport connection.');
    }
  }

  let registerToolCalls = 0;
  const visit = (node: ts.Node): void => {
    if (ts.isElementAccessExpression(node)) {
      generatedSkillFinding(findings, 'Computed property access is not allowed in generated skill drafts.');
    }
    if (ts.isPropertyAccessExpression(node) && GENERATED_SKILL_FORBIDDEN_PROPERTIES.has(node.name.text)) {
      generatedSkillFinding(findings, `Generated skill drafts cannot access escape property ${node.name.text}.`);
    }
    if (
      (ts.isPropertyAssignment(node) || ts.isMethodDeclaration(node) || ts.isPropertyDeclaration(node))
      && node.name
    ) {
      const name = propertyNameText(node.name);
      if (name && GENERATED_SKILL_FORBIDDEN_PROPERTIES.has(name)) {
        generatedSkillFinding(findings, `Generated skill drafts cannot define escape property ${name}.`);
      }
    }
    if (ts.isIdentifier(node) && GENERATED_SKILL_FORBIDDEN_IDENTIFIERS.has(node.text)) {
      generatedSkillFinding(findings, `Generated skill drafts cannot use host entry ${node.text}.`);
    }
    if (ts.isCallExpression(node) && node.expression.kind === ts.SyntaxKind.ImportKeyword) {
      generatedSkillFinding(findings, 'Dynamic imports are not allowed in generated skill drafts.');
    }
    if (ts.isImportTypeNode(node) || ts.isMetaProperty(node)) {
      generatedSkillFinding(findings, 'Generated skill drafts cannot access dynamic modules or import.meta.');
    }
    if (
      ts.isCallExpression(node)
      && ts.isPropertyAccessExpression(node.expression)
      && ts.isIdentifier(node.expression.expression)
      && node.expression.expression.text === 'server'
      && node.expression.name.text === 'registerTool'
    ) {
      registerToolCalls += 1;
    }
    if (ts.isBinaryExpression(node) && node.operatorToken.kind === ts.SyntaxKind.PlusToken) {
      const folded = constantGeneratedString(node);
      if (
        folded
        && (
          GENERATED_SKILL_FORBIDDEN_IDENTIFIERS.has(folded)
          || GENERATED_SKILL_FORBIDDEN_PROPERTIES.has(folded)
          || generatedSkillStringIsDangerous(folded)
        )
      ) {
        generatedSkillFinding(findings, `Generated skill drafts cannot construct host entry ${folded}.`);
      }
    }
    if (node.kind === ts.SyntaxKind.ThisKeyword || node.kind === ts.SyntaxKind.SuperKeyword) {
      generatedSkillFinding(findings, 'Generated skill drafts cannot use this or super as an escape surface.');
    }
    ts.forEachChild(node, visit);
  };
  visit(sourceFile);
  if (registerToolCalls !== 1) {
    generatedSkillFinding(findings, 'Generated skill source must contain exactly one server.registerTool call.');
  }

  if (callback && callbackBody) {
    validateGeneratedCallbackStatements(
      callbackBody.statements,
      new Set(['args']),
      findings,
    );
    const resultDeclarations = callbackBody.statements.flatMap(statement => (
      ts.isVariableStatement(statement)
        ? statement.declarationList.declarations.filter(declaration => (
            ts.isIdentifier(declaration.name) && declaration.name.text === 'result'
          ))
        : []
    ));
    if (resultDeclarations.length !== 1) {
      generatedSkillFinding(findings, 'Generated skill callback must contain exactly one generator-owned result variable.');
    }
    const finalStatement = callbackBody.statements[callbackBody.statements.length - 1];
    if (!finalStatement || !isExactToolResultReturn(finalStatement)) {
      generatedSkillFinding(findings, 'Generated skill callback must end with the expected text-content receipt.');
    }
    const forbiddenClosureNames = new Set(['server', 'transport', 'inputSchema', 'McpServer', 'StdioServerTransport']);
    const visitCallback = (node: ts.Node): void => {
      if (ts.isIdentifier(node) && forbiddenClosureNames.has(node.text)) {
        generatedSkillFinding(findings, `Generated skill callback cannot access envelope binding ${node.text}.`);
      }
      ts.forEachChild(node, visitCallback);
    };
    callbackBody.statements.forEach(visitCallback);
  }

  return [...findings];
}

function normalizeRisk(
  declared: unknown,
  inferred: GeneratedSkillDraftReview['risk'],
): GeneratedSkillDraftReview['risk'] {
  const ranks = { low: 0, medium: 1, high: 2 } as const;
  const requested = String(declared || '').toLowerCase() as keyof typeof ranks;
  if (!(requested in ranks)) return inferred;
  return ranks[requested] > ranks[inferred] ? requested : inferred;
}

function buildGeneratedSkillDraftReview(input: {
  source: string;
  manifestSource?: string;
  lockfileSource?: string;
  generatedAt: string;
  declaredPermissions?: unknown;
  declaredSideEffects?: unknown;
  declaredRisk?: unknown;
  validationPassed: boolean;
}): GeneratedSkillDraftReview {
  const inspection = inspectGeneratedSkillSource(input.source);
  const declaredPermissions = normalizeStringList(input.declaredPermissions);
  const declaredSideEffects = normalizeStringList(input.declaredSideEffects);
  const declarationFindings = [
    ...(declaredPermissions.length > 0
      ? ['Generated skill drafts cannot declare host permissions; only pure computation and in-memory data transformation are allowed.']
      : []),
    ...(declaredSideEffects.length > 0
      ? ['Generated skill drafts cannot declare side effects; only pure computation and in-memory data transformation are allowed.']
      : []),
  ];
  const findings = Array.from(new Set([
    ...inspection.findings,
    ...declarationFindings,
  ]));
  return {
    status: 'draft',
    generatedAt: input.generatedAt,
    contentHash: computeGeneratedSkillArtifactHash(
      input.source,
      input.manifestSource,
      input.lockfileSource,
    ),
    permissions: Array.from(new Set([
      ...declaredPermissions,
      ...inspection.permissions,
    ])).sort((left, right) => left.localeCompare(right)),
    sideEffects: Array.from(new Set([
      ...declaredSideEffects,
      ...inspection.sideEffects,
    ])).sort((left, right) => left.localeCompare(right)),
    risk: normalizeRisk(input.declaredRisk, inspection.risk),
    evidence: {
      kind: 'protocol_structure_validation',
      assurance: 'non_executing',
      limitations: [
        'No generated handler code was executed before approval; domain behavior is verified only after approved installation and activation.',
      ],
    },
    staticCheck: {
      passed: findings.length === 0,
      findings,
    },
    trialRun: {
      passed: input.validationPassed,
      note: input.validationPassed
        ? 'The non-executing protocol structure and locked dependency validation passed.'
        : 'The non-executing protocol structure and locked dependency validation have not passed.',
    },
    requiresUserApproval: true,
  };
}

function assembleReviewedDraftPackage(input: {
  skillName: string;
  toolDescription: string;
  generatedFrom: string;
  generatedAt: string;
  source: string;
  lockfileSource: string;
  review: GeneratedSkillDraftReview;
}): { packageJson: string; review: GeneratedSkillDraftReview } {
  const reviewWithoutHash: GeneratedSkillDraftReview = {
    ...input.review,
    contentHash: '',
  };
  const manifestForHash = buildDraftPackageJson({
    skillName: input.skillName,
    toolDescription: input.toolDescription,
    generatedFrom: input.generatedFrom,
    generatedAt: input.generatedAt,
    review: reviewWithoutHash,
  });
  const review: GeneratedSkillDraftReview = {
    ...reviewWithoutHash,
    contentHash: computeGeneratedSkillArtifactHash(
      input.source,
      manifestForHash,
      input.lockfileSource,
    ),
  };
  return {
    review,
    packageJson: buildDraftPackageJson({
      skillName: input.skillName,
      toolDescription: input.toolDescription,
      generatedFrom: input.generatedFrom,
      generatedAt: input.generatedAt,
      review,
    }),
  };
}

function isPlainJsonObject(value: unknown): value is Record<string, any> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function isStringList(value: unknown): value is string[] {
  return Array.isArray(value) && value.every(item => typeof item === 'string');
}

function hasOnlyFields(value: Record<string, any>, allowed: Set<string>): boolean {
  return Object.keys(value).every(field => allowed.has(field));
}

function comparablePath(value: string): string {
  const normalized = path.normalize(path.resolve(value));
  return process.platform === 'win32' ? normalized.toLocaleLowerCase('en-US') : normalized;
}

/**
 * Classify by the trusted storage boundary, not by attacker-editable manifest
 * flags. A damaged or stripped manifest inside this directory must still take
 * the generated-draft approval path and fail closed during strict validation.
 */
export function isGeneratedSkillDraftLocation(directory: string): boolean {
  const requested = path.resolve(String(directory || '').trim());
  const draftsRoot = path.resolve(SKILL_DRAFTS_DIR);
  if (comparablePath(path.dirname(requested)) === comparablePath(draftsRoot)) return true;
  try {
    const resolvedDraft = fs.realpathSync(requested);
    const resolvedRoot = fs.realpathSync(draftsRoot);
    return comparablePath(path.dirname(resolvedDraft)) === comparablePath(resolvedRoot);
  } catch {
    return false;
  }
}

function validateGeneratedDraftBoundary(directory: string): string[] {
  const errors: string[] = [];
  const requested = path.resolve(String(directory || '').trim());
  const draftsRoot = path.resolve(SKILL_DRAFTS_DIR);
  let resolvedRoot = '';
  let resolvedDraft = '';
  try {
    const rootMetadata = fs.lstatSync(draftsRoot);
    if (!rootMetadata.isDirectory() || rootMetadata.isSymbolicLink()) {
      return ['The formal generated-skill drafts root must be a real directory.'];
    }
    resolvedRoot = fs.realpathSync(draftsRoot);
    const draftMetadata = fs.lstatSync(requested);
    if (!draftMetadata.isDirectory() || draftMetadata.isSymbolicLink()) {
      return ['The generated skill draft root cannot be a symbolic link or junction.'];
    }
    resolvedDraft = fs.realpathSync(requested);
  } catch {
    return ['The generated skill draft root is missing or inaccessible.'];
  }

  const relative = path.relative(resolvedRoot, resolvedDraft);
  if (
    !relative
    || relative.startsWith('..')
    || path.isAbsolute(relative)
    || relative.includes(path.sep)
  ) {
    errors.push('Generated skill drafts must be direct children of the formal skill-drafts directory.');
    return errors;
  }

  let entries: fs.Dirent[] = [];
  try {
    entries = fs.readdirSync(resolvedDraft, { withFileTypes: true });
  } catch {
    return ['The generated skill draft directory cannot be read.'];
  }
  const entryNames = new Set(entries.map(entry => entry.name));
  for (const required of GENERATED_SKILL_REQUIRED_FILES) {
    if (!entryNames.has(required)) {
      errors.push(`Generated skill artifact is missing: ${required}.`);
    }
  }
  for (const entry of entries) {
    if (!GENERATED_SKILL_TOP_LEVEL_ENTRIES.has(entry.name)) {
      errors.push(`Generated skill draft contains an unsupported top-level entry: ${entry.name}.`);
      continue;
    }
    const entryPath = path.join(resolvedDraft, entry.name);
    try {
      const metadata = fs.lstatSync(entryPath);
      if (metadata.isSymbolicLink()) {
        errors.push(`Generated skill artifact cannot be a symbolic link or junction: ${entry.name}.`);
      } else if (entry.name === 'node_modules') {
        if (!metadata.isDirectory()) {
          errors.push('Generated skill node_modules must be a real directory when present.');
        }
      } else if (!metadata.isFile()) {
        errors.push(`Generated skill artifact must be a regular file: ${entry.name}.`);
      }
    } catch {
      errors.push(`Generated skill artifact is inaccessible: ${entry.name}.`);
    }
  }
  return errors;
}

function validateGeneratedDraftManifest(
  directory: string,
  expectedSkillName: string,
): { manifestSource: string; lockfileSource: string; errors: string[] } {
  const errors: string[] = [];
  const manifestPath = path.join(directory, 'package.json');
  const lockfilePath = path.join(directory, 'package-lock.json');

  let manifestSource = '';
  let manifest: Record<string, any> | null = null;
  try {
    manifestSource = fs.readFileSync(manifestPath, 'utf8');
    const parsed = JSON.parse(manifestSource);
    if (!isPlainJsonObject(parsed)) throw new Error('manifest must be an object');
    manifest = parsed;
  } catch {
    errors.push('The generated draft package manifest is invalid.');
    return { manifestSource, lockfileSource: '', errors };
  }

  const unexpectedFields = Object.keys(manifest)
    .filter(field => !GENERATED_SKILL_TOP_LEVEL_FIELDS.has(field));
  if (unexpectedFields.length > 0) {
    errors.push(`Generated draft manifest contains unsupported executable fields: ${unexpectedFields.join(', ')}.`);
  }
  if (manifest.name !== `lumi-skill-${expectedSkillName}`) {
    errors.push('Generated draft package name no longer matches the reviewed skill.');
  }
  if (manifest.version !== '1.0.0' || manifest.type !== 'module' || manifest.main !== 'index.ts') {
    errors.push('Generated draft entrypoint metadata no longer matches the reviewed template.');
  }
  if (typeof manifest.description !== 'string') {
    errors.push('Generated draft description must be a string.');
  }
  const scripts = isPlainJsonObject(manifest.scripts) ? manifest.scripts : {};
  if (
    Object.keys(scripts).length !== 1
    || scripts.start !== 'npx --no-install tsx index.ts'
  ) {
    errors.push('Generated draft lifecycle scripts changed after review.');
  }
  const dependencies = isPlainJsonObject(manifest.dependencies)
    ? manifest.dependencies
    : {};
  if (canonicalJson(dependencies) !== canonicalJson(GENERATED_SKILL_DEPENDENCIES)) {
    errors.push('Generated draft dependencies changed after review.');
  }
  const lumi = isPlainJsonObject(manifest.lumi) ? manifest.lumi : {};
  const unexpectedLumiFields = Object.keys(lumi)
    .filter(field => !GENERATED_SKILL_LUMI_FIELDS.has(field));
  if (unexpectedLumiFields.length > 0) {
    errors.push(`Generated draft lumi metadata contains unsupported fields: ${unexpectedLumiFields.join(', ')}.`);
  }
  if (
    lumi.autoGenerated !== true
    || lumi.status !== 'draft'
    || lumi.skillName !== expectedSkillName
    || lumi.toolCount !== 1
    || typeof lumi.generatedFrom !== 'string'
    || typeof lumi.installedAt !== 'string'
  ) {
    errors.push('Generated draft identity metadata no longer matches the reviewed skill.');
  }
  const review = isPlainJsonObject(lumi.draftReview) ? lumi.draftReview : {};
  const unexpectedReviewFields = Object.keys(review)
    .filter(field => !GENERATED_SKILL_REVIEW_FIELDS.has(field));
  if (unexpectedReviewFields.length > 0) {
    errors.push(`Generated draft review contains unsupported fields: ${unexpectedReviewFields.join(', ')}.`);
  }
  const evidence = isPlainJsonObject(review.evidence) ? review.evidence : {};
  const staticCheck = isPlainJsonObject(review.staticCheck) ? review.staticCheck : {};
  const trialRun = isPlainJsonObject(review.trialRun) ? review.trialRun : {};
  if (
    review.status !== 'draft'
    || typeof review.generatedAt !== 'string'
    || review.generatedAt !== lumi.installedAt
    || review.requiresUserApproval !== true
    || !/^[a-f0-9]{64}$/i.test(String(review.contentHash || ''))
    || !isStringList(review.permissions)
    || !isStringList(review.sideEffects)
    || !['low', 'medium', 'high'].includes(String(review.risk || ''))
    || !hasOnlyFields(evidence, GENERATED_SKILL_EVIDENCE_FIELDS)
    || evidence.kind !== 'protocol_structure_validation'
    || evidence.assurance !== 'non_executing'
    || !isStringList(evidence.limitations)
    || !hasOnlyFields(staticCheck, GENERATED_SKILL_STATIC_CHECK_FIELDS)
    || typeof staticCheck.passed !== 'boolean'
    || !isStringList(staticCheck.findings)
    || !hasOnlyFields(trialRun, GENERATED_SKILL_TRIAL_RUN_FIELDS)
    || typeof trialRun.passed !== 'boolean'
    || typeof trialRun.note !== 'string'
  ) {
    errors.push('Generated draft review metadata is incomplete or invalid.');
  }

  let lockfileSource = '';
  try {
    lockfileSource = fs.readFileSync(lockfilePath, 'utf8');
    const parsedLock = JSON.parse(lockfileSource);
    if (!isPlainJsonObject(parsedLock)) throw new Error('lockfile must be an object');
    const rootPackage = isPlainJsonObject(parsedLock.packages?.[''])
      ? parsedLock.packages['']
      : null;
    if (
      ![2, 3].includes(Number(parsedLock.lockfileVersion))
      || parsedLock.name !== manifest.name
      || parsedLock.version !== manifest.version
      || !rootPackage
      || rootPackage.name !== manifest.name
      || rootPackage.version !== manifest.version
      || canonicalJson(rootPackage.dependencies || {}) !== canonicalJson(GENERATED_SKILL_DEPENDENCIES)
    ) {
      errors.push('The generated draft dependency lockfile does not match package.json.');
    }
  } catch {
    lockfileSource = '';
    errors.push('The generated draft dependency lockfile is missing or invalid.');
  }
  return { manifestSource, lockfileSource, errors };
}

function buildDraftPackageJson(input: {
  skillName: string;
  toolDescription: string;
  generatedFrom: string;
  generatedAt: string;
  review: GeneratedSkillDraftReview;
}): string {
  return PACKAGE_TEMPLATE
    .replace(/{skillName}/g, input.skillName)
    .replace(/{toolDescription}/g, escapeJsonString(input.toolDescription))
    .replace(/{generatedFrom}/g, escapeJsonString(input.generatedFrom))
    .replace(/{installedAt}/g, input.generatedAt)
    .replace('{draftReview}', JSON.stringify(input.review));
}

function allocateDraftDirectory(skillName: string, generatedAt: string): string {
  const suffix = generatedAt.replace(/[:.]/g, '-');
  const preferred = path.join(SKILL_DRAFTS_DIR, `${skillName}-${suffix}`);
  if (!fs.existsSync(preferred)) return preferred;
  for (let index = 2; index < 10_000; index += 1) {
    const candidate = `${preferred}-${index}`;
    if (!fs.existsSync(candidate)) return candidate;
  }
  throw new Error(`Unable to allocate a draft directory for "${skillName}".`);
}

export function readGeneratedSkillDraft(directory: string): {
  skillName: string;
  review: GeneratedSkillDraftReview;
} | null {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(directory, 'package.json'), 'utf8'));
    if (pkg?.lumi?.autoGenerated !== true || pkg?.lumi?.status !== 'draft') return null;
    const skillName = String(pkg?.lumi?.skillName || '').trim();
    const review = pkg?.lumi?.draftReview as GeneratedSkillDraftReview;
    if (!skillName || !review || review.status !== 'draft') return null;
    return { skillName, review };
  } catch {
    return null;
  }
}

function createGeneratedDraftValidationSnapshot(input: {
  manifestSource: string;
  lockfileSource: string;
  source: string;
  readmeSource: string;
}): string {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'lumi-skill-validated-'));
  try {
    fs.writeFileSync(path.join(directory, 'package.json'), input.manifestSource, 'utf8');
    fs.writeFileSync(path.join(directory, 'package-lock.json'), input.lockfileSource, 'utf8');
    fs.writeFileSync(path.join(directory, 'index.ts'), input.source, 'utf8');
    fs.writeFileSync(path.join(directory, 'README.md'), input.readmeSource, 'utf8');
    return directory;
  } catch (error) {
    fs.rmSync(directory, { recursive: true, force: true });
    throw error;
  }
}

function snapshotArtifactStillMatches(input: {
  directory: string;
  expectedHash: string;
  expectedReadmeSource: string;
}): boolean {
  try {
    const entries = fs.readdirSync(input.directory, { withFileTypes: true });
    if (entries.some(entry => !GENERATED_SKILL_TOP_LEVEL_ENTRIES.has(entry.name))) return false;
    for (const entry of entries) {
      const metadata = fs.lstatSync(path.join(input.directory, entry.name));
      if (metadata.isSymbolicLink()) return false;
      if (entry.name === 'node_modules' ? !metadata.isDirectory() : !metadata.isFile()) return false;
    }
    return computeGeneratedSkillArtifactHash(
      fs.readFileSync(path.join(input.directory, 'index.ts'), 'utf8'),
      fs.readFileSync(path.join(input.directory, 'package.json'), 'utf8'),
      fs.readFileSync(path.join(input.directory, 'package-lock.json'), 'utf8'),
    ) === input.expectedHash
      && fs.readFileSync(path.join(input.directory, 'README.md'), 'utf8') === input.expectedReadmeSource;
  } catch {
    return false;
  }
}

export async function validateGeneratedSkillDraftForInstall(directory: string): Promise<{
  valid: boolean;
  skillName?: string;
  review?: GeneratedSkillDraftReview;
  /** Clean validated snapshot; the caller must install it immediately, then remove it. */
  validatedDirectory?: string;
  errors: string[];
}> {
  const boundaryErrors = validateGeneratedDraftBoundary(directory);
  if (boundaryErrors.length > 0) return { valid: false, errors: boundaryErrors };
  const draft = readGeneratedSkillDraft(directory);
  if (!draft) return { valid: false, errors: ['The directory is not a generated Lumi skill draft.'] };
  const indexPath = path.join(directory, 'index.ts');
  const manifestValidation = validateGeneratedDraftManifest(directory, draft.skillName);
  if (manifestValidation.errors.length > 0) {
    return {
      valid: false,
      skillName: draft.skillName,
      review: draft.review,
      errors: manifestValidation.errors,
    };
  }
  let source = '';
  let readmeSource = '';
  try {
    source = fs.readFileSync(indexPath, 'utf8');
    readmeSource = fs.readFileSync(path.join(directory, 'README.md'), 'utf8');
  } catch {
    return {
      valid: false,
      skillName: draft.skillName,
      review: draft.review,
      errors: ['The generated draft source artifacts could not be read.'],
    };
  }
  const current = buildGeneratedSkillDraftReview({
    source,
    manifestSource: manifestValidation.manifestSource,
    lockfileSource: manifestValidation.lockfileSource,
    generatedAt: draft.review.generatedAt,
    declaredPermissions: draft.review.permissions,
    declaredSideEffects: draft.review.sideEffects,
    declaredRisk: draft.review.risk,
    // A generated draft has two legitimate reviewed states: the pre-trial
    // package and the final package whose successful trial is itself hashed.
    // Re-validating the latter must reconstruct the same review state before
    // running a fresh trial, otherwise an install-ready draft is spuriously
    // reported as changed after review.
    validationPassed: draft.review.trialRun.passed === true,
  });
  const errors = Array.from(new Set([
    ...current.staticCheck.findings,
    ...validateGeneratedSkillProtocolStructure(source),
  ]));
  const reviewedStaticFacts = {
    permissions: draft.review.permissions,
    sideEffects: draft.review.sideEffects,
    risk: draft.review.risk,
    evidence: draft.review.evidence,
    staticCheck: draft.review.staticCheck,
  };
  const inspectedStaticFacts = {
    permissions: current.permissions,
    sideEffects: current.sideEffects,
    risk: current.risk,
    evidence: current.evidence,
    staticCheck: current.staticCheck,
  };
  if (canonicalJson(reviewedStaticFacts) !== canonicalJson(inspectedStaticFacts)) {
    errors.push('The generated draft review no longer matches the static inspection of its source.');
  }
  if (current.contentHash !== draft.review.contentHash) {
    errors.push('The generated draft changed after review; generate or review it again before installation.');
  }
  if (errors.length > 0) {
    return {
      valid: false,
      skillName: draft.skillName,
      review: current,
      errors,
    };
  }

  let validatedDirectory = '';
  let protocolValidationPassed = false;
  try {
    validatedDirectory = createGeneratedDraftValidationSnapshot({
      manifestSource: manifestValidation.manifestSource,
      lockfileSource: manifestValidation.lockfileSource,
      source,
      readmeSource,
    });
    await installLockedSkillDeps(validatedDirectory);
    if (!snapshotArtifactStillMatches({
      directory: validatedDirectory,
      expectedHash: draft.review.contentHash,
      expectedReadmeSource: readmeSource,
    })) {
      errors.push('The clean generated-skill validation snapshot changed during dependency preparation.');
    }
    protocolValidationPassed = errors.length === 0;
    if (errors.length === 0) {
      // The returned snapshot is the immutable, reviewed four-file artifact.
      // Dependencies are reproduced from its lock in the caller's private
      // install staging directory. Keeping node_modules here both bloats the
      // copy and carries platform-specific .bin symlinks across filesystems.
      fs.rmSync(path.join(validatedDirectory, 'node_modules'), { recursive: true, force: true });
      if (!snapshotArtifactStillMatches({
        directory: validatedDirectory,
        expectedHash: draft.review.contentHash,
        expectedReadmeSource: readmeSource,
      })) {
        errors.push('The clean generated-skill artifact could not be sealed after protocol validation.');
      }
    }
  } catch (error: any) {
    errors.push(`Dependency snapshot preparation failed: ${error?.message || String(error)}`);
  }

  if (errors.length > 0 && validatedDirectory) {
    try { fs.rmSync(validatedDirectory, { recursive: true, force: true }); } catch {}
    validatedDirectory = '';
  }

  return {
    valid: errors.length === 0,
    skillName: draft.skillName,
    ...(validatedDirectory ? { validatedDirectory } : {}),
    review: errors.length === 0 && draft.review.trialRun.passed
      // A final, approved draft must retain the exact hash-bound review. A
      // fresh non-executing validation must not rewrite that evidence while
      // keeping the old contentHash.
      ? draft.review
      : {
          ...current,
          trialRun: {
            passed: protocolValidationPassed,
            note: protocolValidationPassed
              ? 'The non-executing protocol structure and locked dependency validation passed.'
              : 'The non-executing protocol structure or locked dependency validation failed.',
          },
        },
    errors,
  };
}

// ── Validation ──

function runDependencyCommand(command: string, skillDir: string): Promise<void> {
  return new Promise((resolve, reject) => {
    exec(command, {
      timeout: 120000,
      maxBuffer: 512 * 1024,
      cwd: skillDir,
    }, (error, _stdout, stderr) => {
      if (error) {
        reject(new Error(stderr.trim() || error.message));
      } else {
        resolve();
      }
    });
  });
}

/** Resolve the generated template once without executing package scripts. */
async function createSkillDependencyLock(skillDir: string): Promise<void> {
  await runDependencyCommand(
    'npm install --package-lock-only --ignore-scripts --loglevel=error --no-audit --no-fund',
    skillDir,
  );
  if (!fs.existsSync(path.join(skillDir, 'package-lock.json'))) {
    throw new Error('npm did not produce the required generated-skill dependency lockfile');
  }
}

/** Reproduce exactly the reviewed lock in an isolated validation snapshot. */
async function installLockedSkillDeps(skillDir: string): Promise<void> {
  await runDependencyCommand(
    'npm ci --ignore-scripts --loglevel=error --no-audit --no-fund',
    skillDir,
  );
}

// ── Helpers ──

function topTools(steps: WorkflowStep[]): { name: string; count: number }[] {
  const counts: Record<string, number> = {};
  for (const s of steps) {
    counts[s.name] = (counts[s.name] || 0) + 1;
  }
  return Object.entries(counts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([name, count]) => ({ name, count }));
}

function buildHandlerFunction(handlerCode: string, inputSchema: any): string {
  const props = inputSchema?.properties || {};
  const paramNames = Object.keys(props);

  const destructure = paramNames.length > 0
    ? `  const { ${paramNames.join(', ')} } = args;`
    : '  // No parameters defined';

  // Indent the LLM-generated body code to match the function body
  const sanitizedBody = sanitizeHandlerBody(handlerCode, paramNames);

  const indentedBody = sanitizedBody
    .split('\n')
    .map(line => line.trim() ? `  ${line}` : '')
    .join('\n');

  return `async (args: Record<string, any>): Promise<{ content: Array<{ type: 'text'; text: string }> }> => {
${destructure}
  let result = '';

  // ── Generated implementation ──
${indentedBody}

  return {
    content: [{ type: 'text', text: result }],
  };
}`;
}

function sanitizeHandlerBody(handlerCode: string, paramNames: string[]): string {
  const duplicateDestructure = paramNames.length
    ? new RegExp(`^\\s*const\\s*\\{\\s*${paramNames.map(escapeRegExp).join('\\s*,\\s*')}\\s*\\}\\s*=\\s*args\\s*;\\s*$`)
    : null;

  return String(handlerCode || '')
    .replace(/^```(?:ts|typescript|js|javascript)?\s*/i, '')
    .replace(/```\s*$/i, '')
    .split('\n')
    .filter(line => !duplicateDestructure?.test(line))
    .map(line => {
      const trimmed = line.trim();
      if (/^return\s+result\s*;?$/.test(trimmed)) return '';
      const valueReturn = trimmed.match(/^return\s+(.+);$/);
      if (valueReturn && !trimmed.includes('content:')) {
        const indent = line.match(/^\s*/)?.[0] || '';
        return `${indent}result = String(${valueReturn[1]});\n${indent}return { content: [{ type: 'text', text: result }] };`;
      }
      return line;
    })
    .join('\n')
    .trim();
}

function buildSchemaLiteral(schema: any): string {
  if (!schema || !schema.properties) {
    return 'z.object({})';
  }

  const props = schema.properties || {};

  const propEntries = Object.entries(props).map(([key, prop]: [string, any]) => {
    return `  ${JSON.stringify(key)}: ${mapJsonTypeToZod(prop)}${prop.description ? `.describe('${escapeTsSingleQuoted(prop.description)}')` : ''}`;
  });

  if (propEntries.length === 0) {
    return `z.object({})`;
  }

  return `z.object({\n${propEntries.join(',\n')}\n})`;
}

function mapJsonTypeToZod(prop: any): string {
  const jsonType = prop?.type || 'string';
  switch (jsonType) {
    case 'string': return 'z.string()';
    case 'number': return 'z.number()';
    case 'integer': return 'z.number()';
    case 'boolean': return 'z.boolean()';
    case 'array': return 'z.array(z.any())';
    case 'object': return 'z.record(z.any())';
    default: return 'z.string()';
  }
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function escapeTsSingleQuoted(value: string): string {
  return String(value || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function escapeJsonString(value: string): string {
  return String(value || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
