/**
 * Lumi Skill Management Tools — generate, list, and install MCP skills.
 *
 * These tools let the LLM agent create new reusable tools from natural language
 * descriptions, inspect existing skills, and install skill packages from disk.
 */
import fs from 'fs';
import path from 'path';
import { ToolRegistry } from '../registry';
import {
  generateSkill,
  readGeneratedSkillDraft,
  validateGeneratedSkillDraftForInstall,
} from '../../skills/generator';
import { mcpManager } from '../../mcp/client';
import type { ToolContext } from '../types';
import { capabilityContract, capabilityEvidence } from '../capability_contracts';

// Module-level LLM getters, set during registration
let _llmGetters: {
  getDeepSeek: () => any;
  getGemini: () => any;
  getOpenAI?: () => any;
  getAnthropic?: () => any;
  getQwen?: () => any;
  getOllama?: () => any;
  getLmStudio?: () => any;
  getArk?: () => any;
  getXiaomi?: () => any;
  getKimi?: () => any;
  getGlm?: () => any;
  getRelay?: () => any;
} | null = null;

export function setSkillLLMGetters(getters: typeof _llmGetters): void {
  _llmGetters = getters;
}

function hostSkillMutationBlocked(context?: ToolContext): string | null {
  if (context?.domain === 'work' || context?.orgId) {
    return 'Host-level skill changes are not performed from an organization workspace. A local system administrator can install or generate the skill in desktop settings; the organization workspace can then use the approved capability.';
  }
  return null;
}

async function generateSkillHandler(args: Record<string, any>, context?: ToolContext): Promise<string> {
  const blocked = hostSkillMutationBlocked(context);
  if (blocked) throw new Error(blocked);
  if (!_llmGetters) {
    throw new Error('Skill generation is unavailable because LLM providers have not finished initializing.');
  }

  const description = String(args.description || '').trim();
  if (!description) {
    throw new Error('A specific skill description is required.');
  }

  const result = await generateSkill(
    {
      description,
      ...(args.provider ? { provider: args.provider as any } : {}),
      ...(args.model ? { model: String(args.model) } : {}),
      userId: context?.userId || 'skill_gen',
    },
    _llmGetters.getDeepSeek,
    _llmGetters.getGemini,
    _llmGetters.getOpenAI,
    _llmGetters.getAnthropic,
    _llmGetters.getQwen,
    _llmGetters.getOllama,
    _llmGetters.getLmStudio,
    _llmGetters.getArk,
    _llmGetters.getXiaomi,
    _llmGetters.getKimi,
    _llmGetters.getGlm,
    _llmGetters.getRelay,
  );

  if (!result.success) {
    throw new Error(`Skill generation failed: ${result.error || 'Unknown error'}`);
  }
  const draftDirectory = String(result.directory || '');
  const manifestPath = path.join(draftDirectory, 'package.json');
  const entryPath = path.join(draftDirectory, 'index.ts');
  if (
    !draftDirectory
    || !result.review?.staticCheck.passed
    || !result.review?.trialRun.passed
    || !fs.existsSync(manifestPath)
    || !fs.existsSync(entryPath)
  ) {
    throw new Error('Skill generation returned without a complete reviewed draft artifact.');
  }
  return JSON.stringify({
    ok: true,
    status: 'draft',
    executable: false,
    installed: false,
    skillName: result.skillName,
    toolName: result.toolName,
    draftDirectory,
    manifestPath,
    entryPath,
    review: result.review,
    warnings: result.error ? [result.error] : [],
  });
}

async function listSkillsHandler(): Promise<string> {
  try {
    const skills = mcpManager.listLocalSkills();
    if (skills.length === 0) {
      return 'No locally installed skills found in ~/lumi_skills/. Generate one with the generate_skill tool.';
    }

    const lines = skills.map(s => {
      const autoBadge = s.autoGenerated ? '[auto]' : '[manual]';
      return `- **${s.name}** ${autoBadge}: ${s.description} (${s.toolCount} tool(s), installed ${s.installedAt.slice(0, 10)})`;
    });

    return `Installed skills (${skills.length} total):\n\n${lines.join('\n')}`;
  } catch (err: any) {
    throw new Error(`Skill listing failed: ${err.message || String(err)}`);
  }
}

async function installSkillHandler(args: Record<string, any>, context?: ToolContext): Promise<string> {
  const blocked = hostSkillMutationBlocked(context);
  if (blocked) throw new Error(blocked);
  const dir = String(args.directory || '').trim();
  if (!dir) {
    throw new Error('An absolute skill source directory is required.');
  }

  try {
    const generatedDraft = readGeneratedSkillDraft(dir);
    if (generatedDraft && context?.userConfirmed !== true) {
      throw new Error('Generated skill installation requires approval of its reviewed permissions, risk, side effects, and trial result.');
    }
    const validation = generatedDraft
      ? await validateGeneratedSkillDraftForInstall(dir)
      : null;
    if (validation && !validation.valid) {
      throw new Error(`Generated skill draft validation failed: ${validation.errors.join(' | ')}`);
    }
    const name = String(args.name || '').trim()
      || validation?.skillName
      || dir.split(/[/\\]/).pop()
      || 'unknown';
    const destDir = await mcpManager.installSkillValidated(
      name,
      dir,
      validation?.review
        ? {
            approvedGeneratedDraft: {
              approvedAt: new Date().toISOString(),
              review: validation.review as unknown as Record<string, unknown>,
            },
          }
        : undefined,
    );
    const manifestPath = path.join(destDir, 'package.json');
    if (!fs.existsSync(manifestPath) || fs.statSync(manifestPath).size === 0) {
      throw new Error('Skill installer returned without a non-empty installed package manifest.');
    }
    return JSON.stringify({
      ok: true,
      status: 'installed',
      skillName: name,
      installDirectory: destDir,
      manifestPath,
      runtimeStatus: 'restart_required',
      generatedDraft: Boolean(generatedDraft),
    });
  } catch (err: any) {
    throw new Error(`Skill installation failed: ${err.message || String(err)}`);
    return `Install failed: ${err.message}. The skill may already be installed — check with list_skills.`;
  }
}

export function registerSkillTools(registry: ToolRegistry): void {
  registry.register({
    name: 'generate_skill',
    description:
      'Generate an isolated, non-executable MCP skill draft from an explicit user request. ' +
      'The draft receives static analysis, a permission/side-effect declaration, type validation, and an isolated startup trial. ' +
      'It is never scanned or installed automatically; install_skill requires a separate explicit approval.',
    parameters: {
      type: 'object',
      properties: {
        description: {
          type: 'string',
          description:
            'Natural language description of what the skill should do. Be specific: describe the inputs, the processing logic, error handling, and expected output format.',
        },
        provider: {
          type: 'string',
          description: 'LLM provider to use for code generation. Default: deepseek.',
          enum: ['deepseek', 'qwen', 'openai', 'gemini', 'anthropic'],
        },
        model: {
          type: 'string',
          description: 'Specific model name. Default: inherit the current user selection.',
        },
      },
      required: ['description'],
    },
    handler: (args, context) => generateSkillHandler(args, context),
    permission: 'user',
    securityLevel: 'confirm',
    capability: capabilityContract({
      id: 'skills.draft.generate',
      family: 'skill-lifecycle',
      lane: 'system',
      operation: 'create',
      risk: 'high',
      sideEffects: [
        { type: 'external_state_change', scope: 'configured LLM generation request', reversible: false },
        { type: 'local_write', scope: 'isolated non-executable skill draft in user data', reversible: true },
        { type: 'process_execution', scope: 'isolated static/type/startup validation trial', reversible: false },
      ],
      verification: {
        strategy: 'artifact',
        required: true,
        requiredFields: ['ok', 'status', 'executable', 'installed', 'skillName', 'toolName', 'draftDirectory', 'manifestPath', 'entryPath', 'review'],
        requiredValues: {
          ok: true,
          status: 'draft',
          executable: false,
          installed: false,
          'review.status': 'draft',
          'review.staticCheck.passed': true,
          'review.trialRun.passed': true,
          'review.requiresUserApproval': true,
        },
        successStatuses: ['draft'],
        failureStatuses: ['failed', 'installed'],
        requiredArtifacts: ['manifestPath', 'entryPath'],
        successSignals: ['reviewed draft artifacts exist only in the isolated draft directory'],
        limitations: ['Draft validation does not authorize installation or prove production safety.'],
      },
    }),
    evidence: capabilityEvidence({
      id: 'skills.draft.generate',
      operation: 'create',
      subjectArgument: 'description',
      limitations: ['The generated result is intentionally non-executable and requires a separate reviewed installation.'],
    }),
  });

  registry.register({
    name: 'list_skills',
    description:
      'List all locally installed MCP skills in ~/lumi_skills/. ' +
      'Shows skill name, description, tool count, and whether it was auto-generated. ' +
      'Use before generating new skills to check for duplicates.',
    parameters: {
      type: 'object',
      properties: {},
      required: [],
    },
    handler: listSkillsHandler,
    permission: 'public',
    securityLevel: 'safe',
  });

  registry.register({
    name: 'install_skill',
    description:
      'Validate and install an MCP skill from a local directory into ~/lumi_skills/. ' +
      'Generated Lumi drafts are rechecked for source integrity, declared permissions, static safety, type correctness, and an isolated startup trial, then require explicit user confirmation.',
    parameters: {
      type: 'object',
      properties: {
        directory: {
          type: 'string',
          description: 'Absolute path to the skill directory containing index.ts and package.json.',
        },
        name: {
          type: 'string',
          description: 'Skill name. Defaults to the directory basename.',
        },
      },
      required: ['directory'],
    },
    handler: (args, context) => installSkillHandler(args, context),
    permission: 'user',
    securityLevel: 'confirm',
    capability: capabilityContract({
      id: 'skills.package.install',
      family: 'skill-lifecycle',
      lane: 'system',
      operation: 'mutate',
      risk: 'high',
      sideEffects: [
        { type: 'installation', scope: 'user-maintained Lumi skills directory', reversible: true },
        { type: 'local_state_change', scope: 'MCP skill runtime configuration', reversible: true },
        { type: 'process_execution', scope: 'dependency preparation and skill validation', reversible: false },
        { type: 'network_read', scope: 'package registries required by declared dependencies', reversible: true },
      ],
      verification: {
        strategy: 'artifact',
        required: true,
        requiredFields: ['ok', 'status', 'skillName', 'installDirectory', 'manifestPath', 'runtimeStatus'],
        requiredValues: { ok: true, status: 'installed', runtimeStatus: 'restart_required' },
        successStatuses: ['installed'],
        failureStatuses: ['failed', 'blocked'],
        requiredArtifacts: ['manifestPath'],
        successSignals: ['installed package manifest exists and runtime restart requirement is explicit'],
        limitations: ['Installation does not prove the skill has connected or completed a real task.'],
      },
    }),
    evidence: capabilityEvidence({
      id: 'skills.package.install',
      operation: 'mutate',
      subjectArgument: 'directory',
      limitations: ['Runtime availability requires a later MCP reconnect/startup receipt.'],
    }),
  });
}
