import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

export interface ManagedSkillIdentity {
  origin: 'bundled' | 'generated';
  skillId: string;
  packageName: string;
  packageVersion: string;
  contentDigest: string;
  reviewHash?: string;
  runtime?: ManagedSkillRuntimeIdentity;
  signature?: string;
}

export interface ManagedRuntimeFileIdentity {
  path: string;
  kind: 'file' | 'directory';
  digest: string;
}

export interface ManagedSkillRuntimeIdentity {
  transport: 'stdio';
  command: string;
  args: string[];
  cwd: string;
  env?: Record<string, string>;
  files: ManagedRuntimeFileIdentity[];
}

export type OfficialSkillIdentityStatus = 'absent' | 'verified' | 'conflict';

export interface OfficialSkillIdentityProjection {
  identityStatus: OfficialSkillIdentityStatus;
  installed: boolean;
  conflictReason?: string;
  identity?: ManagedSkillIdentity;
}

const IGNORED_DIRECTORY_NAMES = new Set(['node_modules', '.git']);
const IGNORED_FILE_NAMES = new Set(['.lumi-pending', '.lumi-disabled']);

function stableJson(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stableJson);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.keys(value as Record<string, unknown>)
      .sort()
      .map(key => [key, stableJson((value as Record<string, unknown>)[key])]),
  );
}

function identitySignaturePayload(identity: ManagedSkillIdentity): string {
  const { signature: _signature, ...unsigned } = identity;
  return JSON.stringify(stableJson(unsigned));
}

export function signManagedSkillIdentity(
  identity: ManagedSkillIdentity,
  secret: string,
): ManagedSkillIdentity {
  const signature = crypto
    .createHmac('sha256', secret)
    .update(identitySignaturePayload(identity))
    .digest('base64url');
  return { ...identity, signature };
}

export function verifyManagedSkillIdentitySignature(
  identity: ManagedSkillIdentity | undefined,
  secret: string,
): boolean {
  if (!identity?.signature) return false;
  const expected = crypto
    .createHmac('sha256', secret)
    .update(identitySignaturePayload(identity))
    .digest();
  let supplied: Buffer;
  try { supplied = Buffer.from(identity.signature, 'base64url'); } catch { return false; }
  return supplied.length === expected.length && crypto.timingSafeEqual(supplied, expected);
}

function normalizedPackageJson(filePath: string): Buffer {
  const parsed = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  if (parsed?.lumi && typeof parsed.lumi === 'object') {
    const lumi = { ...parsed.lumi };
    delete lumi.installedAt;
    delete lumi.installedVersion;
    delete lumi.status;
    delete lumi.managedSkill;
    delete lumi.autoGenerated;
    delete lumi.generatedByLumi;
    delete lumi.approvedAt;
    delete lumi.draftReview;
    parsed.lumi = lumi;
  }
  return Buffer.from(JSON.stringify(stableJson(parsed)), 'utf8');
}

/**
 * Digest the executable package owned by the current LumiCore build. Runtime
 * dependencies and install-only metadata are deliberately excluded.
 */
export function computeSkillContentDigest(rootDirectory: string): string {
  const root = path.resolve(rootDirectory);
  if (!fs.existsSync(root) || !fs.statSync(root).isDirectory()) {
    throw new Error('Skill package directory is unavailable');
  }
  const files: string[] = [];
  const visit = (directory: string): void => {
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      if (IGNORED_DIRECTORY_NAMES.has(entry.name)) continue;
      if (entry.isSymbolicLink()) throw new Error('Skill package identity cannot include symbolic links');
      if (entry.isFile() && IGNORED_FILE_NAMES.has(entry.name)) continue;
      const target = path.join(directory, entry.name);
      if (entry.isDirectory()) visit(target);
      else if (entry.isFile()) files.push(target);
    }
  };
  visit(root);
  files.sort((left, right) => left.localeCompare(right));

  const hash = crypto.createHash('sha256');
  for (const file of files) {
    const relative = path.relative(root, file).split(path.sep).join('/');
    const content = relative === 'package.json'
      ? normalizedPackageJson(file)
      : fs.readFileSync(file);
    hash.update(relative, 'utf8');
    hash.update('\0');
    hash.update(content);
    hash.update('\0');
  }
  return `sha256:${hash.digest('hex')}`;
}

export function computeRuntimePathDigest(targetPath: string): string {
  const resolved = path.resolve(targetPath);
  if (!fs.existsSync(resolved)) throw new Error(`Managed runtime path is unavailable: ${resolved}`);
  const stat = fs.statSync(resolved);
  if (stat.isFile()) {
    return `sha256:${crypto.createHash('sha256').update(fs.readFileSync(resolved)).digest('hex')}`;
  }
  if (!stat.isDirectory()) throw new Error(`Managed runtime path is unsupported: ${resolved}`);
  const files: string[] = [];
  const visit = (directory: string): void => {
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      if (IGNORED_DIRECTORY_NAMES.has(entry.name)) continue;
      if (entry.isSymbolicLink()) throw new Error(`Managed runtime dependency contains a symbolic link: ${entry.name}`);
      const target = path.join(directory, entry.name);
      if (entry.isDirectory()) visit(target);
      else if (entry.isFile()) files.push(target);
    }
  };
  visit(resolved);
  files.sort((left, right) => left.localeCompare(right));
  const hash = crypto.createHash('sha256');
  for (const file of files) {
    hash.update(path.relative(resolved, file).split(path.sep).join('/'), 'utf8');
    hash.update('\0');
    hash.update(fs.readFileSync(file));
    hash.update('\0');
  }
  return `sha256:${hash.digest('hex')}`;
}

export function createManagedSkillRuntimeIdentity(input: {
  command: string;
  args: string[];
  cwd: string;
  env?: Record<string, string>;
  files: string[];
}): ManagedSkillRuntimeIdentity {
  const command = path.resolve(input.command);
  const args = input.args.map(value => path.isAbsolute(value) ? path.resolve(value) : value);
  const cwd = path.resolve(input.cwd);
  const files = Array.from(new Set(input.files.map(value => path.resolve(value))))
    .sort((left, right) => left.localeCompare(right))
    .map(file => ({
      path: file,
      kind: fs.statSync(file).isDirectory() ? 'directory' as const : 'file' as const,
      digest: computeRuntimePathDigest(file),
    }));
  const env = input.env && Object.keys(input.env).length > 0
    ? Object.fromEntries(Object.entries(input.env).sort(([left], [right]) => left.localeCompare(right)))
    : undefined;
  return { transport: 'stdio', command, args, cwd, env, files };
}

export function verifyManagedSkillRuntimeIdentity(
  runtime: ManagedSkillRuntimeIdentity | undefined,
): { valid: true } | { valid: false; reason: string } {
  if (!runtime || runtime.transport !== 'stdio') {
    return { valid: false, reason: 'Managed Skill runtime identity is missing.' };
  }
  if (!path.isAbsolute(runtime.command) || !path.isAbsolute(runtime.cwd)) {
    return { valid: false, reason: 'Managed Skill command and working directory must be absolute.' };
  }
  if (!Array.isArray(runtime.args) || !Array.isArray(runtime.files) || runtime.files.length < 2) {
    return { valid: false, reason: 'Managed Skill runtime files are not fully bound.' };
  }
  if (
    runtime.env !== undefined
    && (
      !runtime.env
      || typeof runtime.env !== 'object'
      || Array.isArray(runtime.env)
      || Object.entries(runtime.env).some(([key, value]) => !key || typeof value !== 'string')
    )
  ) {
    return { valid: false, reason: 'Managed Skill runtime environment is invalid.' };
  }
  for (const file of runtime.files) {
    try {
      const kind = fs.existsSync(file.path) && fs.statSync(file.path).isDirectory() ? 'directory' : 'file';
      if (
        !path.isAbsolute(file.path)
        || file.kind !== kind
        || computeRuntimePathDigest(file.path) !== file.digest
      ) {
        return { valid: false, reason: `Managed Skill runtime file changed: ${file.path}` };
      }
    } catch (error: any) {
      return { valid: false, reason: error?.message || `Managed Skill runtime file changed: ${file.path}` };
    }
  }
  return { valid: true };
}

export function createGeneratedSkillIdentity(
  skillName: string,
  sourceDirectory: string,
  reviewHash: string,
): ManagedSkillIdentity {
  const pkg = readPackage(sourceDirectory);
  const packageName = String(pkg?.name || skillName).trim();
  const packageVersion = String(pkg?.version || '1.0.0').trim();
  const normalizedReviewHash = String(reviewHash || '').trim();
  if (!packageName || !packageVersion || !normalizedReviewHash) {
    throw new Error('Generated Skill identity is incomplete');
  }
  return {
    origin: 'generated',
    skillId: `generated-${skillName}`,
    packageName,
    packageVersion,
    contentDigest: computeSkillContentDigest(sourceDirectory),
    reviewHash: normalizedReviewHash,
  };
}

function readPackage(directory: string): Record<string, any> | undefined {
  try {
    const parsed = JSON.parse(fs.readFileSync(path.join(directory, 'package.json'), 'utf8'));
    return parsed && typeof parsed === 'object' ? parsed : undefined;
  } catch {
    return undefined;
  }
}

export function createBundledSkillIdentity(
  skillId: string,
  sourceDirectory: string,
): ManagedSkillIdentity {
  const pkg = readPackage(sourceDirectory);
  const packageName = String(pkg?.name || '').trim();
  const packageVersion = String(pkg?.version || '').trim();
  if (!packageName || !packageVersion) {
    throw new Error('Official bundled skill package must declare name and version');
  }
  return {
    origin: 'bundled',
    skillId: String(skillId || '').trim(),
    packageName,
    packageVersion,
    contentDigest: computeSkillContentDigest(sourceDirectory),
  };
}

function sameIdentity(left: unknown, right: ManagedSkillIdentity): boolean {
  if (!left || typeof left !== 'object') return false;
  const value = left as Record<string, unknown>;
  return value.origin === right.origin
    && value.skillId === right.skillId
    && value.packageName === right.packageName
    && value.packageVersion === right.packageVersion
    && value.contentDigest === right.contentDigest
    && value.reviewHash === right.reviewHash;
}

export function configTargetsInstalledPackage(
  config: Record<string, any>,
  installedDirectory: string,
  sourcePackage: Record<string, any>,
): boolean {
  if (config.source !== 'local') return false;
  const managedRuntime = config.managedSkill?.runtime as ManagedSkillRuntimeIdentity | undefined;
  if (managedRuntime) {
    return config.transport === 'stdio'
      && !config.url
      && !config.headers
      && path.resolve(String(config.command || '')) === managedRuntime.command
      && JSON.stringify(config.args || []) === JSON.stringify(managedRuntime.args)
      && path.resolve(String(config.cwd || '')) === managedRuntime.cwd
      && JSON.stringify(config.env || null) === JSON.stringify(managedRuntime.env || null)
      && managedRuntime.cwd === path.resolve(installedDirectory)
      && managedRuntime.args.includes(path.resolve(installedDirectory, 'index.ts'));
  }
  const lumi = sourcePackage.lumi || {};
  if (lumi.runCommand) {
    return config.command === lumi.runCommand
      && JSON.stringify(config.args || []) === JSON.stringify(lumi.runArgs || []);
  }
  const expectedIndex = path.join(path.resolve(installedDirectory), 'index.ts')
    .split(path.sep)
    .join('/');
  const portableIndex = `~/lumi_skills/${path.basename(path.resolve(installedDirectory))}/index.ts`;
  const variableIndex = `\${LUMI_SKILLS_DIR}/${path.basename(path.resolve(installedDirectory))}/index.ts`;
  const configuredIndex = String(config.args?.[1] || '').split('\\').join('/');
  return config.command === 'npx'
    && Array.isArray(config.args)
    && config.args.length === 2
    && config.args[0] === 'tsx'
    && [expectedIndex, portableIndex, variableIndex].includes(configuredIndex);
}

/**
 * A same-name directory is not an official installation. Both the package and
 * its executable config must carry the server-owned identity, and the copied
 * executable content must still match the bundled source.
 */
export function projectOfficialBundledIdentity(input: {
  skillId: string;
  sourceDirectory: string;
  installedDirectory: string;
  config?: Record<string, any>;
  identitySecret: string;
}): OfficialSkillIdentityProjection {
  const packagePresent = fs.existsSync(input.installedDirectory);
  const configured = Boolean(input.config);
  if (!packagePresent && !configured) return { identityStatus: 'absent', installed: false };

  let expected: ManagedSkillIdentity;
  try {
    expected = createBundledSkillIdentity(input.skillId, input.sourceDirectory);
  } catch (error: any) {
    return {
      identityStatus: 'conflict',
      installed: false,
      conflictReason: `Official source identity is invalid: ${error?.message || error}`,
    };
  }
  if (!packagePresent || !configured) {
    return {
      identityStatus: 'conflict',
      installed: false,
      identity: expected,
      conflictReason: packagePresent
        ? 'A same-name local package exists without its managed official configuration.'
        : 'A same-name configuration exists without the managed official package.',
    };
  }

  const installedPackage = readPackage(input.installedDirectory);
  const sourcePackage = readPackage(input.sourceDirectory);
  if (!installedPackage || !sourcePackage) {
    return {
      identityStatus: 'conflict', installed: false, identity: expected,
      conflictReason: 'The local or bundled package manifest is unreadable.',
    };
  }
  if (
    installedPackage.name !== expected.packageName
    || String(installedPackage.lumi?.installedVersion || installedPackage.version || '') !== expected.packageVersion
  ) {
    return {
      identityStatus: 'conflict', installed: false, identity: expected,
      conflictReason: 'The same-name local package does not match the official package name and version.',
    };
  }
  if (!sameIdentity(installedPackage.lumi?.managedSkill, expected)) {
    return {
      identityStatus: 'conflict', installed: false, identity: expected,
      conflictReason: 'The same-name local package has no matching managed official identity.',
    };
  }
  if (!sameIdentity(input.config?.managedSkill, expected)) {
    return {
      identityStatus: 'conflict', installed: false, identity: expected,
      conflictReason: 'The same-name runtime configuration is not the managed official configuration.',
    };
  }
  if (JSON.stringify(installedPackage.lumi?.managedSkill) !== JSON.stringify(input.config?.managedSkill)) {
    return {
      identityStatus: 'conflict', installed: false, identity: expected,
      conflictReason: 'The package and runtime configuration identities differ.',
    };
  }
  if (!verifyManagedSkillIdentitySignature(installedPackage.lumi?.managedSkill, input.identitySecret)) {
    return {
      identityStatus: 'conflict', installed: false, identity: expected,
      conflictReason: 'The managed Skill identity signature is invalid.',
    };
  }
  const packageRuntime = installedPackage.lumi?.managedSkill?.runtime as ManagedSkillRuntimeIdentity | undefined;
  const configRuntime = input.config?.managedSkill?.runtime as ManagedSkillRuntimeIdentity | undefined;
  if (JSON.stringify(packageRuntime || null) !== JSON.stringify(configRuntime || null)) {
    return {
      identityStatus: 'conflict', installed: false, identity: expected,
      conflictReason: 'The package and runtime configuration do not share the same execution identity.',
    };
  }
  const runtimeVerification = verifyManagedSkillRuntimeIdentity(packageRuntime);
  if (!runtimeVerification.valid) {
    return {
      identityStatus: 'conflict', installed: false, identity: expected,
      conflictReason: 'reason' in runtimeVerification
        ? runtimeVerification.reason
        : 'Managed Skill runtime identity is invalid.',
    };
  }
  if (
    input.config?.transport !== 'stdio'
    || Boolean(input.config?.url)
    || Boolean(input.config?.headers)
    || path.resolve(String(input.config?.command || '')) !== packageRuntime!.command
    || JSON.stringify(input.config?.args || []) !== JSON.stringify(packageRuntime!.args)
    || path.resolve(String(input.config?.cwd || '')) !== packageRuntime!.cwd
    || JSON.stringify(input.config?.env || null) !== JSON.stringify(packageRuntime!.env || null)
    || packageRuntime!.cwd !== path.resolve(input.installedDirectory)
    || !packageRuntime!.args.includes(path.resolve(input.installedDirectory, 'index.ts'))
  ) {
    return {
      identityStatus: 'conflict', installed: false, identity: expected,
      conflictReason: 'The runtime command, entry point, working directory, or environment differs from the managed identity.',
    };
  }
  if (!configTargetsInstalledPackage(input.config!, input.installedDirectory, sourcePackage)) {
    return {
      identityStatus: 'conflict', installed: false, identity: expected,
      conflictReason: 'The same-name runtime configuration does not target the installed official package.',
    };
  }
  try {
    if (computeSkillContentDigest(input.installedDirectory) !== expected.contentDigest) {
      return {
        identityStatus: 'conflict', installed: false, identity: expected,
        conflictReason: 'The installed package content no longer matches the official bundled package.',
      };
    }
  } catch (error: any) {
    return {
      identityStatus: 'conflict', installed: false, identity: expected,
      conflictReason: `The installed package identity could not be verified: ${error?.message || error}`,
    };
  }

  return { identityStatus: 'verified', installed: true, identity: expected };
}
