import fs from 'fs';
import path from 'path';
import { ToolRegistry } from '../server/tools/registry';
import { registerAllTools } from '../server/tools/definitions';

function countBy<T extends string>(values: T[]): Record<T, number> {
  return values.reduce((counts, value) => {
    counts[value] = (counts[value] || 0) + 1;
    return counts;
  }, {} as Record<T, number>);
}

function markdownRows(values: Record<string, number>): string[] {
  return Object.entries(values)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, count]) => `| ${name} | ${count} |`);
}

const workspaceRoot = process.cwd();
const registry = new ToolRegistry();
registerAllTools(registry);
const manifest = registry.getCapabilityManifest();
const bundledRoot = path.join(workspaceRoot, 'server', 'skills', 'bundled');
const bundledSkills = fs.existsSync(bundledRoot)
  ? fs.readdirSync(bundledRoot, { withFileTypes: true })
    .filter(entry => entry.isDirectory() && fs.existsSync(path.join(bundledRoot, entry.name, 'package.json')))
    .map(entry => entry.name)
    .sort()
  : [];
const materialSideEffectTypes = new Set([
  'local_write',
  'local_state_change',
  'desktop_control',
  'external_state_change',
  'external_communication',
  'credential_access',
  'process_execution',
  'installation',
]);
const sideEffectCapabilities = manifest.filter(entry => (
  entry.sideEffects.some(effect => materialSideEffectTypes.has(effect.type))
));
const materializedEvidence = sideEffectCapabilities.filter(entry => entry.evidence);
const explicitEvidence = sideEffectCapabilities.filter(entry => (
  entry.evidence?.declarationSource === 'tool_definition'
));
const materializedRisk = sideEffectCapabilities.filter(entry => entry.risk !== 'none');
const explicitRisk = sideEffectCapabilities.filter(entry => (
  entry.metadataSources.risk === 'tool_definition'
));
const missingExplicitEvidence = sideEffectCapabilities.filter(entry => (
  entry.evidence?.declarationSource !== 'tool_definition'
));
const missingExplicitRisk = sideEffectCapabilities.filter(entry => (
  entry.metadataSources.risk !== 'tool_definition'
));

function inlineNames(entries: typeof manifest): string {
  return entries.length
    ? entries.map(entry => `\`${entry.toolName}\``).join(', ')
    : '_None_';
}

const generated = [
  '# Runtime capability statistics',
  '',
  '> Generated by `npm run docs:capability-stats`. Do not edit counts manually.',
  '',
  `- Registered tool capabilities: **${manifest.length}**`,
  `- Bundled maintained skill packages: **${bundledSkills.length}**`,
  `- Material side-effect capabilities: **${sideEffectCapabilities.length}**`,
  `- Material side-effect capabilities with a materialized evidence contract: **${materializedEvidence.length}/${sideEffectCapabilities.length}**`,
  `- Material side-effect capabilities with materialized non-none risk: **${materializedRisk.length}/${sideEffectCapabilities.length}**`,
  `- Material side-effect capabilities with tool-specific evidence metadata: **${explicitEvidence.length}/${sideEffectCapabilities.length}**`,
  `- Material side-effect capabilities with tool-specific risk metadata: **${explicitRisk.length}/${sideEffectCapabilities.length}**`,
  '',
  '> Read-only local/network access is excluded from the material side-effect gate. Materialized policy metadata is conservative fallback, not proof that the tool owner supplied an exact contract. Release readiness requires the tool-specific counts to reach 100%.',
  '',
  '## Release metadata gaps',
  '',
  `- Missing tool-specific evidence: ${inlineNames(missingExplicitEvidence)}`,
  `- Missing tool-specific risk: ${inlineNames(missingExplicitRisk)}`,
  '',
  '## By source',
  '',
  '| Source | Count |',
  '| --- | ---: |',
  ...markdownRows(countBy(manifest.map(entry => entry.source))),
  '',
  '## By lane',
  '',
  '| Lane | Count |',
  '| --- | ---: |',
  ...markdownRows(countBy(manifest.map(entry => entry.lane))),
  '',
  '## Bundled skill packages',
  '',
  bundledSkills.map(name => `\`${name}\``).join(', '),
  '',
  `Generated at build time from commit source; schema version: ${manifest[0] ? 1 : 0}.`,
  '',
].join('\n');

const outputPath = path.join(workspaceRoot, 'docs', 'generated', 'capability-stats.md');
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, generated, 'utf8');
console.log(`[capability-stats] wrote ${path.relative(workspaceRoot, outputPath)} (${manifest.length} tools, ${bundledSkills.length} bundled skills)`);
process.exit(0);
