import fs from 'node:fs';
import path from 'node:path';

const CLEANUP_MIGRATION = 'runtimeCapabilityCleanupV1';
const CLEANUP_VERSION = 1;
const FILESYSTEM_MIGRATION = 'desktopBuiltinFilesystem';
const FILESYSTEM_VERSION = 2;

interface RuntimeServerConfig {
  command?: string;
  args?: string[];
  enabled?: boolean;
  autoGenerated?: boolean;
  description?: string;
  [key: string]: unknown;
}

interface RuntimeMCPConfig {
  mcpServers: Record<string, RuntimeServerConfig>;
  migrations?: Record<string, number>;
  [key: string]: unknown;
}

export interface RuntimeCapabilityCleanupOptions {
  configPath: string;
  skillsDir: string;
  quarantineRoot: string;
  now?: Date;
}

export interface RuntimeCapabilityCleanupReport {
  migration: typeof CLEANUP_MIGRATION;
  version: number;
  applied: boolean;
  configPath: string;
  backupPath?: string;
  skillManifestPath?: string;
  reportPath?: string;
  removedServerNames: string[];
  quarantinedSkills: Array<{
    name: string;
    sourcePath: string;
    quarantinePath: string;
  }>;
  filesystemDisabled: boolean;
  errors: Array<{
    name: string;
    message: string;
  }>;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function parseConfig(raw: string): RuntimeMCPConfig {
  const parsed: unknown = JSON.parse(raw);
  if (!isRecord(parsed)) throw new Error('MCP config root must be an object.');
  if (isRecord(parsed.mcpServers)) {
    return {
      ...parsed,
      mcpServers: parsed.mcpServers as Record<string, RuntimeServerConfig>,
    };
  }
  return { mcpServers: parsed as Record<string, RuntimeServerConfig> };
}

function isGeneratedSkillDirectory(skillDir: string): boolean {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(skillDir, 'package.json'), 'utf8'));
    if (pkg?.lumi?.autoGenerated === true) return true;
  } catch {
    // A missing or malformed package manifest is not enough to classify a skill.
  }

  try {
    const source = fs.readFileSync(path.join(skillDir, 'index.ts'), 'utf8');
    return source.includes('Auto-generated Lumi Skill');
  } catch {
    return false;
  }
}

function isLegacyDefaultFilesystem(server: RuntimeServerConfig | undefined): boolean {
  if (!server || server.command !== 'npx' || !Array.isArray(server.args)) return false;
  return server.args.includes('@modelcontextprotocol/server-filesystem')
    && server.args.includes('.');
}

function safeTimestamp(now: Date): string {
  return now.toISOString().replace(/[:.]/g, '-');
}

function uniqueDestination(parent: string, name: string): string {
  const preferred = path.join(parent, name);
  if (!fs.existsSync(preferred)) return preferred;
  for (let suffix = 2; suffix < 10_000; suffix += 1) {
    const candidate = path.join(parent, `${name}-${suffix}`);
    if (!fs.existsSync(candidate)) return candidate;
  }
  throw new Error(`Unable to allocate quarantine destination for "${name}".`);
}

function moveDirectoryRecoverably(source: string, destination: string): void {
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  try {
    fs.renameSync(source, destination);
    return;
  } catch (error: any) {
    if (error?.code !== 'EXDEV') throw error;
  }

  fs.cpSync(source, destination, { recursive: true, errorOnExist: true });
  fs.rmSync(source, { recursive: true, force: false });
}

function writeJson(filePath: string, value: unknown): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

function readSkillManifest(skillsDir: string, config: RuntimeMCPConfig): Array<Record<string, unknown>> {
  if (!fs.existsSync(skillsDir)) return [];
  return fs.readdirSync(skillsDir, { withFileTypes: true })
    .filter(entry => entry.isDirectory() && !entry.name.startsWith('.staging-'))
    .map(entry => {
      const skillDir = path.join(skillsDir, entry.name);
      let pkg: Record<string, unknown> | null = null;
      try {
        const parsed = JSON.parse(fs.readFileSync(path.join(skillDir, 'package.json'), 'utf8'));
        if (isRecord(parsed)) pkg = parsed;
      } catch {
        // Preserve the directory name even when its historical manifest is bad.
      }
      return {
        name: entry.name,
        sourcePath: skillDir,
        generated: isGeneratedSkillDirectory(skillDir),
        configured: Boolean(config.mcpServers[entry.name]),
        enabled: config.mcpServers[entry.name]?.enabled === true,
        package: pkg,
      };
    })
    .sort((left, right) => String(left.name).localeCompare(String(right.name)));
}

/**
 * One-time product migration for the old executable-skill runtime.
 *
 * Historical model-generated skills are moved, not deleted. Their original
 * config is backed up beside the quarantine report so the migration remains
 * recoverable without keeping those tools active.
 */
export function runRuntimeCapabilityCleanup(
  options: RuntimeCapabilityCleanupOptions,
): RuntimeCapabilityCleanupReport {
  const report: RuntimeCapabilityCleanupReport = {
    migration: CLEANUP_MIGRATION,
    version: CLEANUP_VERSION,
    applied: false,
    configPath: options.configPath,
    removedServerNames: [],
    quarantinedSkills: [],
    filesystemDisabled: false,
    errors: [],
  };

  const raw = fs.readFileSync(options.configPath, 'utf8');
  const config = parseConfig(raw);
  const migrations = isRecord(config.migrations)
    ? config.migrations as Record<string, number>
    : {};
  const cleanupPending = Number(migrations[CLEANUP_MIGRATION] || 0) < CLEANUP_VERSION;
  const filesystem = config.mcpServers.filesystem;
  const filesystemPending = Number(migrations[FILESYSTEM_MIGRATION] || 0) < FILESYSTEM_VERSION;

  if (!cleanupPending && !filesystemPending) return report;

  const generatedNames = new Set<string>();
  if (cleanupPending) {
    for (const [name, server] of Object.entries(config.mcpServers)) {
      if (server?.autoGenerated === true) generatedNames.add(name);
    }

    if (fs.existsSync(options.skillsDir)) {
      for (const entry of fs.readdirSync(options.skillsDir, { withFileTypes: true })) {
        if (!entry.isDirectory() || entry.name.startsWith('.staging-')) continue;
        const skillDir = path.join(options.skillsDir, entry.name);
        if (isGeneratedSkillDirectory(skillDir)) generatedNames.add(entry.name);
      }
    }
  }

  const migrationDir = path.join(
    options.quarantineRoot,
    safeTimestamp(options.now || new Date()),
  );
  fs.mkdirSync(migrationDir, { recursive: true });
  const backupPath = path.join(migrationDir, 'mcp_config.before.json');
  fs.copyFileSync(options.configPath, backupPath);
  report.backupPath = backupPath;
  const skillManifestPath = path.join(migrationDir, 'skill-manifest.before.json');
  writeJson(skillManifestPath, readSkillManifest(options.skillsDir, config));
  report.skillManifestPath = skillManifestPath;

  if (cleanupPending) {
    const quarantinedNames = new Set<string>();
    for (const name of [...generatedNames].sort((left, right) => left.localeCompare(right))) {
      const sourcePath = path.join(options.skillsDir, name);
      if (!fs.existsSync(sourcePath)) {
        quarantinedNames.add(name);
        continue;
      }

      try {
        const quarantinePath = uniqueDestination(path.join(migrationDir, 'skills'), name);
        moveDirectoryRecoverably(sourcePath, quarantinePath);
        quarantinedNames.add(name);
        report.quarantinedSkills.push({ name, sourcePath, quarantinePath });
      } catch (error: any) {
        report.errors.push({
          name,
          message: String(error?.message || error || 'Unknown quarantine failure'),
        });
      }
    }

    for (const name of quarantinedNames) {
      if (config.mcpServers[name]) {
        delete config.mcpServers[name];
        report.removedServerNames.push(name);
      }
    }

    if (report.errors.length === 0) {
      migrations[CLEANUP_MIGRATION] = CLEANUP_VERSION;
    }
  }

  if (filesystemPending) {
    if (isLegacyDefaultFilesystem(filesystem)) {
      filesystem.enabled = false;
      filesystem.description = 'Legacy external filesystem MCP disabled: Lumi uses built-in native file tools.';
      report.filesystemDisabled = true;
    }
    migrations[FILESYSTEM_MIGRATION] = FILESYSTEM_VERSION;
  }

  config.migrations = migrations;
  writeJson(options.configPath, config);
  report.removedServerNames.sort((left, right) => left.localeCompare(right));
  report.applied = true;

  const reportPath = path.join(migrationDir, 'migration-report.json');
  report.reportPath = reportPath;
  writeJson(reportPath, report);
  return report;
}

export interface RuntimeCapabilityCleanupRollbackReport {
  rolledBack: boolean;
  reportPath: string;
  configPath: string;
  rollbackBackupPath?: string;
  restoredSkills: string[];
  errors: Array<{ name: string; message: string }>;
}

/**
 * Recover the exact config and quarantined skill directories captured by one
 * cleanup report. Existing source directories are never overwritten.
 */
export function rollbackRuntimeCapabilityCleanup(
  reportPath: string,
): RuntimeCapabilityCleanupRollbackReport {
  const result: RuntimeCapabilityCleanupRollbackReport = {
    rolledBack: false,
    reportPath,
    configPath: '',
    restoredSkills: [],
    errors: [],
  };
  const report = JSON.parse(fs.readFileSync(reportPath, 'utf8')) as RuntimeCapabilityCleanupReport;
  result.configPath = report.configPath;
  if (!report.backupPath || !fs.existsSync(report.backupPath)) {
    throw new Error('Runtime cleanup rollback cannot continue: the config backup is missing.');
  }

  for (const skill of report.quarantinedSkills || []) {
    if (fs.existsSync(skill.sourcePath)) {
      result.errors.push({
        name: skill.name,
        message: `Restore target already exists: ${skill.sourcePath}`,
      });
    } else if (!fs.existsSync(skill.quarantinePath)) {
      result.errors.push({
        name: skill.name,
        message: `Quarantined source is missing: ${skill.quarantinePath}`,
      });
    }
  }
  if (result.errors.length > 0) return result;

  const rollbackBackupPath = path.join(
    path.dirname(reportPath),
    'mcp_config.before-rollback.json',
  );
  fs.copyFileSync(report.configPath, rollbackBackupPath);
  result.rollbackBackupPath = rollbackBackupPath;

  const moved: Array<{ sourcePath: string; quarantinePath: string; name: string }> = [];
  try {
    for (const skill of report.quarantinedSkills || []) {
      moveDirectoryRecoverably(skill.quarantinePath, skill.sourcePath);
      moved.push(skill);
      result.restoredSkills.push(skill.name);
    }
    fs.copyFileSync(report.backupPath, report.configPath);
    result.rolledBack = true;
    return result;
  } catch (error: any) {
    for (const skill of moved.reverse()) {
      try {
        if (fs.existsSync(skill.sourcePath) && !fs.existsSync(skill.quarantinePath)) {
          moveDirectoryRecoverably(skill.sourcePath, skill.quarantinePath);
        }
      } catch {
        // Report the primary rollback failure while preserving best-effort recovery.
      }
    }
    fs.copyFileSync(rollbackBackupPath, report.configPath);
    result.errors.push({
      name: 'rollback',
      message: String(error?.message || error || 'Unknown rollback failure'),
    });
    return result;
  }
}
